// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;art.breaks.ck&lt;/c&gt;.</summary>
public sealed class ArtBreaksClient(SdkHttp http)
{
    /// <summary>
    /// List break artwork
    /// Every kind the station holds a picture for
    /// </summary>
    public async Task<BreakArtworkList> ListBreakArtworkAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("art", "breaks"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<BreakArtworkList>(response);
    }

    /// <summary>
    /// Replace break artwork
    /// Puts an operator's own picture behind a kind of break. The id does not change, so a URL already on the wire keeps working and the ETag is what says the picture moved
    /// </summary>
    /// <exception cref="SdkException">On 400, 413, 415.</exception>
    public async Task<BreakArtworkList> ReplaceBreakArtworkAsync(string kind, IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("art", "breaks", http.Segment(kind)),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<BreakArtworkList>(response);
    }

    /// <summary>
    /// Revert break artwork
    /// Puts the picture this repository ships back. The shipped file is read at this moment rather than copied at install, so an upgrade that improved it is what comes back
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<BreakArtworkList> RevertBreakArtworkAsync(string kind, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("art", "breaks", http.Segment(kind)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<BreakArtworkList>(response);
    }
}
