// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;art.personas.ck&lt;/c&gt;.</summary>
public sealed class ArtPersonasClient(SdkHttp http)
{
    /// <summary>
    /// List persona portraits
    /// Every persona that has a portrait
    /// </summary>
    public async Task<PersonaPortraitList> ListPersonaPortraitsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("art", "personas"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PersonaPortraitList>(response);
    }

    /// <summary>
    /// Replace persona portrait
    /// Puts a picture on a persona. A persona that already had one keeps its URL, so a player holding it picks up the new picture
    /// </summary>
    /// <exception cref="SdkException">On 400, 413, 415.</exception>
    public async Task<PersonaPortraitList> ReplacePersonaPortraitAsync(Guid personaId, IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("art", "personas", http.Segment(personaId)),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PersonaPortraitList>(response);
    }

    /// <summary>
    /// Remove persona portrait
    /// Takes a persona's picture away. A player shows the record's cover instead
    /// </summary>
    public async Task<PersonaPortraitList> RemovePersonaPortraitAsync(Guid personaId, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("art", "personas", http.Segment(personaId)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PersonaPortraitList>(response);
    }
}
