// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;charts.ck&lt;/c&gt;.</summary>
public sealed class ChartsClient(SdkHttp http)
{
    /// <summary>
    /// List charts
    /// Every chart every installed chart plugin currently offers
    /// </summary>
    public async Task<StationChartList> ListChartsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("charts"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationChartList>(response);
    }

    /// <summary>
    /// Read chart
    /// One chart's records, ranked
    /// </summary>
    public async Task<ChartPage> ReadChartAsync(string id, ChartQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("charts", http.Segment(id)),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ChartPage>(response);
    }
}
