// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;nowplaying.ck&lt;/c&gt;.</summary>
public sealed class NowplayingClient(SdkHttp http)
{
    /// <summary>
    /// Get now playing
    /// What is on air right now. Answers 200 with `onAir: false` when the station is quiet, so a device polling this treats silence as an answer rather than an error
    /// </summary>
    public async Task<NowPlaying> GetNowPlayingAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("nowplaying"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<NowPlaying>(response);
    }
}
