// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;plugins.ck&lt;/c&gt;.</summary>
public sealed class PluginsClient(SdkHttp http)
{
    /// <summary>
    /// List plugins
    /// Lists every plugin the host knows about
    /// </summary>
    public async Task<List<PluginSummary>> ListPluginsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<List<PluginSummary>>(response);
    }

    /// <summary>
    /// List plugin grants
    /// Every capability an installed plugin is asking the operator for, with the answer so far
    /// </summary>
    public async Task<PluginGrantList> ListPluginGrantsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", "grants"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginGrantList>(response);
    }

    /// <summary>
    /// Rescan plugins
    /// Rescans the mounted plugin directory: registers new plugins, unloads removed ones
    /// </summary>
    public async Task<List<PluginSummary>> RescanPluginsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", "rescan"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<List<PluginSummary>>(response);
    }

    /// <summary>
    /// Import plugin
    /// Takes a plugin in from the browser as the tarball npm pack writes and puts it in the plugins directory. It lands disabled, and a newer version of an installed plugin replaces the older one
    /// </summary>
    /// <exception cref="SdkException">On 400, 409, 413, 415, 422.</exception>
    public async Task<PluginImportResult> ImportPluginAsync(IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", "import"),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginImportResult>(response);
    }

    /// <summary>
    /// Get plugin
    /// One plugin, including its stored non-secret configuration and last error
    /// </summary>
    public async Task<PluginDetail> GetPluginAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Update plugin configuration
    /// Validates against the plugin's own config schema, encrypts secrets, persists, and reinitializes
    /// </summary>
    public async Task<PluginDetail> UpdatePluginConfigurationAsync(string id, PluginConfigInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("plugins", http.Segment(id), "config"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Enable plugin
    /// Enables a plugin without resubmitting its configuration
    /// </summary>
    public async Task<PluginDetail> EnablePluginAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", http.Segment(id), "enable"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Disable plugin
    /// Disables a plugin and tears its instance down, keeping its configuration
    /// </summary>
    public async Task<PluginDetail> DisablePluginAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", http.Segment(id), "disable"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Decide plugin grant
    /// Answers one capability this plugin asked for. Takes effect on the next fetch, with no reload
    /// </summary>
    public async Task<PluginGrantList> DecidePluginGrantAsync(string id, PluginGrantInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("plugins", http.Segment(id), "grants"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginGrantList>(response);
    }

    /// <summary>
    /// Reload plugin
    /// Reapplies the plugin's stored configuration: disposes the running instance and initializes it again
    /// </summary>
    public async Task<PluginDetail> ReloadPluginAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", http.Segment(id), "reload"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Test plugin connection
    /// Runs the plugin's own `testConnection()` through the invoker
    /// </summary>
    public async Task<PluginTestResult> TestPluginConnectionAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", http.Segment(id), "test"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginTestResult>(response);
    }

    /// <summary>
    /// Suggest plugin config options
    /// Asks the plugin what to offer for its config fields right now, through the invoker
    /// </summary>
    public async Task<PluginFieldSuggestions> SuggestPluginConfigOptionsAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("plugins", http.Segment(id), "config", "suggestions"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginFieldSuggestions>(response);
    }

    /// <summary>
    /// Get plugin logs
    /// Returns the plugin's buffered log lines at or above the current log level
    /// </summary>
    public async Task<PluginLogPage> GetPluginLogsAsync(string id, PluginLogQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", http.Segment(id), "logs"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginLogPage>(response);
    }

    /// <summary>
    /// Download plugin logs
    /// Streams the plugin's full retained log as a plain-text attachment
    /// </summary>
    public async Task<DownloadPluginLogsResult> DownloadPluginLogsAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", http.Segment(id), "logs", "download"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        var headers = new DownloadPluginLogsHeaders(
            response.Header("Content-Disposition") is { } contentDisposition ? contentDisposition : null);
        return new DownloadPluginLogsResult(response.Text, headers);
    }

    /// <summary>
    /// Set plugin log level
    /// Sets the minimum severity the plugin's log store retains going forward
    /// </summary>
    public async Task<PluginDetail> SetPluginLogLevelAsync(string id, PluginLogLevelInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("plugins", http.Segment(id), "logs", "level"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Start plugin OAuth authorization
    /// Reports where to send the operator for the provider's consent screen
    /// </summary>
    public async Task<PluginOAuthStart> StartPluginOAuthAuthorizationAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", http.Segment(id), "oauth", "authorize"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginOAuthStart>(response);
    }

    /// <summary>
    /// Disconnect plugin OAuth
    /// Forgets the plugin's stored OAuth tokens and reinitializes it
    /// </summary>
    public async Task<PluginDetail> DisconnectPluginOAuthAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("plugins", http.Segment(id), "oauth"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginDetail>(response);
    }

    /// <summary>
    /// Complete plugin OAuth authorization
    /// Completes the flow. Anonymous: the provider redirects the browser here with no session of ours
    /// </summary>
    public async Task<PluginOAuthResult> CompletePluginOAuthAuthorizationAsync(string id, PluginOAuthCallbackQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("plugins", http.Segment(id), "oauth", "callback"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PluginOAuthResult>(response);
    }
}

/// <summary>Response headers declared on GET /plugins/{id}/logs/download.</summary>
public sealed record DownloadPluginLogsHeaders(string? ContentDisposition);

/// <summary>The body of GET /plugins/{id}/logs/download, with the response headers the contract declares.</summary>
public sealed record DownloadPluginLogsResult(string Data, DownloadPluginLogsHeaders Headers);
