// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;productions.ck&lt;/c&gt;.</summary>
public sealed class ProductionsClient(SdkHttp http)
{
    /// <summary>
    /// List productions
    /// Everything the station has made or is making, newest first
    /// </summary>
    public async Task<ProductionList> ListProductionsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("productions"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ProductionList>(response);
    }

    /// <summary>
    /// Request production
    /// Asks the station to make one. It is queued, not started
    /// </summary>
    public async Task<Production> RequestProductionAsync(ProductionRequest body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("productions"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Production>(response);
    }

    /// <summary>
    /// Cancel production
    /// Stops a production being made, for good
    /// </summary>
    public async Task<Production> CancelProductionAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("productions", http.Segment(id), "cancel"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Production>(response);
    }
}
