// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;render.ck&lt;/c&gt;.</summary>
public sealed class RenderClient(SdkHttp http)
{
    /// <summary>
    /// List segments
    /// Everything the station can play that is not a record
    /// </summary>
    public async Task<SegmentList> ListSegmentsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("segments"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<SegmentList>(response);
    }

    /// <summary>
    /// Create segment
    /// Plans something for the station to say, and starts rendering it
    /// </summary>
    public async Task<Segment> CreateSegmentAsync(SegmentCreate body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("segments"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Segment>(response);
    }

    /// <summary>
    /// Upload segment
    /// Takes a recording in from the browser and puts it in the library, ready to air
    /// </summary>
    /// <exception cref="SdkException">On 400, 413, 415.</exception>
    public async Task<Segment> UploadSegmentAsync(IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("segments", "upload"),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Segment>(response);
    }

    /// <summary>
    /// Scan the segment inbox
    /// Takes whatever audio is sitting in the inbox directory into the library. Safe to repeat: a segment is identified by its audio, so the same recording arriving twice is one segment
    /// </summary>
    public async Task<SegmentScanResult> ScanTheSegmentInboxAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("segments", "scan"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<SegmentScanResult>(response);
    }

    /// <summary>
    /// Read script history
    /// What the station has written lately, newest first, one page at a time
    /// </summary>
    public async Task<ScriptHistoryPage> ReadScriptHistoryAsync(ScriptHistoryQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("scripts"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScriptHistoryPage>(response);
    }

    /// <summary>
    /// Rate script
    /// What the operator thought of this attempt. Nothing acts on it automatically
    /// </summary>
    public async Task<ScriptAttempt> RateScriptAsync(Guid id, ScriptRatingInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("scripts", http.Segment(id), "rating"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScriptAttempt>(response);
    }

    /// <summary>
    /// Read script summary
    /// Write attempts by outcome, per presenter, over a recent window
    /// </summary>
    public async Task<ScriptHistorySummary> ReadScriptSummaryAsync(ScriptHistorySummaryQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("scripts", "summary"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScriptHistorySummary>(response);
    }

    /// <summary>
    /// List voices
    /// The voices the station can be asked to speak in
    /// </summary>
    public async Task<VoiceList> ListVoicesAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("voices"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<VoiceList>(response);
    }

    /// <summary>
    /// Get default voice sample
    /// A short line spoken in whichever voice the plugin falls back to
    /// </summary>
    public async Task<GetDefaultVoiceSampleResponse> GetDefaultVoiceSampleAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("voices", "sample"),
            expectStatuses: new[] { 304 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 304:
            {
                return new GetDefaultVoiceSampleResponse.Status304();
            }

            default:
            {
                var headers = new GetDefaultVoiceSample200Headers(
                    response.Header("cache-control") is { } cacheControl ? cacheControl : null,
                    response.Header("etag") is { } etag ? etag : null);
                switch (response.ContentType)
                {
                    case "audio/wav":
                        return new GetDefaultVoiceSampleResponse.Status200AudioWav(response.Bytes, headers);
                    case "audio/ogg":
                        return new GetDefaultVoiceSampleResponse.Status200AudioOgg(response.Bytes, headers);
                    case "audio/flac":
                        return new GetDefaultVoiceSampleResponse.Status200AudioFlac(response.Bytes, headers);
                    case "audio/mp4":
                        return new GetDefaultVoiceSampleResponse.Status200AudioMp4(response.Bytes, headers);
                    default:
                        return new GetDefaultVoiceSampleResponse.Status200AudioMpeg(response.Bytes, headers);
                }
            }
        }
    }

    /// <summary>
    /// Get voice sample
    /// A short line spoken in one voice, so an operator can hear it before choosing it
    /// </summary>
    public async Task<GetVoiceSampleResponse> GetVoiceSampleAsync(string voiceId, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("voices", http.Segment(voiceId), "sample"),
            expectStatuses: new[] { 304 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 304:
            {
                return new GetVoiceSampleResponse.Status304();
            }

            default:
            {
                var headers = new GetVoiceSample200Headers(
                    response.Header("cache-control") is { } cacheControl ? cacheControl : null,
                    response.Header("etag") is { } etag ? etag : null);
                switch (response.ContentType)
                {
                    case "audio/wav":
                        return new GetVoiceSampleResponse.Status200AudioWav(response.Bytes, headers);
                    case "audio/ogg":
                        return new GetVoiceSampleResponse.Status200AudioOgg(response.Bytes, headers);
                    case "audio/flac":
                        return new GetVoiceSampleResponse.Status200AudioFlac(response.Bytes, headers);
                    case "audio/mp4":
                        return new GetVoiceSampleResponse.Status200AudioMp4(response.Bytes, headers);
                    default:
                        return new GetVoiceSampleResponse.Status200AudioMpeg(response.Bytes, headers);
                }
            }
        }
    }

    /// <summary>
    /// Preview speech
    /// Speaks the caller's words in one voice, so a break can be heard before it is written for air
    /// </summary>
    public async Task<PreviewSpeechResponse> PreviewSpeechAsync(SpeechPreviewRequest body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("voices", "preview"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.ContentType)
        {
            case "audio/wav":
                return new PreviewSpeechResponse.AudioWav(response.Bytes);
            case "audio/ogg":
                return new PreviewSpeechResponse.AudioOgg(response.Bytes);
            case "audio/flac":
                return new PreviewSpeechResponse.AudioFlac(response.Bytes);
            case "audio/mp4":
                return new PreviewSpeechResponse.AudioMp4(response.Bytes);
            default:
                return new PreviewSpeechResponse.AudioMpeg(response.Bytes);
        }
    }

    /// <summary>
    /// Delete segment
    /// Removes a recording and the inbox file behind it, so the next scan does not read it back in
    /// </summary>
    /// <exception cref="SdkException">On 404, 409.</exception>
    public async Task<SegmentList> DeleteSegmentAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("segments", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<SegmentList>(response);
    }

    /// <summary>
    /// Get segment audio
    /// The audio of one segment
    /// </summary>
    public async Task<GetSegmentAudioResponse> GetSegmentAudioAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("segments", http.Segment(id), "audio"),
            expectStatuses: new[] { 304 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 304:
            {
                return new GetSegmentAudioResponse.Status304();
            }

            default:
            {
                var headers = new GetSegmentAudio200Headers(
                    response.Header("cache-control") is { } cacheControl ? cacheControl : null,
                    response.Header("etag") is { } etag ? etag : null);
                switch (response.ContentType)
                {
                    case "audio/wav":
                        return new GetSegmentAudioResponse.Status200AudioWav(response.Bytes, headers);
                    case "audio/ogg":
                        return new GetSegmentAudioResponse.Status200AudioOgg(response.Bytes, headers);
                    case "audio/flac":
                        return new GetSegmentAudioResponse.Status200AudioFlac(response.Bytes, headers);
                    case "audio/mp4":
                        return new GetSegmentAudioResponse.Status200AudioMp4(response.Bytes, headers);
                    default:
                        return new GetSegmentAudioResponse.Status200AudioMpeg(response.Bytes, headers);
                }
            }
        }
    }

    /// <summary>
    /// Get stored audio
    /// Audio out of the segment store, addressed by content rather than by row
    /// </summary>
    public async Task<GetStoredAudioResponse> GetStoredAudioAsync(string checksum, string ext, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("audio", http.Segment(checksum), http.Segment(ext)),
            expectStatuses: new[] { 304 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 304:
            {
                return new GetStoredAudioResponse.Status304();
            }

            default:
            {
                var headers = new GetStoredAudio200Headers(
                    response.Header("cache-control") is { } cacheControl ? cacheControl : null,
                    response.Header("etag") is { } etag ? etag : null);
                switch (response.ContentType)
                {
                    case "audio/wav":
                        return new GetStoredAudioResponse.Status200AudioWav(response.Bytes, headers);
                    case "audio/ogg":
                        return new GetStoredAudioResponse.Status200AudioOgg(response.Bytes, headers);
                    case "audio/flac":
                        return new GetStoredAudioResponse.Status200AudioFlac(response.Bytes, headers);
                    case "audio/mp4":
                        return new GetStoredAudioResponse.Status200AudioMp4(response.Bytes, headers);
                    default:
                        return new GetStoredAudioResponse.Status200AudioMpeg(response.Bytes, headers);
                }
            }
        }
    }

    /// <summary>
    /// List pronunciations
    /// The station's lexicon: what it says, what has been proposed to it, and what it has turned down
    /// </summary>
    public async Task<PronunciationList> ListPronunciationsAsync(PronunciationQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("pronunciations"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PronunciationList>(response);
    }

    /// <summary>
    /// Create pronunciation
    /// Adds one the operator typed. It is said from the next render on
    /// </summary>
    public async Task<PronunciationList> CreatePronunciationAsync(PronunciationWrite body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("pronunciations"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PronunciationList>(response);
    }

    /// <summary>
    /// Update pronunciation
    /// Rewrites one entry's words, whoever proposed it
    /// </summary>
    public async Task<PronunciationList> UpdatePronunciationAsync(Guid id, PronunciationWrite body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("pronunciations", http.Segment(id)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PronunciationList>(response);
    }

    /// <summary>
    /// Delete pronunciation
    /// Removes an entry outright. Turning a PROPOSAL down is a state rather than a deletion, because a deleted one comes back on the next pass
    /// </summary>
    public async Task<PronunciationList> DeletePronunciationAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("pronunciations", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PronunciationList>(response);
    }

    /// <summary>
    /// Set pronunciation state
    /// Accepts a proposal, turns one down, or takes an entry out of use without losing what it said
    /// </summary>
    public async Task<PronunciationList> SetPronunciationStateAsync(Guid id, PronunciationStateWrite body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("pronunciations", http.Segment(id), "state"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PronunciationList>(response);
    }

    /// <summary>
    /// List pads
    /// Every sound the station holds, board by board
    /// </summary>
    public async Task<PadList> ListPadsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("pads"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Upload pad
    /// Takes a sound in from the browser and puts it on a board. The file lands in the pad library on disk, so it survives a rebuild and an archive carries it
    /// </summary>
    /// <exception cref="SdkException">On 400, 409, 413, 415.</exception>
    public async Task<PadList> UploadPadAsync(IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("pads"),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Scan the pad library
    /// Takes whatever audio is sitting in the pad library directory onto its board. Safe to repeat: a file nobody has touched is seen and left alone
    /// </summary>
    public async Task<PadScanResult> ScanThePadLibraryAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("pads", "scan"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadScanResult>(response);
    }

    /// <summary>
    /// Fetch pad
    /// Fetches a sound from an address and puts it on a board. The operator names the address, so this is them choosing a file exactly as dropping one in the library is
    /// </summary>
    /// <exception cref="SdkException">On 400, 409, 413, 415, 502.</exception>
    public async Task<PadList> FetchPadAsync(PadFetch body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("pads", "fetch"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Delete pad
    /// Removes a sound the console put there, and the file it wrote for it
    /// </summary>
    /// <exception cref="SdkException">On 404, 409.</exception>
    public async Task<PadList> DeletePadAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("pads", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Set pad state
    /// Turns a sound down, or puts one back. Answers the whole rack, since one pad changing state is one row moving between two sections of the same page
    /// </summary>
    public async Task<PadList> SetPadStateAsync(Guid id, PadState body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("pads", http.Segment(id), "state"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Get pad audio
    /// The sound itself, so an operator can hear what they dropped in
    /// </summary>
    public async Task<GetPadAudioResponse> GetPadAudioAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("pads", http.Segment(id), "audio"),
            expectStatuses: new[] { 304 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 304:
            {
                return new GetPadAudioResponse.Status304();
            }

            default:
            {
                var headers = new GetPadAudio200Headers(
                    response.Header("cache-control") is { } cacheControl ? cacheControl : null,
                    response.Header("etag") is { } etag ? etag : null);
                switch (response.ContentType)
                {
                    case "audio/wav":
                        return new GetPadAudioResponse.Status200AudioWav(response.Bytes, headers);
                    case "audio/ogg":
                        return new GetPadAudioResponse.Status200AudioOgg(response.Bytes, headers);
                    case "audio/flac":
                        return new GetPadAudioResponse.Status200AudioFlac(response.Bytes, headers);
                    case "audio/mp4":
                        return new GetPadAudioResponse.Status200AudioMp4(response.Bytes, headers);
                    default:
                        return new GetPadAudioResponse.Status200AudioMpeg(response.Bytes, headers);
                }
            }
        }
    }

    /// <summary>
    /// Create pad set
    /// Names a new set, or answers the one already under that key
    /// </summary>
    public async Task<PadList> CreatePadSetAsync(PadSetWrite body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("pads", "sets"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Update pad set
    /// Renames a set. The KEY moves with it, so every persona naming the old one stops finding it
    /// </summary>
    public async Task<PadList> UpdatePadSetAsync(Guid id, PadSetWrite body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("pads", "sets", http.Segment(id)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Delete pad set
    /// Removes a set and its memberships, and no pads at all
    /// </summary>
    public async Task<PadList> DeletePadSetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("pads", "sets", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }

    /// <summary>
    /// Set pad membership
    /// Puts a pad on a set or takes it off. Refused where the set already answers to that name, because a script writes a name
    /// </summary>
    public async Task<PadList> SetPadMembershipAsync(Guid id, PadSetMembership body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("pads", "sets", http.Segment(id), "pads"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PadList>(response);
    }
}

/// <summary>Response headers declared on GET /voices/sample.</summary>
public sealed record GetDefaultVoiceSample200Headers(string? CacheControl, string? Etag);

/// <summary>
/// What GET /voices/sample returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetDefaultVoiceSampleResponse
{
    private GetDefaultVoiceSampleResponse() { }

    public sealed record Status200AudioMpeg(byte[] Data, GetDefaultVoiceSample200Headers Headers) : GetDefaultVoiceSampleResponse;

    public sealed record Status200AudioWav(byte[] Data, GetDefaultVoiceSample200Headers Headers) : GetDefaultVoiceSampleResponse;

    public sealed record Status200AudioOgg(byte[] Data, GetDefaultVoiceSample200Headers Headers) : GetDefaultVoiceSampleResponse;

    public sealed record Status200AudioFlac(byte[] Data, GetDefaultVoiceSample200Headers Headers) : GetDefaultVoiceSampleResponse;

    public sealed record Status200AudioMp4(byte[] Data, GetDefaultVoiceSample200Headers Headers) : GetDefaultVoiceSampleResponse;

    public sealed record Status304() : GetDefaultVoiceSampleResponse;
}

/// <summary>Response headers declared on GET /voices/{voiceId}/sample.</summary>
public sealed record GetVoiceSample200Headers(string? CacheControl, string? Etag);

/// <summary>
/// What GET /voices/{voiceId}/sample returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetVoiceSampleResponse
{
    private GetVoiceSampleResponse() { }

    public sealed record Status200AudioMpeg(byte[] Data, GetVoiceSample200Headers Headers) : GetVoiceSampleResponse;

    public sealed record Status200AudioWav(byte[] Data, GetVoiceSample200Headers Headers) : GetVoiceSampleResponse;

    public sealed record Status200AudioOgg(byte[] Data, GetVoiceSample200Headers Headers) : GetVoiceSampleResponse;

    public sealed record Status200AudioFlac(byte[] Data, GetVoiceSample200Headers Headers) : GetVoiceSampleResponse;

    public sealed record Status200AudioMp4(byte[] Data, GetVoiceSample200Headers Headers) : GetVoiceSampleResponse;

    public sealed record Status304() : GetVoiceSampleResponse;
}

/// <summary>
/// What POST /voices/preview returned.
///
/// The status declares several content types, so which one arrived is part of the value.
/// </summary>
public abstract record PreviewSpeechResponse
{
    private PreviewSpeechResponse() { }

    public sealed record AudioMpeg(byte[] Data) : PreviewSpeechResponse;

    public sealed record AudioWav(byte[] Data) : PreviewSpeechResponse;

    public sealed record AudioOgg(byte[] Data) : PreviewSpeechResponse;

    public sealed record AudioFlac(byte[] Data) : PreviewSpeechResponse;

    public sealed record AudioMp4(byte[] Data) : PreviewSpeechResponse;
}

/// <summary>Response headers declared on GET /segments/{id}/audio.</summary>
public sealed record GetSegmentAudio200Headers(string? CacheControl, string? Etag);

/// <summary>
/// What GET /segments/{id}/audio returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetSegmentAudioResponse
{
    private GetSegmentAudioResponse() { }

    public sealed record Status200AudioMpeg(byte[] Data, GetSegmentAudio200Headers Headers) : GetSegmentAudioResponse;

    public sealed record Status200AudioWav(byte[] Data, GetSegmentAudio200Headers Headers) : GetSegmentAudioResponse;

    public sealed record Status200AudioOgg(byte[] Data, GetSegmentAudio200Headers Headers) : GetSegmentAudioResponse;

    public sealed record Status200AudioFlac(byte[] Data, GetSegmentAudio200Headers Headers) : GetSegmentAudioResponse;

    public sealed record Status200AudioMp4(byte[] Data, GetSegmentAudio200Headers Headers) : GetSegmentAudioResponse;

    public sealed record Status304() : GetSegmentAudioResponse;
}

/// <summary>Response headers declared on GET /audio/{checksum}/{ext}.</summary>
public sealed record GetStoredAudio200Headers(string? CacheControl, string? Etag);

/// <summary>
/// What GET /audio/{checksum}/{ext} returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetStoredAudioResponse
{
    private GetStoredAudioResponse() { }

    public sealed record Status200AudioMpeg(byte[] Data, GetStoredAudio200Headers Headers) : GetStoredAudioResponse;

    public sealed record Status200AudioWav(byte[] Data, GetStoredAudio200Headers Headers) : GetStoredAudioResponse;

    public sealed record Status200AudioOgg(byte[] Data, GetStoredAudio200Headers Headers) : GetStoredAudioResponse;

    public sealed record Status200AudioFlac(byte[] Data, GetStoredAudio200Headers Headers) : GetStoredAudioResponse;

    public sealed record Status200AudioMp4(byte[] Data, GetStoredAudio200Headers Headers) : GetStoredAudioResponse;

    public sealed record Status304() : GetStoredAudioResponse;
}

/// <summary>Response headers declared on GET /pads/{id}/audio.</summary>
public sealed record GetPadAudio200Headers(string? CacheControl, string? Etag);

/// <summary>
/// What GET /pads/{id}/audio returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetPadAudioResponse
{
    private GetPadAudioResponse() { }

    public sealed record Status200AudioMpeg(byte[] Data, GetPadAudio200Headers Headers) : GetPadAudioResponse;

    public sealed record Status200AudioWav(byte[] Data, GetPadAudio200Headers Headers) : GetPadAudioResponse;

    public sealed record Status200AudioOgg(byte[] Data, GetPadAudio200Headers Headers) : GetPadAudioResponse;

    public sealed record Status200AudioFlac(byte[] Data, GetPadAudio200Headers Headers) : GetPadAudioResponse;

    public sealed record Status200AudioMp4(byte[] Data, GetPadAudio200Headers Headers) : GetPadAudioResponse;

    public sealed record Status304() : GetPadAudioResponse;
}
