// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;schedule.ck&lt;/c&gt;.</summary>
public sealed class ScheduleClient(SdkHttp http)
{
    /// <summary>
    /// List schedule
    /// Every slot in this station's schedule, earliest in the day first
    /// </summary>
    public async Task<ScheduleSlotList> ListScheduleAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("schedule"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleSlotList>(response);
    }

    /// <summary>
    /// Create schedule slot
    /// Adds a slot. The station does not change over until its start time comes round
    /// </summary>
    public async Task<ScheduleSlotList> CreateScheduleSlotAsync(ScheduleSlotInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("schedule"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleSlotList>(response);
    }

    /// <summary>
    /// Read current slot
    /// Which slot the clock says should be on, and which one the station is actually airing
    /// </summary>
    public async Task<ScheduleNow> ReadCurrentSlotAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("schedule", "current"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleNow>(response);
    }

    /// <summary>
    /// Read timetable
    /// The station's day as blocks, contiguous and gapless, for drawing
    /// </summary>
    public async Task<ScheduleTimetable> ReadTimetableAsync(ScheduleTimetableQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("schedule", "timetable"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleTimetable>(response);
    }

    /// <summary>
    /// Update schedule slot
    /// Rewrites a slot. Takes effect at its next boundary rather than immediately
    /// </summary>
    public async Task<ScheduleSlotList> UpdateScheduleSlotAsync(string id, ScheduleSlotInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("schedule", http.Segment(id)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleSlotList>(response);
    }

    /// <summary>
    /// Delete schedule slot
    /// Removes a slot. Whatever is on air stays on until the next slot begins
    /// </summary>
    public async Task<ScheduleSlotList> DeleteScheduleSlotAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("schedule", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<ScheduleSlotList>(response);
    }
}
