// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;station.playlists.ck&lt;/c&gt;.</summary>
public sealed class StationPlaylistsClient(SdkHttp http)
{
    /// <summary>
    /// List station playlists
    /// Every playlist the station owns, newest first
    /// </summary>
    public async Task<StationPlaylistList> ListStationPlaylistsAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("station-playlists"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationPlaylistList>(response);
    }

    /// <summary>
    /// Get station playlist
    /// One station playlist with its records in order, placeholders included
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<StationPlaylistDetail> GetStationPlaylistAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("station-playlists", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationPlaylistDetail>(response);
    }

    /// <summary>
    /// Update station playlist
    /// Renames a station playlist, or rewrites what it is for
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<StationPlaylist> UpdateStationPlaylistAsync(Guid id, StationPlaylistUpdate body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            SdkHttp.Patch,
            http.Path("station-playlists", http.Segment(id)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationPlaylist>(response);
    }

    /// <summary>
    /// Delete station playlist
    /// Deletes a station playlist. The records it named stay in the library
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task DeleteStationPlaylistAsync(Guid id, CancellationToken cancellationToken = default)
    {
        await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("station-playlists", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Fill station playlist
    /// Looks up the records this playlist names and the library does not hold, in the background, and adds the ones a provider has. The activity feed says how it went
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task FillStationPlaylistAsync(Guid id, CancellationToken cancellationToken = default)
    {
        await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("station-playlists", http.Segment(id), "fill"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Export station playlist
    /// One station playlist as a file another station can import
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<ExportStationPlaylistResult> ExportStationPlaylistAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("station-playlists", http.Segment(id), "export"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        var headers = new ExportStationPlaylistHeaders(
            response.Header("Content-Disposition") is { } contentDisposition ? contentDisposition : null);
        return new ExportStationPlaylistResult(http.ReadJson<PlaylistFile>(response), headers);
    }

    /// <summary>
    /// Preview playlist import
    /// Reads a source and reports which of its records the library holds and which it would have to find. Writes nothing
    /// </summary>
    public async Task<PlaylistImportPlan> PreviewPlaylistImportAsync(PlaylistImportInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("station-playlists", "import", "preview"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PlaylistImportPlan>(response);
    }

    /// <summary>
    /// Import playlist
    /// Makes a new station playlist from a source and answers with what it did
    /// </summary>
    public async Task<PlaylistImportResult> ImportPlaylistAsync(PlaylistImportInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("station-playlists", "import"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<PlaylistImportResult>(response);
    }
}

/// <summary>Response headers declared on GET /station-playlists/{id}/export.</summary>
public sealed record ExportStationPlaylistHeaders(string? ContentDisposition);

/// <summary>The body of GET /station-playlists/{id}/export, with the response headers the contract declares.</summary>
public sealed record ExportStationPlaylistResult(PlaylistFile Data, ExportStationPlaylistHeaders Headers);
