// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;station.ck&lt;/c&gt;.</summary>
public sealed class StationClient(SdkHttp http)
{
    /// <summary>
    /// Read station attention
    /// Everything wrong or waiting, worst first, each with the console page that can act on it
    /// </summary>
    public async Task<StationAttention> ReadStationAttentionAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("station", "attention"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationAttention>(response);
    }

    /// <summary>
    /// Read station checkup
    /// The loops the station runs and how much of the library it has looked at
    /// </summary>
    public async Task<StationCheckup> ReadStationCheckupAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("station", "checkup"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<StationCheckup>(response);
    }
}
