// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MaroonedSoftware.Deadair.Sdk.Models;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;traces.ck&lt;/c&gt;.</summary>
public sealed class TracesClient(SdkHttp http)
{
    /// <summary>
    /// Read traces
    /// Recent decisions, newest first, folded to one row each
    /// </summary>
    public async Task<TracesPage> ReadTracesAsync(TracesQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("traces"),
            query: http.Params(query),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<TracesPage>(response);
    }

    /// <summary>
    /// Read trace
    /// One decision: every call it made, and the decisions on either side of it
    /// </summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<TraceDetail> ReadTraceAsync(string id, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("traces", http.Segment(id)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<TraceDetail>(response);
    }
}
