// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Entry point to the generated SDK.
///
/// Holds one `SdkHttp`, shared by every client, so the SDK keeps a single configuration and transport.
public final class Deadair: Sendable {
    public let http: SdkHttp
    public let activity: ActivityClient
    public let art: ArtClient
    public let authentication: AuthenticationClient
    public let authenticationFactor: AuthenticationFactorClient
    public let authenticationSessions: AuthenticationSessionsClient
    public let catalog: CatalogClient
    public let charts: ChartsClient
    public let clock: ClockClient
    public let director: DirectorClient
    public let history: HistoryClient
    public let news: NewsClient
    public let nowplaying: NowplayingClient
    public let onboarding: OnboardingClient
    public let personasAuditions: PersonasAuditionsClient
    public let personas: PersonasClient
    public let playlists: PlaylistsClient
    public let playout: PlayoutClient
    public let plugins: PluginsClient
    public let productions: ProductionsClient
    public let render: RenderClient
    public let schedule: ScheduleClient
    public let settings: SettingsClient
    public let logs: LogsClient
    public let station: StationClient
    public let traces: TracesClient
    public let storage: StorageClient
    public let stream: StreamClient
    public let topics: TopicsClient

    public init(config: SdkConfig) {
        let http = SdkHttp(config: config)
        self.http = http
        self.activity = ActivityClient(http: http)
        self.art = ArtClient(http: http)
        self.authentication = AuthenticationClient(http: http)
        self.authenticationFactor = AuthenticationFactorClient(http: http)
        self.authenticationSessions = AuthenticationSessionsClient(http: http)
        self.catalog = CatalogClient(http: http)
        self.charts = ChartsClient(http: http)
        self.clock = ClockClient(http: http)
        self.director = DirectorClient(http: http)
        self.history = HistoryClient(http: http)
        self.news = NewsClient(http: http)
        self.nowplaying = NowplayingClient(http: http)
        self.onboarding = OnboardingClient(http: http)
        self.personasAuditions = PersonasAuditionsClient(http: http)
        self.personas = PersonasClient(http: http)
        self.playlists = PlaylistsClient(http: http)
        self.playout = PlayoutClient(http: http)
        self.plugins = PluginsClient(http: http)
        self.productions = ProductionsClient(http: http)
        self.render = RenderClient(http: http)
        self.schedule = ScheduleClient(http: http)
        self.settings = SettingsClient(http: http)
        self.logs = LogsClient(http: http)
        self.station = StationClient(http: http)
        self.traces = TracesClient(http: http)
        self.storage = StorageClient(http: http)
        self.stream = StreamClient(http: http)
        self.topics = TopicsClient(http: http)
    }

    /// The SDK against `baseURL`, with `headers` added to every request.
    public convenience init(baseURL: URL, headers: @escaping @Sendable () async throws -> [String: String] = { [:] }) {
        self.init(config: SdkConfig(baseURL: baseURL, headers: headers))
    }
}
