// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A language pack: every word the console says, in one language, as the file a translator made. The same document is exported, imported and stored. The console's language only; what the station broadcasts in is the `stream.language` setting
public struct ConsoleLanguagePack: Codable, Equatable, Sendable {
    /// Says the file is a console language pack
    public var format: String
    /// The version of the document's shape. This station reads version 1
    public var version: Int
    /// The language, as a BCP 47 tag such as `de` or `pt-BR`. Never English, which is built into the console
    public var locale: String
    /// The language's name in itself, as the console's picker shows it: `Deutsch`, not `German`
    public var name: String
    /// Which way its text runs
    public var direction: ConsoleLanguagePackDirection
    /// The console version the pack was translated against. Empty when the file did not say
    public var madeFor: String
    /// The strings, nested by namespace and then by key, in the English catalog's shape. Every value is text or a further level of nesting
    public var catalog: [String: JSONValue]

    public init(format: String = "deadair.console-language", version: Int, locale: String, name: String, direction: ConsoleLanguagePackDirection, madeFor: String, catalog: [String: JSONValue]) {
        self.format = format
        self.version = version
        self.locale = locale
        self.name = name
        self.direction = direction
        self.madeFor = madeFor
        self.catalog = catalog
    }

    private enum CodingKeys: String, CodingKey {
        case format = "format"
        case version = "version"
        case locale = "locale"
        case name = "name"
        case direction = "direction"
        case madeFor = "madeFor"
        case catalog = "catalog"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.format = try container.decode(String.self, forKey: .format)
        guard self.format == "deadair.console-language" else {
            throw DecodingError.dataCorruptedError(forKey: .format, in: container, debugDescription: "Expected \"deadair.console-language\"")
        }
        self.version = try container.decode(Int.self, forKey: .version)
        self.locale = try container.decode(String.self, forKey: .locale)
        self.name = try container.decode(String.self, forKey: .name)
        self.direction = try container.decode(ConsoleLanguagePackDirection.self, forKey: .direction)
        self.madeFor = try container.decode(String.self, forKey: .madeFor)
        self.catalog = try container.decode([String: JSONValue].self, forKey: .catalog)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.format, forKey: .format)
        try container.encode(self.version, forKey: .version)
        try container.encode(self.locale, forKey: .locale)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.direction, forKey: .direction)
        try container.encode(self.madeFor, forKey: .madeFor)
        try container.encode(self.catalog, forKey: .catalog)
    }
}

/// A language the console can be shown in on this station, without its strings
public struct ConsoleLanguage: Codable, Equatable, Sendable {
    public var locale: String
    public var name: String
    public var direction: ConsoleLanguageDirection
    public var madeFor: String
    /// When the pack now installed for it was imported
    public var importedAt: Date

    public init(locale: String, name: String, direction: ConsoleLanguageDirection, madeFor: String, importedAt: Date) {
        self.locale = locale
        self.name = name
        self.direction = direction
        self.madeFor = madeFor
        self.importedAt = importedAt
    }

    private enum CodingKeys: String, CodingKey {
        case locale = "locale"
        case name = "name"
        case direction = "direction"
        case madeFor = "madeFor"
        case importedAt = "importedAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.locale = try container.decode(String.self, forKey: .locale)
        self.name = try container.decode(String.self, forKey: .name)
        self.direction = try container.decode(ConsoleLanguageDirection.self, forKey: .direction)
        self.madeFor = try container.decode(String.self, forKey: .madeFor)
        self.importedAt = try container.decode(Date.self, forKey: .importedAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.locale, forKey: .locale)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.direction, forKey: .direction)
        try container.encode(self.madeFor, forKey: .madeFor)
        try container.encode(self.importedAt, forKey: .importedAt)
    }
}

public struct ConsoleLanguageList: Codable, Equatable, Sendable {
    /// In order of their tags. English is built in and is never listed
    public var languages: [ConsoleLanguage]

    public init(languages: [ConsoleLanguage]) {
        self.languages = languages
    }

    private enum CodingKeys: String, CodingKey {
        case languages = "languages"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.languages = try container.decode([ConsoleLanguage].self, forKey: .languages)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.languages, forKey: .languages)
    }
}

/// Which way its text runs
public enum ConsoleLanguagePackDirection: String, Codable, CaseIterable, Sendable {
    case ltr = "ltr"
    case rtl = "rtl"
}

public enum ConsoleLanguageDirection: String, Codable, CaseIterable, Sendable {
    case ltr = "ltr"
    case rtl = "rtl"
}
