// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Five values, where `PluginLogLevel` next door has four. The plugin enum is the narrower one on
/// purpose — that is the vocabulary a plugin's own `PluginLogger` offers — while `api.log` is written
/// by `DeadairLogger`, which tees every level the app-wide `Logger` has, `trace` included. Narrowing
/// here would make a `trace` line unrepresentable in the type of the surface that reads the file it
/// is in.
public enum LogLevel: String, Codable, CaseIterable, Sendable {
    case trace = "trace"
    case debug = "debug"
    case info = "info"
    case warn = "warn"
    case error = "error"
}

/// One log file this install has, whether or not anything has been written to it
public struct LogSource: Codable, Equatable, Sendable {
    /// A closed set the API owns: `api`, `liquidsoap`, `shim`. Never a path
    public var id: String
    public var label: String
    /// What writes it, in a sentence, because "shim" means nothing to somebody who has not read the tree
    public var description: String
    /// Whether the file is there at all. A station that never ran the stream has no stream logs, which is a state rather than a fault
    public var present: Bool
    /// Whether its lines carry a level, so the console knows whether to offer the filter
    public var levels: Bool
    /// Retained size across every segment. Zero when absent
    public var bytes: Int
    /// Absent when nothing has ever been written
    public var lastWriteAt: Date?

    public init(id: String, label: String, description: String, present: Bool, levels: Bool, bytes: Int, lastWriteAt: Date? = nil) {
        self.id = id
        self.label = label
        self.description = description
        self.present = present
        self.levels = levels
        self.bytes = bytes
        self.lastWriteAt = lastWriteAt
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case label = "label"
        case description = "description"
        case present = "present"
        case levels = "levels"
        case bytes = "bytes"
        case lastWriteAt = "lastWriteAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.label = try container.decode(String.self, forKey: .label)
        self.description = try container.decode(String.self, forKey: .description)
        self.present = try container.decode(Bool.self, forKey: .present)
        self.levels = try container.decode(Bool.self, forKey: .levels)
        self.bytes = try container.decode(Int.self, forKey: .bytes)
        self.lastWriteAt = try container.decodeIfPresent(Date.self, forKey: .lastWriteAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.label, forKey: .label)
        try container.encode(self.description, forKey: .description)
        try container.encode(self.present, forKey: .present)
        try container.encode(self.levels, forKey: .levels)
        try container.encode(self.bytes, forKey: .bytes)
        try container.encodeIfPresent(self.lastWriteAt, forKey: .lastWriteAt)
    }
}

/// One line, as far as it could be read back
public struct LogLine: Codable, Equatable, Sendable {
    /// Absent on a line this API did not write, and on one of its own that did not parse
    public var ts: String?
    /// Absent for the same two reasons
    public var level: LogLevel?
    /// Must match MAX_LINE_BYTES_CEILING in apps/api/src/logging/rotating.log.store.ts. Change both together
    public var text: String

    public init(ts: String? = nil, level: LogLevel? = nil, text: String) {
        self.ts = ts
        self.level = level
        self.text = text
    }

    private enum CodingKeys: String, CodingKey {
        case ts = "ts"
        case level = "level"
        case text = "text"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.ts = try container.decodeIfPresent(String.self, forKey: .ts)
        self.level = try container.decodeIfPresent(LogLevel.self, forKey: .level)
        self.text = try container.decode(String.self, forKey: .text)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.ts, forKey: .ts)
        try container.encodeIfPresent(self.level, forKey: .level)
        try container.encode(self.text, forKey: .text)
    }
}

public struct LogQuery: Codable, Equatable, Sendable {
    public var limit: Int?
    /// Ignored by a source whose lines carry no level
    public var level: LogLevel?

    public init(limit: Int? = nil, level: LogLevel? = nil) {
        self.limit = limit
        self.level = level
    }

    private enum CodingKeys: String, CodingKey {
        case limit = "limit"
        case level = "level"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.limit = try container.decodeIfPresent(Int.self, forKey: .limit)
        self.level = try container.decodeIfPresent(LogLevel.self, forKey: .level)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.limit, forKey: .limit)
        try container.encodeIfPresent(self.level, forKey: .level)
    }
}

public struct LogSourceList: Codable, Equatable, Sendable {
    /// Every source, in a fixed order, including the ones that are not present
    public var sources: [LogSource]

    public init(sources: [LogSource]) {
        self.sources = sources
    }

    private enum CodingKeys: String, CodingKey {
        case sources = "sources"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.sources = try container.decode([LogSource].self, forKey: .sources)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.sources, forKey: .sources)
    }
}

public struct LogPage: Codable, Equatable, Sendable {
    public var sourceId: String
    /// The minimum severity that was applied. Absent when the source carries no levels, so a filter that did nothing cannot look as though it worked
    public var level: LogLevel?
    /// Whether the read hit its byte budget, so the oldest line here is not the file's first
    public var truncated: Bool
    /// Newest first, as the plugin log page, the activity feed and the script history all send
    public var lines: [LogLine]

    public init(sourceId: String, level: LogLevel? = nil, truncated: Bool, lines: [LogLine]) {
        self.sourceId = sourceId
        self.level = level
        self.truncated = truncated
        self.lines = lines
    }

    private enum CodingKeys: String, CodingKey {
        case sourceId = "sourceId"
        case level = "level"
        case truncated = "truncated"
        case lines = "lines"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.sourceId = try container.decode(String.self, forKey: .sourceId)
        self.level = try container.decodeIfPresent(LogLevel.self, forKey: .level)
        self.truncated = try container.decode(Bool.self, forKey: .truncated)
        self.lines = try container.decode([LogLine].self, forKey: .lines)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.sourceId, forKey: .sourceId)
        try container.encodeIfPresent(self.level, forKey: .level)
        try container.encode(self.truncated, forKey: .truncated)
        try container.encode(self.lines, forKey: .lines)
    }
}
