// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A one-time code that links a chat account to the signed-in station account. Shown once: send it to the station's bot as `/link CODE` in a direct message
public struct MessagingLinkCode: Codable, Equatable, Sendable {
    /// The code itself. Case does not matter when it is sent
    public var code: String
    /// When the code stops working. A new code replaces any earlier one
    public var expiresAt: Date

    public init(code: String, expiresAt: Date) {
        self.code = code
        self.expiresAt = expiresAt
    }

    private enum CodingKeys: String, CodingKey {
        case code = "code"
        case expiresAt = "expiresAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.code = try container.decode(String.self, forKey: .code)
        self.expiresAt = try container.decode(Date.self, forKey: .expiresAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.code, forKey: .code)
        try container.encode(self.expiresAt, forKey: .expiresAt)
    }
}

/// A chat account linked to the signed-in station account. Operator commands sent from it run with this account's permissions
public struct MessagingLink: Codable, Equatable, Sendable {
    /// Which messaging plugin the chat account is on, for example `deadair.telegram`
    public var pluginId: String
    /// The chat platform's own id for the person
    public var platformUserId: String
    /// What the chat platform called them when they linked
    public var displayName: String
    /// When the link was made
    public var createdAt: Date

    public init(pluginId: String, platformUserId: String, displayName: String, createdAt: Date) {
        self.pluginId = pluginId
        self.platformUserId = platformUserId
        self.displayName = displayName
        self.createdAt = createdAt
    }

    private enum CodingKeys: String, CodingKey {
        case pluginId = "pluginId"
        case platformUserId = "platformUserId"
        case displayName = "displayName"
        case createdAt = "createdAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.platformUserId = try container.decode(String.self, forKey: .platformUserId)
        self.displayName = try container.decode(String.self, forKey: .displayName)
        self.createdAt = try container.decode(Date.self, forKey: .createdAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.platformUserId, forKey: .platformUserId)
        try container.encode(self.displayName, forKey: .displayName)
        try container.encode(self.createdAt, forKey: .createdAt)
    }
}

/// Every chat account linked to the signed-in station account, newest first
public struct MessagingLinkList: Codable, Equatable, Sendable {
    public var links: [MessagingLink]

    public init(links: [MessagingLink]) {
        self.links = links
    }

    private enum CodingKeys: String, CodingKey {
        case links = "links"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.links = try container.decode([MessagingLink].self, forKey: .links)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.links, forKey: .links)
    }
}
