// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Something the station can read out, as one installed plugin describes it
public struct StationSeries: Codable, Equatable, Sendable {
    /// Unique across the station: the plugin's own id for the series, qualified with the plugin that offered it
    public var id: String
    public var pluginId: String
    /// What the series is called, which is what a presenter says out loud
    public var title: String
    /// How it is worked through: `serial` from the beginning in order, `latest` its newest piece and nothing once that has aired
    public var order: StationSeriesOrder
    public var author: String?
    /// What the series says about itself, as plain text
    public var description: String?
    public var artworkUrl: String?
    public var homeUrl: String?
    /// ISO 639-1, or the source's own tag. Also what the station splits sentences by when it cuts a long piece up
    public var language: String?

    public init(id: String, pluginId: String, title: String, order: StationSeriesOrder, author: String? = nil, description: String? = nil, artworkUrl: String? = nil, homeUrl: String? = nil, language: String? = nil) {
        self.id = id
        self.pluginId = pluginId
        self.title = title
        self.order = order
        self.author = author
        self.description = description
        self.artworkUrl = artworkUrl
        self.homeUrl = homeUrl
        self.language = language
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case pluginId = "pluginId"
        case title = "title"
        case order = "order"
        case author = "author"
        case description = "description"
        case artworkUrl = "artworkUrl"
        case homeUrl = "homeUrl"
        case language = "language"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.title = try container.decode(String.self, forKey: .title)
        self.order = try container.decode(StationSeriesOrder.self, forKey: .order)
        self.author = try container.decodeIfPresent(String.self, forKey: .author)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.artworkUrl = try container.decodeIfPresent(String.self, forKey: .artworkUrl)
        self.homeUrl = try container.decodeIfPresent(String.self, forKey: .homeUrl)
        self.language = try container.decodeIfPresent(String.self, forKey: .language)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.title, forKey: .title)
        try container.encode(self.order, forKey: .order)
        try container.encodeIfPresent(self.author, forKey: .author)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(self.homeUrl, forKey: .homeUrl)
        try container.encodeIfPresent(self.language, forKey: .language)
    }
}

/// One instalment, and what the station has done with it
public struct StationPiece: Codable, Equatable, Sendable {
    /// The station's own id for this piece
    public var id: String
    /// Qualified, matching `StationSeries.id`
    public var seriesId: String
    /// The plugin's own id for the piece, stable across refreshes
    public var pieceId: String
    public var seriesTitle: String
    public var title: String
    /// How its series is worked through, copied onto the piece by every refresh
    public var order: StationPieceOrder
    public var author: String?
    /// What it is about, as plain text
    public var summary: String?
    /// The piece's page, for a person
    public var url: String?
    public var artworkUrl: String?
    /// Where it comes in a serial, from 0. Absent for a `latest` series
    public var ordinal: Int?
    /// ISO-8601
    public var publishedAt: String?
    /// Roughly how many words it runs to, as the plugin counted them
    public var wordCount: Int?
    /// ISO-8601: when a refresh last saw it listed
    public var seenAt: String
    /// ISO-8601: when a refresh found its plugin no longer listing it. The station never picks a withdrawn piece; the row is kept so what was done with it is not lost
    public var withdrawnAt: String?
    /// Whether the station has the spoken audio, ready to air
    public var rendered: Bool
    /// Whether the words are being spoken right now
    public var rendering: Bool
    /// ISO-8601: when the station last asked for it to be spoken
    public var renderRequestedAt: String?
    /// Why the last attempt to speak it failed, when it did
    public var renderError: String?
    /// ISO-8601: the slot it was made for
    public var scheduledFor: String?
    /// ISO-8601: when a listener could first have heard it. A piece airs once, and for a serial this is also the station's place in the book
    public var airedAt: String?

    public init(id: String, seriesId: String, pieceId: String, seriesTitle: String, title: String, order: StationPieceOrder, author: String? = nil, summary: String? = nil, url: String? = nil, artworkUrl: String? = nil, ordinal: Int? = nil, publishedAt: String? = nil, wordCount: Int? = nil, seenAt: String, withdrawnAt: String? = nil, rendered: Bool, rendering: Bool, renderRequestedAt: String? = nil, renderError: String? = nil, scheduledFor: String? = nil, airedAt: String? = nil) {
        self.id = id
        self.seriesId = seriesId
        self.pieceId = pieceId
        self.seriesTitle = seriesTitle
        self.title = title
        self.order = order
        self.author = author
        self.summary = summary
        self.url = url
        self.artworkUrl = artworkUrl
        self.ordinal = ordinal
        self.publishedAt = publishedAt
        self.wordCount = wordCount
        self.seenAt = seenAt
        self.withdrawnAt = withdrawnAt
        self.rendered = rendered
        self.rendering = rendering
        self.renderRequestedAt = renderRequestedAt
        self.renderError = renderError
        self.scheduledFor = scheduledFor
        self.airedAt = airedAt
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case seriesId = "seriesId"
        case pieceId = "pieceId"
        case seriesTitle = "seriesTitle"
        case title = "title"
        case order = "order"
        case author = "author"
        case summary = "summary"
        case url = "url"
        case artworkUrl = "artworkUrl"
        case ordinal = "ordinal"
        case publishedAt = "publishedAt"
        case wordCount = "wordCount"
        case seenAt = "seenAt"
        case withdrawnAt = "withdrawnAt"
        case rendered = "rendered"
        case rendering = "rendering"
        case renderRequestedAt = "renderRequestedAt"
        case renderError = "renderError"
        case scheduledFor = "scheduledFor"
        case airedAt = "airedAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.seriesId = try container.decode(String.self, forKey: .seriesId)
        self.pieceId = try container.decode(String.self, forKey: .pieceId)
        self.seriesTitle = try container.decode(String.self, forKey: .seriesTitle)
        self.title = try container.decode(String.self, forKey: .title)
        self.order = try container.decode(StationPieceOrder.self, forKey: .order)
        self.author = try container.decodeIfPresent(String.self, forKey: .author)
        self.summary = try container.decodeIfPresent(String.self, forKey: .summary)
        self.url = try container.decodeIfPresent(String.self, forKey: .url)
        self.artworkUrl = try container.decodeIfPresent(String.self, forKey: .artworkUrl)
        self.ordinal = try container.decodeIfPresent(Int.self, forKey: .ordinal)
        self.publishedAt = try container.decodeIfPresent(String.self, forKey: .publishedAt)
        self.wordCount = try container.decodeIfPresent(Int.self, forKey: .wordCount)
        self.seenAt = try container.decode(String.self, forKey: .seenAt)
        self.withdrawnAt = try container.decodeIfPresent(String.self, forKey: .withdrawnAt)
        self.rendered = try container.decode(Bool.self, forKey: .rendered)
        self.rendering = try container.decode(Bool.self, forKey: .rendering)
        self.renderRequestedAt = try container.decodeIfPresent(String.self, forKey: .renderRequestedAt)
        self.renderError = try container.decodeIfPresent(String.self, forKey: .renderError)
        self.scheduledFor = try container.decodeIfPresent(String.self, forKey: .scheduledFor)
        self.airedAt = try container.decodeIfPresent(String.self, forKey: .airedAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.seriesId, forKey: .seriesId)
        try container.encode(self.pieceId, forKey: .pieceId)
        try container.encode(self.seriesTitle, forKey: .seriesTitle)
        try container.encode(self.title, forKey: .title)
        try container.encode(self.order, forKey: .order)
        try container.encodeIfPresent(self.author, forKey: .author)
        try container.encodeIfPresent(self.summary, forKey: .summary)
        try container.encodeIfPresent(self.url, forKey: .url)
        try container.encodeIfPresent(self.artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(self.ordinal, forKey: .ordinal)
        try container.encodeIfPresent(self.publishedAt, forKey: .publishedAt)
        try container.encodeIfPresent(self.wordCount, forKey: .wordCount)
        try container.encode(self.seenAt, forKey: .seenAt)
        try container.encodeIfPresent(self.withdrawnAt, forKey: .withdrawnAt)
        try container.encode(self.rendered, forKey: .rendered)
        try container.encode(self.rendering, forKey: .rendering)
        try container.encodeIfPresent(self.renderRequestedAt, forKey: .renderRequestedAt)
        try container.encodeIfPresent(self.renderError, forKey: .renderError)
        try container.encodeIfPresent(self.scheduledFor, forKey: .scheduledFor)
        try container.encodeIfPresent(self.airedAt, forKey: .airedAt)
    }
}

public struct StationPieceQuery: Codable, Equatable, Sendable {
    /// One series' pieces in its own order, or absent for every series' newest first
    public var seriesId: String?
    public var limit: Int?

    public init(seriesId: String? = nil, limit: Int? = nil) {
        self.seriesId = seriesId
        self.limit = limit
    }

    private enum CodingKeys: String, CodingKey {
        case seriesId = "seriesId"
        case limit = "limit"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.seriesId = try container.decodeIfPresent(String.self, forKey: .seriesId)
        self.limit = try container.decodeIfPresent(Int.self, forKey: .limit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.seriesId, forKey: .seriesId)
        try container.encodeIfPresent(self.limit, forKey: .limit)
    }
}

public struct StationSeriesList: Codable, Equatable, Sendable {
    public var series: [StationSeries]

    public init(series: [StationSeries]) {
        self.series = series
    }

    private enum CodingKeys: String, CodingKey {
        case series = "series"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.series = try container.decode([StationSeries].self, forKey: .series)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.series, forKey: .series)
    }
}

public struct StationPiecePage: Codable, Equatable, Sendable {
    /// Empty when the station knows of none, which is not an error
    public var pieces: [StationPiece]

    public init(pieces: [StationPiece]) {
        self.pieces = pieces
    }

    private enum CodingKeys: String, CodingKey {
        case pieces = "pieces"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pieces = try container.decode([StationPiece].self, forKey: .pieces)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pieces, forKey: .pieces)
    }
}

/// How it is worked through: `serial` from the beginning in order, `latest` its newest piece and nothing once that has aired
public enum StationSeriesOrder: String, Codable, CaseIterable, Sendable {
    case serial = "serial"
    case latest = "latest"
}

/// How its series is worked through, copied onto the piece by every refresh
public enum StationPieceOrder: String, Codable, CaseIterable, Sendable {
    case serial = "serial"
    case latest = "latest"
}
