// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

public enum OnboardingRequirementKey: String, Codable, CaseIterable, Sendable {
    case adminAccount = "admin.account"
}

/// A single onboarding requirement
public struct CoreOnboardingRequirement: Codable, Equatable, Sendable {
    /// The key of the requirement
    public var key: OnboardingRequirementKey
    /// Human-readable label for the onboarding checklist
    public var title: String
    /// Optional longer explanation
    public var description: String?
    /// Whether the requirement is optional for onboarding
    public var optional: Bool

    public init(key: OnboardingRequirementKey, title: String, description: String? = nil, optional: Bool) {
        self.key = key
        self.title = title
        self.description = description
        self.optional = optional
    }

    private enum CodingKeys: String, CodingKey {
        case key = "key"
        case title = "title"
        case description = "description"
        case optional = "optional"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.key = try container.decode(OnboardingRequirementKey.self, forKey: .key)
        self.title = try container.decode(String.self, forKey: .title)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.optional = try container.decode(Bool.self, forKey: .optional)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.key, forKey: .key)
        try container.encode(self.title, forKey: .title)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encode(self.optional, forKey: .optional)
    }
}

/// A single onboarding requirement
public struct CoreOnboardingRequirementInput: Codable, Equatable, Sendable {
    /// The key of the requirement
    public var key: OnboardingRequirementKey

    public init(key: OnboardingRequirementKey) {
        self.key = key
    }

    private enum CodingKeys: String, CodingKey {
        case key = "key"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.key = try container.decode(OnboardingRequirementKey.self, forKey: .key)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.key, forKey: .key)
    }
}

public struct AdminAccountOnboardingRequirement: Codable, Equatable, Sendable {
    public var key: String
    /// Human-readable label for the onboarding checklist
    public var title: String
    /// Optional longer explanation
    public var description: String?
    /// Whether the requirement is optional for onboarding
    public var optional: Bool

    public init(key: String = "admin.account", title: String, description: String? = nil, optional: Bool) {
        self.key = key
        self.title = title
        self.description = description
        self.optional = optional
    }

    private enum CodingKeys: String, CodingKey {
        case key = "key"
        case title = "title"
        case description = "description"
        case optional = "optional"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.key = try container.decode(String.self, forKey: .key)
        guard self.key == "admin.account" else {
            throw DecodingError.dataCorruptedError(forKey: .key, in: container, debugDescription: "Expected \"admin.account\"")
        }
        self.title = try container.decode(String.self, forKey: .title)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.optional = try container.decode(Bool.self, forKey: .optional)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.key, forKey: .key)
        try container.encode(self.title, forKey: .title)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encode(self.optional, forKey: .optional)
    }
}

public struct AdminAccountOnboardingRequirementInput: Codable, Equatable, Sendable {
    public var key: String
    public var value: AdminAccountOnboardingRequirementValue

    public init(key: String = "admin.account", value: AdminAccountOnboardingRequirementValue) {
        self.key = key
        self.value = value
    }

    private enum CodingKeys: String, CodingKey {
        case key = "key"
        case value = "value"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.key = try container.decode(String.self, forKey: .key)
        guard self.key == "admin.account" else {
            throw DecodingError.dataCorruptedError(forKey: .key, in: container, debugDescription: "Expected \"admin.account\"")
        }
        self.value = try container.decode(AdminAccountOnboardingRequirementValue.self, forKey: .value)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.key, forKey: .key)
        try container.encode(self.value, forKey: .value)
    }
}

public typealias OnboardingRequirement = AdminAccountOnboardingRequirement
public typealias OnboardingRequirementInput = AdminAccountOnboardingRequirementInput

public struct AdminAccountOnboardingRequirementValue: Codable, Equatable, Sendable {
    public var email: String
    /// The password
    public var password: String

    public init(email: String, password: String) {
        self.email = email
        self.password = password
    }

    private enum CodingKeys: String, CodingKey {
        case email = "email"
        case password = "password"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.email = try container.decode(String.self, forKey: .email)
        self.password = try container.decode(String.self, forKey: .password)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.email, forKey: .email)
        try container.encode(self.password, forKey: .password)
    }
}
