// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// One of the station's mounts a speaker can play
public struct OutputMount: Codable, Equatable, Sendable {
    public var format: OutputMountFormat
    /// Same-origin path, leading slash included, as `/nowplaying` gives it
    public var path: String

    public init(format: OutputMountFormat, path: String) {
        self.format = format
        self.path = path
    }

    private enum CodingKeys: String, CodingKey {
        case format = "format"
        case path = "path"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.format = try container.decode(OutputMountFormat.self, forKey: .format)
        self.path = try container.decode(String.self, forKey: .path)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.format, forKey: .format)
        try container.encode(self.path, forKey: .path)
    }
}

/// A plugin that could not list its speakers
public struct OutputProblem: Codable, Equatable, Sendable {
    public var pluginId: String
    public var message: String

    public init(pluginId: String, message: String) {
        self.pluginId = pluginId
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case pluginId = "pluginId"
        case message = "message"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.message = try container.decode(String.self, forKey: .message)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.message, forKey: .message)
    }
}

/// A speaker the station is meant to be playing on, and how it is doing
public struct OutputCast: Codable, Equatable, Sendable {
    public var pluginId: String
    public var deviceId: String
    /// What the speaker was called when the cast started
    public var deviceName: String
    /// Which mount it plays
    public var mountPath: String
    public var startedAt: Date
    /// As the speaker reports it now. `opening` and `buffering` are a stream starting, not a failure; `stopped` with the station's stream still loaded is played again on its own; `unreachable` is a speaker that did not answer, which the station waits out
    public var phase: OutputCastPhase
    /// A sentence about the phase when it needs one, such as why a speaker is unreachable
    public var detail: String?

    public init(pluginId: String, deviceId: String, deviceName: String, mountPath: String, startedAt: Date, phase: OutputCastPhase, detail: String? = nil) {
        self.pluginId = pluginId
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.mountPath = mountPath
        self.startedAt = startedAt
        self.phase = phase
        self.detail = detail
    }

    private enum CodingKeys: String, CodingKey {
        case pluginId = "pluginId"
        case deviceId = "deviceId"
        case deviceName = "deviceName"
        case mountPath = "mountPath"
        case startedAt = "startedAt"
        case phase = "phase"
        case detail = "detail"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.deviceId = try container.decode(String.self, forKey: .deviceId)
        self.deviceName = try container.decode(String.self, forKey: .deviceName)
        self.mountPath = try container.decode(String.self, forKey: .mountPath)
        self.startedAt = try container.decode(Date.self, forKey: .startedAt)
        self.phase = try container.decode(OutputCastPhase.self, forKey: .phase)
        self.detail = try container.decodeIfPresent(String.self, forKey: .detail)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.deviceId, forKey: .deviceId)
        try container.encode(self.deviceName, forKey: .deviceName)
        try container.encode(self.mountPath, forKey: .mountPath)
        try container.encode(self.startedAt, forKey: .startedAt)
        try container.encode(self.phase, forKey: .phase)
        try container.encodeIfPresent(self.detail, forKey: .detail)
    }
}

/// Play the station on a speaker
public struct OutputCastRequest: Codable, Equatable, Sendable {
    public var pluginId: String
    public var deviceId: String
    /// Which mount, from the speaker's `mounts`. Absent means its first, which is MP3 wherever the speaker takes it
    public var mountPath: String?

    public init(pluginId: String, deviceId: String, mountPath: String? = nil) {
        self.pluginId = pluginId
        self.deviceId = deviceId
        self.mountPath = mountPath
    }

    private enum CodingKeys: String, CodingKey {
        case pluginId = "pluginId"
        case deviceId = "deviceId"
        case mountPath = "mountPath"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.deviceId = try container.decode(String.self, forKey: .deviceId)
        self.mountPath = try container.decodeIfPresent(String.self, forKey: .mountPath)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.deviceId, forKey: .deviceId)
        try container.encodeIfPresent(self.mountPath, forKey: .mountPath)
    }
}

/// A speaker the station can play on, as an `output` plugin listed it
public struct OutputDevice: Codable, Equatable, Sendable {
    /// The plugin that drives it, for example `deadair.cast`
    public var pluginId: String
    /// The plugin's own id for the speaker. Stable across restarts
    public var deviceId: String
    /// What the operator calls it
    public var name: String
    /// The make or model, where the speaker says
    public var model: String?
    /// How the plugin reaches it, for recognising rather than dialling
    public var address: String
    /// How it is driven, for a plugin that speaks several: `chromecast`, `upnp`, `bluos`
    public var `protocol`: String?
    /// The station's mounts this speaker can play, MP3 first. Empty when it plays none of the ones switched on
    public var mounts: [OutputMount]
    /// Whether the station is meant to be playing on it now. `/outputs/casts` says how that is going
    public var casting: Bool

    public init(pluginId: String, deviceId: String, name: String, model: String? = nil, address: String, `protocol`: String? = nil, mounts: [OutputMount], casting: Bool) {
        self.pluginId = pluginId
        self.deviceId = deviceId
        self.name = name
        self.model = model
        self.address = address
        self.`protocol` = `protocol`
        self.mounts = mounts
        self.casting = casting
    }

    private enum CodingKeys: String, CodingKey {
        case pluginId = "pluginId"
        case deviceId = "deviceId"
        case name = "name"
        case model = "model"
        case address = "address"
        case `protocol` = "protocol"
        case mounts = "mounts"
        case casting = "casting"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.deviceId = try container.decode(String.self, forKey: .deviceId)
        self.name = try container.decode(String.self, forKey: .name)
        self.model = try container.decodeIfPresent(String.self, forKey: .model)
        self.address = try container.decode(String.self, forKey: .address)
        self.`protocol` = try container.decodeIfPresent(String.self, forKey: .`protocol`)
        self.mounts = try container.decode([OutputMount].self, forKey: .mounts)
        self.casting = try container.decode(Bool.self, forKey: .casting)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.deviceId, forKey: .deviceId)
        try container.encode(self.name, forKey: .name)
        try container.encodeIfPresent(self.model, forKey: .model)
        try container.encode(self.address, forKey: .address)
        try container.encodeIfPresent(self.`protocol`, forKey: .`protocol`)
        try container.encode(self.mounts, forKey: .mounts)
        try container.encode(self.casting, forKey: .casting)
    }
}

/// Every speaker the station is meant to be playing on
public struct OutputCastList: Codable, Equatable, Sendable {
    public var casts: [OutputCast]

    public init(casts: [OutputCast]) {
        self.casts = casts
    }

    private enum CodingKeys: String, CodingKey {
        case casts = "casts"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.casts = try container.decode([OutputCast].self, forKey: .casts)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.casts, forKey: .casts)
    }
}

/// Every speaker every `output` plugin can play the station on
public struct OutputDeviceList: Codable, Equatable, Sendable {
    public var devices: [OutputDevice]
    /// Plugins that did not answer. Their speakers are missing from `devices` rather than the whole list failing
    public var problems: [OutputProblem]

    public init(devices: [OutputDevice], problems: [OutputProblem]) {
        self.devices = devices
        self.problems = problems
    }

    private enum CodingKeys: String, CodingKey {
        case devices = "devices"
        case problems = "problems"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.devices = try container.decode([OutputDevice].self, forKey: .devices)
        self.problems = try container.decode([OutputProblem].self, forKey: .problems)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.devices, forKey: .devices)
        try container.encode(self.problems, forKey: .problems)
    }
}

public enum OutputMountFormat: String, Codable, CaseIterable, Sendable {
    case mp3 = "mp3"
    case opus = "opus"
    case aac = "aac"
    case flac = "flac"
    case hls = "hls"
}

/// As the speaker reports it now. `opening` and `buffering` are a stream starting, not a failure; `stopped` with the station's stream still loaded is played again on its own; `unreachable` is a speaker that did not answer, which the station waits out
public enum OutputCastPhase: String, Codable, CaseIterable, Sendable {
    case idle = "idle"
    case opening = "opening"
    case buffering = "buffering"
    case playing = "playing"
    case stopped = "stopped"
    case unreachable = "unreachable"
}
