// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A programme the station carries, as one installed plugin describes it
public struct StationShow: Codable, Equatable, Sendable {
    /// Unique across the station: the plugin's own id for the show, qualified with the plugin that offered it
    public var id: String
    public var pluginId: String
    /// What the show is called, which is what a presenter says out loud
    public var title: String
    public var author: String?
    /// What the show says about itself, as plain text
    public var description: String?
    public var artworkUrl: String?
    public var homeUrl: String?
    /// Where its feed is, when the plugin reads one
    public var feedUrl: String?
    public var language: String?
    public var categories: [String]?
    /// Whether the publisher marked the whole show explicit. Absent means the publisher did not say, which is not the same as clean
    public var explicit: Bool?

    public init(id: String, pluginId: String, title: String, author: String? = nil, description: String? = nil, artworkUrl: String? = nil, homeUrl: String? = nil, feedUrl: String? = nil, language: String? = nil, categories: [String]? = nil, explicit: Bool? = nil) {
        self.id = id
        self.pluginId = pluginId
        self.title = title
        self.author = author
        self.description = description
        self.artworkUrl = artworkUrl
        self.homeUrl = homeUrl
        self.feedUrl = feedUrl
        self.language = language
        self.categories = categories
        self.explicit = explicit
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case pluginId = "pluginId"
        case title = "title"
        case author = "author"
        case description = "description"
        case artworkUrl = "artworkUrl"
        case homeUrl = "homeUrl"
        case feedUrl = "feedUrl"
        case language = "language"
        case categories = "categories"
        case explicit = "explicit"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.title = try container.decode(String.self, forKey: .title)
        self.author = try container.decodeIfPresent(String.self, forKey: .author)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.artworkUrl = try container.decodeIfPresent(String.self, forKey: .artworkUrl)
        self.homeUrl = try container.decodeIfPresent(String.self, forKey: .homeUrl)
        self.feedUrl = try container.decodeIfPresent(String.self, forKey: .feedUrl)
        self.language = try container.decodeIfPresent(String.self, forKey: .language)
        self.categories = try container.decodeIfPresent([String].self, forKey: .categories)
        self.explicit = try container.decodeIfPresent(Bool.self, forKey: .explicit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.title, forKey: .title)
        try container.encodeIfPresent(self.author, forKey: .author)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(self.homeUrl, forKey: .homeUrl)
        try container.encodeIfPresent(self.feedUrl, forKey: .feedUrl)
        try container.encodeIfPresent(self.language, forKey: .language)
        try container.encodeIfPresent(self.categories, forKey: .categories)
        try container.encodeIfPresent(self.explicit, forKey: .explicit)
    }
}

/// One episode of a programme the station carries, and what the station has done with it
public struct StationEpisode: Codable, Equatable, Sendable {
    /// The station's own id for this episode
    public var id: String
    /// Qualified, matching `StationShow.id`
    public var showId: String
    /// The plugin's own id for the episode, stable across refreshes
    public var episodeId: String
    public var showTitle: String
    public var title: String
    /// What the publisher says it is about, as plain text
    public var summary: String?
    /// The episode's page, for a person
    public var url: String?
    /// ISO-8601
    public var publishedAt: String?
    /// How long the publisher says it runs, in milliseconds
    public var durationMs: Int?
    public var artworkUrl: String?
    public var explicit: Bool?
    /// ISO-8601: when a refresh last saw it in its feed
    public var seenAt: String
    /// Whether the station holds its own copy of the audio, ready to air
    public var fetched: Bool
    /// ISO-8601: when the station last asked for the audio
    public var fetchRequestedAt: String?
    /// Why the last attempt to fetch the audio failed, when it did
    public var fetchError: String?
    /// ISO-8601: the slot the audio was fetched for
    public var scheduledFor: String?
    /// ISO-8601: when a listener could first have heard it. An episode airs once
    public var airedAt: String?

    public init(id: String, showId: String, episodeId: String, showTitle: String, title: String, summary: String? = nil, url: String? = nil, publishedAt: String? = nil, durationMs: Int? = nil, artworkUrl: String? = nil, explicit: Bool? = nil, seenAt: String, fetched: Bool, fetchRequestedAt: String? = nil, fetchError: String? = nil, scheduledFor: String? = nil, airedAt: String? = nil) {
        self.id = id
        self.showId = showId
        self.episodeId = episodeId
        self.showTitle = showTitle
        self.title = title
        self.summary = summary
        self.url = url
        self.publishedAt = publishedAt
        self.durationMs = durationMs
        self.artworkUrl = artworkUrl
        self.explicit = explicit
        self.seenAt = seenAt
        self.fetched = fetched
        self.fetchRequestedAt = fetchRequestedAt
        self.fetchError = fetchError
        self.scheduledFor = scheduledFor
        self.airedAt = airedAt
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case showId = "showId"
        case episodeId = "episodeId"
        case showTitle = "showTitle"
        case title = "title"
        case summary = "summary"
        case url = "url"
        case publishedAt = "publishedAt"
        case durationMs = "durationMs"
        case artworkUrl = "artworkUrl"
        case explicit = "explicit"
        case seenAt = "seenAt"
        case fetched = "fetched"
        case fetchRequestedAt = "fetchRequestedAt"
        case fetchError = "fetchError"
        case scheduledFor = "scheduledFor"
        case airedAt = "airedAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.showId = try container.decode(String.self, forKey: .showId)
        self.episodeId = try container.decode(String.self, forKey: .episodeId)
        self.showTitle = try container.decode(String.self, forKey: .showTitle)
        self.title = try container.decode(String.self, forKey: .title)
        self.summary = try container.decodeIfPresent(String.self, forKey: .summary)
        self.url = try container.decodeIfPresent(String.self, forKey: .url)
        self.publishedAt = try container.decodeIfPresent(String.self, forKey: .publishedAt)
        self.durationMs = try container.decodeIfPresent(Int.self, forKey: .durationMs)
        self.artworkUrl = try container.decodeIfPresent(String.self, forKey: .artworkUrl)
        self.explicit = try container.decodeIfPresent(Bool.self, forKey: .explicit)
        self.seenAt = try container.decode(String.self, forKey: .seenAt)
        self.fetched = try container.decode(Bool.self, forKey: .fetched)
        self.fetchRequestedAt = try container.decodeIfPresent(String.self, forKey: .fetchRequestedAt)
        self.fetchError = try container.decodeIfPresent(String.self, forKey: .fetchError)
        self.scheduledFor = try container.decodeIfPresent(String.self, forKey: .scheduledFor)
        self.airedAt = try container.decodeIfPresent(String.self, forKey: .airedAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.showId, forKey: .showId)
        try container.encode(self.episodeId, forKey: .episodeId)
        try container.encode(self.showTitle, forKey: .showTitle)
        try container.encode(self.title, forKey: .title)
        try container.encodeIfPresent(self.summary, forKey: .summary)
        try container.encodeIfPresent(self.url, forKey: .url)
        try container.encodeIfPresent(self.publishedAt, forKey: .publishedAt)
        try container.encodeIfPresent(self.durationMs, forKey: .durationMs)
        try container.encodeIfPresent(self.artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(self.explicit, forKey: .explicit)
        try container.encode(self.seenAt, forKey: .seenAt)
        try container.encode(self.fetched, forKey: .fetched)
        try container.encodeIfPresent(self.fetchRequestedAt, forKey: .fetchRequestedAt)
        try container.encodeIfPresent(self.fetchError, forKey: .fetchError)
        try container.encodeIfPresent(self.scheduledFor, forKey: .scheduledFor)
        try container.encodeIfPresent(self.airedAt, forKey: .airedAt)
    }
}

/// A show a podcast plugin's directory knows about, which the station may or may not carry
public struct StationDirectoryEntry: Codable, Equatable, Sendable {
    /// The directory's own id for the show. A key in a list, and nothing more
    public var id: String
    /// The plugin whose directory answered, which is the plugin a subscription would go to
    public var pluginId: String
    public var title: String
    /// Where the show's feed is, which is what subscribing needs
    public var feedUrl: String
    public var author: String?
    public var description: String?
    public var artworkUrl: String?
    public var homeUrl: String?
    public var categories: [String]?
    public var explicit: Bool?

    public init(id: String, pluginId: String, title: String, feedUrl: String, author: String? = nil, description: String? = nil, artworkUrl: String? = nil, homeUrl: String? = nil, categories: [String]? = nil, explicit: Bool? = nil) {
        self.id = id
        self.pluginId = pluginId
        self.title = title
        self.feedUrl = feedUrl
        self.author = author
        self.description = description
        self.artworkUrl = artworkUrl
        self.homeUrl = homeUrl
        self.categories = categories
        self.explicit = explicit
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case pluginId = "pluginId"
        case title = "title"
        case feedUrl = "feedUrl"
        case author = "author"
        case description = "description"
        case artworkUrl = "artworkUrl"
        case homeUrl = "homeUrl"
        case categories = "categories"
        case explicit = "explicit"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.pluginId = try container.decode(String.self, forKey: .pluginId)
        self.title = try container.decode(String.self, forKey: .title)
        self.feedUrl = try container.decode(String.self, forKey: .feedUrl)
        self.author = try container.decodeIfPresent(String.self, forKey: .author)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.artworkUrl = try container.decodeIfPresent(String.self, forKey: .artworkUrl)
        self.homeUrl = try container.decodeIfPresent(String.self, forKey: .homeUrl)
        self.categories = try container.decodeIfPresent([String].self, forKey: .categories)
        self.explicit = try container.decodeIfPresent(Bool.self, forKey: .explicit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.pluginId, forKey: .pluginId)
        try container.encode(self.title, forKey: .title)
        try container.encode(self.feedUrl, forKey: .feedUrl)
        try container.encodeIfPresent(self.author, forKey: .author)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(self.homeUrl, forKey: .homeUrl)
        try container.encodeIfPresent(self.categories, forKey: .categories)
        try container.encodeIfPresent(self.explicit, forKey: .explicit)
    }
}

public struct StationDirectoryQuery: Codable, Equatable, Sendable {
    /// Words to look a show up by: its name, its publisher, its subject
    public var query: String
    public var limit: Int?

    public init(query: String, limit: Int? = nil) {
        self.query = query
        self.limit = limit
    }

    private enum CodingKeys: String, CodingKey {
        case query = "query"
        case limit = "limit"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.query = try container.decode(String.self, forKey: .query)
        self.limit = try container.decodeIfPresent(Int.self, forKey: .limit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.query, forKey: .query)
        try container.encodeIfPresent(self.limit, forKey: .limit)
    }
}

public struct StationEpisodeQuery: Codable, Equatable, Sendable {
    /// One show's episodes, or absent for every show's, newest first
    public var showId: String?
    public var limit: Int?

    public init(showId: String? = nil, limit: Int? = nil) {
        self.showId = showId
        self.limit = limit
    }

    private enum CodingKeys: String, CodingKey {
        case showId = "showId"
        case limit = "limit"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.showId = try container.decodeIfPresent(String.self, forKey: .showId)
        self.limit = try container.decodeIfPresent(Int.self, forKey: .limit)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.showId, forKey: .showId)
        try container.encodeIfPresent(self.limit, forKey: .limit)
    }
}

public struct StationShowList: Codable, Equatable, Sendable {
    public var shows: [StationShow]

    public init(shows: [StationShow]) {
        self.shows = shows
    }

    private enum CodingKeys: String, CodingKey {
        case shows = "shows"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.shows = try container.decode([StationShow].self, forKey: .shows)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.shows, forKey: .shows)
    }
}

public struct StationEpisodePage: Codable, Equatable, Sendable {
    /// Newest first. Empty when the station knows of none, which is not an error
    public var episodes: [StationEpisode]

    public init(episodes: [StationEpisode]) {
        self.episodes = episodes
    }

    private enum CodingKeys: String, CodingKey {
        case episodes = "episodes"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.episodes = try container.decode([StationEpisode].self, forKey: .episodes)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.episodes, forKey: .episodes)
    }
}

public struct StationDirectoryPage: Codable, Equatable, Sendable {
    /// Empty when nothing matched or no directory could be asked, which is not an error
    public var results: [StationDirectoryEntry]

    public init(results: [StationDirectoryEntry]) {
        self.results = results
    }

    private enum CodingKeys: String, CodingKey {
        case results = "results"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.results = try container.decode([StationDirectoryEntry].self, forKey: .results)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.results, forKey: .results)
    }
}
