// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A record the station holds and could be asked for
public struct RequestableTrack: Codable, Equatable, Sendable {
    /// What to send as `trackId` to make the request
    public var trackId: UUID
    public var title: String
    /// The lead artist
    public var artist: String
    public var album: String?
    public var year: Int?

    public init(trackId: UUID, title: String, artist: String, album: String? = nil, year: Int? = nil) {
        self.trackId = trackId
        self.title = title
        self.artist = artist
        self.album = album
        self.year = year
    }

    private enum CodingKeys: String, CodingKey {
        case trackId = "trackId"
        case title = "title"
        case artist = "artist"
        case album = "album"
        case year = "year"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.trackId = try container.decode(UUID.self, forKey: .trackId)
        self.title = try container.decode(String.self, forKey: .title)
        self.artist = try container.decode(String.self, forKey: .artist)
        self.album = try container.decodeIfPresent(String.self, forKey: .album)
        self.year = try container.decodeIfPresent(Int.self, forKey: .year)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.trackId, forKey: .trackId)
        try container.encode(self.title, forKey: .title)
        try container.encode(self.artist, forKey: .artist)
        try container.encodeIfPresent(self.album, forKey: .album)
        try container.encodeIfPresent(self.year, forKey: .year)
    }
}

public enum RequestStatus: String, Codable, CaseIterable, Sendable {
    case waiting = "waiting"
    case pending = "pending"
    case queued = "queued"
    case aired = "aired"
    case declined = "declined"
    case expired = "expired"
}

public enum RequestSource: String, Codable, CaseIterable, Sendable {
    case app = "app"
    case chat = "chat"
}

/// Ask the station to play a record
public struct ListenerRequestCreate: Codable, Equatable, Sendable {
    /// A record from the request search
    public var trackId: UUID
    /// What the station should call you. Omitted, you are "a listener": your account's email address is never shown or read out
    public var name: String?
    /// Dedicate it to somebody. The station may say this name on air
    public var dedicateTo: String?
    /// A few words to go with it. The presenter may put them in their own words on air, and leaves out anything unfit to broadcast; the words themselves are never read out
    public var message: String?

    public init(trackId: UUID, name: String? = nil, dedicateTo: String? = nil, message: String? = nil) {
        self.trackId = trackId
        self.name = name
        self.dedicateTo = dedicateTo
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case trackId = "trackId"
        case name = "name"
        case dedicateTo = "dedicateTo"
        case message = "message"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.trackId = try container.decode(UUID.self, forKey: .trackId)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.dedicateTo = try container.decodeIfPresent(String.self, forKey: .dedicateTo)
        self.message = try container.decodeIfPresent(String.self, forKey: .message)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.trackId, forKey: .trackId)
        try container.encodeIfPresent(self.name, forKey: .name)
        try container.encodeIfPresent(self.dedicateTo, forKey: .dedicateTo)
        try container.encodeIfPresent(self.message, forKey: .message)
    }
}

/// Turn a request down
public struct ListenerRequestDecline: Codable, Equatable, Sendable {
    /// What to tell the listener. Omit for a plain no
    public var reason: String?

    public init(reason: String? = nil) {
        self.reason = reason
    }

    private enum CodingKeys: String, CodingKey {
        case reason = "reason"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.reason = try container.decodeIfPresent(String.self, forKey: .reason)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.reason, forKey: .reason)
    }
}

/// Records matching a search, best matches first
public struct RequestableTrackList: Codable, Equatable, Sendable {
    public var tracks: [RequestableTrack]

    public init(tracks: [RequestableTrack]) {
        self.tracks = tracks
    }

    private enum CodingKeys: String, CodingKey {
        case tracks = "tracks"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.tracks = try container.decode([RequestableTrack].self, forKey: .tracks)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.tracks, forKey: .tracks)
    }
}

/// A record somebody asked the station to play, and what became of it
public struct ListenerRequest: Codable, Equatable, Sendable {
    public var id: UUID
    /// `waiting` for an operator to approve it, `pending` while its audio is fetched or a place is found for it, `queued` in the running order, `aired` once heard, `declined` or `expired` when it never will be
    public var status: RequestStatus
    /// The record, as it was called when it was asked for
    public var title: String
    public var artist: String
    /// Who asked, by the name their account or chat platform gave
    public var requesterName: String
    /// Whether it came from an app or a chat platform
    public var source: RequestSource
    /// When it was asked for
    public var createdAt: Date
    /// Why it was declined or expired, in the station's words or an operator's
    public var reason: String?
    /// When it aired
    public var airedAt: Date?
    /// Who the listener dedicated it to
    public var dedicateTo: String?
    /// What the listener asked to have said with it, in their own words
    public var message: String?

    public init(id: UUID, status: RequestStatus, title: String, artist: String, requesterName: String, source: RequestSource, createdAt: Date, reason: String? = nil, airedAt: Date? = nil, dedicateTo: String? = nil, message: String? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.artist = artist
        self.requesterName = requesterName
        self.source = source
        self.createdAt = createdAt
        self.reason = reason
        self.airedAt = airedAt
        self.dedicateTo = dedicateTo
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case status = "status"
        case title = "title"
        case artist = "artist"
        case requesterName = "requesterName"
        case source = "source"
        case createdAt = "createdAt"
        case reason = "reason"
        case airedAt = "airedAt"
        case dedicateTo = "dedicateTo"
        case message = "message"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.status = try container.decode(RequestStatus.self, forKey: .status)
        self.title = try container.decode(String.self, forKey: .title)
        self.artist = try container.decode(String.self, forKey: .artist)
        self.requesterName = try container.decode(String.self, forKey: .requesterName)
        self.source = try container.decode(RequestSource.self, forKey: .source)
        self.createdAt = try container.decode(Date.self, forKey: .createdAt)
        self.reason = try container.decodeIfPresent(String.self, forKey: .reason)
        self.airedAt = try container.decodeIfPresent(Date.self, forKey: .airedAt)
        self.dedicateTo = try container.decodeIfPresent(String.self, forKey: .dedicateTo)
        self.message = try container.decodeIfPresent(String.self, forKey: .message)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.status, forKey: .status)
        try container.encode(self.title, forKey: .title)
        try container.encode(self.artist, forKey: .artist)
        try container.encode(self.requesterName, forKey: .requesterName)
        try container.encode(self.source, forKey: .source)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.reason, forKey: .reason)
        try container.encodeIfPresent(self.airedAt, forKey: .airedAt)
        try container.encodeIfPresent(self.dedicateTo, forKey: .dedicateTo)
        try container.encodeIfPresent(self.message, forKey: .message)
    }
}

/// Requests, newest first
public struct ListenerRequestList: Codable, Equatable, Sendable {
    public var requests: [ListenerRequest]

    public init(requests: [ListenerRequest]) {
        self.requests = requests
    }

    private enum CodingKeys: String, CodingKey {
        case requests = "requests"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.requests = try container.decode([ListenerRequest].self, forKey: .requests)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.requests, forKey: .requests)
    }
}
