// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A never-play rule: a KIND of record the station must not play. Absolute, like a dislike, and
/// exclude-only: there is no "only these" rule, because one could leave the station nothing to play.
/// Every scope is optional and an absent one means "always"
public struct BlockRule: Codable, Equatable, Sendable {
    public var id: UUID
    /// `genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag
    public var field: BlockRuleField
    /// The genre or tag, as you would write it
    public var value: String
    /// First day it holds, as `MM-DD`. With `seasonTo`; a season starting after it ends wraps the year end
    public var seasonFrom: String?
    /// Last day it holds, as `MM-DD`
    public var seasonTo: String?
    /// First hour of the station's day it holds. With `untilHour`; a window starting after it ends wraps midnight
    public var fromHour: Int?
    /// The hour it stops holding, exclusive
    public var untilHour: Int?
    /// Only while the station is in one of these modes. Absent or empty means every mode
    public var modes: [BlockRuleModes]?
    /// Only during these schedule blocks. Absent or empty means whatever is on
    public var slotIds: [String]?
    /// When it stops holding. Absent means until it is removed
    public var endsAt: Date?
    /// Whether it holds right now, on the station's clock, for what is on air
    public var inForce: Bool

    public init(id: UUID, field: BlockRuleField, value: String, seasonFrom: String? = nil, seasonTo: String? = nil, fromHour: Int? = nil, untilHour: Int? = nil, modes: [BlockRuleModes]? = nil, slotIds: [String]? = nil, endsAt: Date? = nil, inForce: Bool) {
        self.id = id
        self.field = field
        self.value = value
        self.seasonFrom = seasonFrom
        self.seasonTo = seasonTo
        self.fromHour = fromHour
        self.untilHour = untilHour
        self.modes = modes
        self.slotIds = slotIds
        self.endsAt = endsAt
        self.inForce = inForce
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case field = "field"
        case value = "value"
        case seasonFrom = "seasonFrom"
        case seasonTo = "seasonTo"
        case fromHour = "fromHour"
        case untilHour = "untilHour"
        case modes = "modes"
        case slotIds = "slotIds"
        case endsAt = "endsAt"
        case inForce = "inForce"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.field = try container.decode(BlockRuleField.self, forKey: .field)
        self.value = try container.decode(String.self, forKey: .value)
        self.seasonFrom = try container.decodeIfPresent(String.self, forKey: .seasonFrom)
        self.seasonTo = try container.decodeIfPresent(String.self, forKey: .seasonTo)
        self.fromHour = try container.decodeIfPresent(Int.self, forKey: .fromHour)
        self.untilHour = try container.decodeIfPresent(Int.self, forKey: .untilHour)
        self.modes = try container.decodeIfPresent([BlockRuleModes].self, forKey: .modes)
        self.slotIds = try container.decodeIfPresent([String].self, forKey: .slotIds)
        self.endsAt = try container.decodeIfPresent(Date.self, forKey: .endsAt)
        self.inForce = try container.decode(Bool.self, forKey: .inForce)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.field, forKey: .field)
        try container.encode(self.value, forKey: .value)
        try container.encodeIfPresent(self.seasonFrom, forKey: .seasonFrom)
        try container.encodeIfPresent(self.seasonTo, forKey: .seasonTo)
        try container.encodeIfPresent(self.fromHour, forKey: .fromHour)
        try container.encodeIfPresent(self.untilHour, forKey: .untilHour)
        try container.encodeIfPresent(self.modes, forKey: .modes)
        try container.encodeIfPresent(self.slotIds, forKey: .slotIds)
        try container.encodeIfPresent(self.endsAt, forKey: .endsAt)
        try container.encode(self.inForce, forKey: .inForce)
    }
}

/// A never-play rule: a KIND of record the station must not play. Absolute, like a dislike, and
/// exclude-only: there is no "only these" rule, because one could leave the station nothing to play.
/// Every scope is optional and an absent one means "always"
public struct BlockRuleInput: Codable, Equatable, Sendable {
    /// `genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag
    public var field: BlockRuleField
    /// The genre or tag, as you would write it
    public var value: String
    /// First day it holds, as `MM-DD`. With `seasonTo`; a season starting after it ends wraps the year end
    public var seasonFrom: String?
    /// Last day it holds, as `MM-DD`
    public var seasonTo: String?
    /// First hour of the station's day it holds. With `untilHour`; a window starting after it ends wraps midnight
    public var fromHour: Int?
    /// The hour it stops holding, exclusive
    public var untilHour: Int?
    /// Only while the station is in one of these modes. Absent or empty means every mode
    public var modes: [BlockRuleModes]?
    /// Only during these schedule blocks. Absent or empty means whatever is on
    public var slotIds: [String]?
    /// When it stops holding. Absent means until it is removed
    public var endsAt: Date?

    public init(field: BlockRuleField, value: String, seasonFrom: String? = nil, seasonTo: String? = nil, fromHour: Int? = nil, untilHour: Int? = nil, modes: [BlockRuleModes]? = nil, slotIds: [String]? = nil, endsAt: Date? = nil) {
        self.field = field
        self.value = value
        self.seasonFrom = seasonFrom
        self.seasonTo = seasonTo
        self.fromHour = fromHour
        self.untilHour = untilHour
        self.modes = modes
        self.slotIds = slotIds
        self.endsAt = endsAt
    }

    private enum CodingKeys: String, CodingKey {
        case field = "field"
        case value = "value"
        case seasonFrom = "seasonFrom"
        case seasonTo = "seasonTo"
        case fromHour = "fromHour"
        case untilHour = "untilHour"
        case modes = "modes"
        case slotIds = "slotIds"
        case endsAt = "endsAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.field = try container.decode(BlockRuleField.self, forKey: .field)
        self.value = try container.decode(String.self, forKey: .value)
        self.seasonFrom = try container.decodeIfPresent(String.self, forKey: .seasonFrom)
        self.seasonTo = try container.decodeIfPresent(String.self, forKey: .seasonTo)
        self.fromHour = try container.decodeIfPresent(Int.self, forKey: .fromHour)
        self.untilHour = try container.decodeIfPresent(Int.self, forKey: .untilHour)
        self.modes = try container.decodeIfPresent([BlockRuleModes].self, forKey: .modes)
        self.slotIds = try container.decodeIfPresent([String].self, forKey: .slotIds)
        self.endsAt = try container.decodeIfPresent(Date.self, forKey: .endsAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.field, forKey: .field)
        try container.encode(self.value, forKey: .value)
        try container.encodeIfPresent(self.seasonFrom, forKey: .seasonFrom)
        try container.encodeIfPresent(self.seasonTo, forKey: .seasonTo)
        try container.encodeIfPresent(self.fromHour, forKey: .fromHour)
        try container.encodeIfPresent(self.untilHour, forKey: .untilHour)
        try container.encodeIfPresent(self.modes, forKey: .modes)
        try container.encodeIfPresent(self.slotIds, forKey: .slotIds)
        try container.encodeIfPresent(self.endsAt, forKey: .endsAt)
    }
}

/// A lean toward some genres for a while. The opposite of a rule: the station favours them when it
/// chooses records, and still plays anything else rather than run dry
public struct GenreSteer: Codable, Equatable, Sendable {
    /// What to favour, as genres. A record tagged with any of them, or a kind of one, is preferred
    public var genres: [String]
    /// When the station goes back to choosing as it ordinarily does
    public var endsAt: Date

    public init(genres: [String], endsAt: Date) {
        self.genres = genres
        self.endsAt = endsAt
    }

    private enum CodingKeys: String, CodingKey {
        case genres = "genres"
        case endsAt = "endsAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.genres = try container.decode([String].self, forKey: .genres)
        self.endsAt = try container.decode(Date.self, forKey: .endsAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.genres, forKey: .genres)
        try container.encode(self.endsAt, forKey: .endsAt)
    }
}

/// Lean the station toward some genres for a number of hours
public struct GenreSteerInput: Codable, Equatable, Sendable {
    public var genres: [String]
    /// How long it lasts, from now
    public var hours: Int

    public init(genres: [String], hours: Int) {
        self.genres = genres
        self.hours = hours
    }

    private enum CodingKeys: String, CodingKey {
        case genres = "genres"
        case hours = "hours"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.genres = try container.decode([String].self, forKey: .genres)
        self.hours = try container.decode(Int.self, forKey: .hours)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.genres, forKey: .genres)
        try container.encode(self.hours, forKey: .hours)
    }
}

/// Every rule on the station, newest first
public struct BlockRuleList: Codable, Equatable, Sendable {
    public var rules: [BlockRule]

    public init(rules: [BlockRule]) {
        self.rules = rules
    }

    private enum CodingKeys: String, CodingKey {
        case rules = "rules"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.rules = try container.decode([BlockRule].self, forKey: .rules)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.rules, forKey: .rules)
    }
}

/// Every rule on the station, newest first
public struct BlockRuleListInput: Codable, Equatable, Sendable {
    public var rules: [BlockRuleInput]

    public init(rules: [BlockRuleInput]) {
        self.rules = rules
    }

    private enum CodingKeys: String, CodingKey {
        case rules = "rules"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.rules = try container.decode([BlockRuleInput].self, forKey: .rules)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.rules, forKey: .rules)
    }
}

/// The lean in force, or none
public struct GenreSteerReading: Codable, Equatable, Sendable {
    /// Absent when nothing is leaning the station, including once one has run out
    public var steer: GenreSteer?

    public init(steer: GenreSteer? = nil) {
        self.steer = steer
    }

    private enum CodingKeys: String, CodingKey {
        case steer = "steer"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.steer = try container.decodeIfPresent(GenreSteer.self, forKey: .steer)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.steer, forKey: .steer)
    }
}

/// `genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag
public enum BlockRuleField: String, Codable, CaseIterable, Sendable {
    case genre = "genre"
    case tag = "tag"
}

public enum BlockRuleModes: String, Codable, CaseIterable, Sendable {
    case rotation = "rotation"
    case setlist = "setlist"
    case feature = "feature"
}
