// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// One stretch of the station's day: from this time, on these days, the station plays this
public struct ScheduleSlot: Codable, Equatable, Sendable {
    public var id: String
    /// What the operator calls this stretch of the day. Becomes the broadcast's name
    public var label: String
    /// When it starts, as minutes past midnight on the station's clock
    public var startsAtMinutes: Int
    /// When it stops, in the same terms. Before the start means the block runs past midnight, which is ordinary for a late show; equal to it means a full twenty-four hours
    public var endsAtMinutes: Int
    /// The weekdays it runs on, Sunday 0. Absent or empty means every day
    public var days: [Int]?
    /// The plugin the records come from. Absent, with no playlist, is a slot the station fills itself
    public var sourcePluginId: String?
    public var sourcePlaylistId: String?
    /// A published chart to play instead, as `pluginId:chartId`. An ALTERNATIVE to the playlist pair rather than a companion, and it wins if both are sent: a playlist names copies the station can already fetch and a chart names records it has to look up
    public var sourceChartId: String?
    /// Which way round that chart is played. Absent is `countdown`, which ends on number one. Ignored without `sourceChartId`
    public var sourceChartOrder: ScheduleSlotSourceChartOrder?
    /// Who hosts this stretch of the day. Absent means the station's own active persona
    public var personaId: String?
    /// What this stretch of the day is asked to play, in the operator's own words. The same ceiling `PutOnAirInput.brief` has, because a changeover builds one of those from this and the two boxes are one field set on the console
    public var brief: String?
    /// The earliest release year this stretch of the day plays. Absent means no lower bound, and a record whose year the catalog does not know is played whatever the period
    public var eraFrom: Int?
    /// The latest release year, on the same terms. Set with `eraFrom` for a decade; either may stand alone
    public var eraTo: Int?
    /// Whether somebody phones in during this stretch of the day. Absent leaves the station's own setting standing, exactly as it does when an operator briefs a broadcast by hand; a `setlist` or a `feature` takes no calls whatever this says
    public var callins: Bool?
    public var mode: ScheduleSlotMode
    public var onEnd: ScheduleSlotOnEnd

    public init(id: String, label: String, startsAtMinutes: Int, endsAtMinutes: Int, days: [Int]? = nil, sourcePluginId: String? = nil, sourcePlaylistId: String? = nil, sourceChartId: String? = nil, sourceChartOrder: ScheduleSlotSourceChartOrder? = nil, personaId: String? = nil, brief: String? = nil, eraFrom: Int? = nil, eraTo: Int? = nil, callins: Bool? = nil, mode: ScheduleSlotMode, onEnd: ScheduleSlotOnEnd) {
        self.id = id
        self.label = label
        self.startsAtMinutes = startsAtMinutes
        self.endsAtMinutes = endsAtMinutes
        self.days = days
        self.sourcePluginId = sourcePluginId
        self.sourcePlaylistId = sourcePlaylistId
        self.sourceChartId = sourceChartId
        self.sourceChartOrder = sourceChartOrder
        self.personaId = personaId
        self.brief = brief
        self.eraFrom = eraFrom
        self.eraTo = eraTo
        self.callins = callins
        self.mode = mode
        self.onEnd = onEnd
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case label = "label"
        case startsAtMinutes = "startsAtMinutes"
        case endsAtMinutes = "endsAtMinutes"
        case days = "days"
        case sourcePluginId = "sourcePluginId"
        case sourcePlaylistId = "sourcePlaylistId"
        case sourceChartId = "sourceChartId"
        case sourceChartOrder = "sourceChartOrder"
        case personaId = "personaId"
        case brief = "brief"
        case eraFrom = "eraFrom"
        case eraTo = "eraTo"
        case callins = "callins"
        case mode = "mode"
        case onEnd = "onEnd"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.label = try container.decode(String.self, forKey: .label)
        self.startsAtMinutes = try container.decode(Int.self, forKey: .startsAtMinutes)
        self.endsAtMinutes = try container.decode(Int.self, forKey: .endsAtMinutes)
        self.days = try container.decodeIfPresent([Int].self, forKey: .days)
        self.sourcePluginId = try container.decodeIfPresent(String.self, forKey: .sourcePluginId)
        self.sourcePlaylistId = try container.decodeIfPresent(String.self, forKey: .sourcePlaylistId)
        self.sourceChartId = try container.decodeIfPresent(String.self, forKey: .sourceChartId)
        self.sourceChartOrder = try container.decodeIfPresent(ScheduleSlotSourceChartOrder.self, forKey: .sourceChartOrder)
        self.personaId = try container.decodeIfPresent(String.self, forKey: .personaId)
        self.brief = try container.decodeIfPresent(String.self, forKey: .brief)
        self.eraFrom = try container.decodeIfPresent(Int.self, forKey: .eraFrom)
        self.eraTo = try container.decodeIfPresent(Int.self, forKey: .eraTo)
        self.callins = try container.decodeIfPresent(Bool.self, forKey: .callins)
        self.mode = try container.decode(ScheduleSlotMode.self, forKey: .mode)
        self.onEnd = try container.decode(ScheduleSlotOnEnd.self, forKey: .onEnd)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.label, forKey: .label)
        try container.encode(self.startsAtMinutes, forKey: .startsAtMinutes)
        try container.encode(self.endsAtMinutes, forKey: .endsAtMinutes)
        try container.encodeIfPresent(self.days, forKey: .days)
        try container.encodeIfPresent(self.sourcePluginId, forKey: .sourcePluginId)
        try container.encodeIfPresent(self.sourcePlaylistId, forKey: .sourcePlaylistId)
        try container.encodeIfPresent(self.sourceChartId, forKey: .sourceChartId)
        try container.encodeIfPresent(self.sourceChartOrder, forKey: .sourceChartOrder)
        try container.encodeIfPresent(self.personaId, forKey: .personaId)
        try container.encodeIfPresent(self.brief, forKey: .brief)
        try container.encodeIfPresent(self.eraFrom, forKey: .eraFrom)
        try container.encodeIfPresent(self.eraTo, forKey: .eraTo)
        try container.encodeIfPresent(self.callins, forKey: .callins)
        try container.encode(self.mode, forKey: .mode)
        try container.encode(self.onEnd, forKey: .onEnd)
    }
}

/// One stretch of the station's day: from this time, on these days, the station plays this
public struct ScheduleSlotInput: Codable, Equatable, Sendable {
    /// What the operator calls this stretch of the day. Becomes the broadcast's name
    public var label: String
    /// When it starts, as minutes past midnight on the station's clock
    public var startsAtMinutes: Int
    /// When it stops, in the same terms. Before the start means the block runs past midnight, which is ordinary for a late show; equal to it means a full twenty-four hours
    public var endsAtMinutes: Int
    /// The weekdays it runs on, Sunday 0. Absent or empty means every day
    public var days: [Int]?
    /// The plugin the records come from. Absent, with no playlist, is a slot the station fills itself
    public var sourcePluginId: String?
    public var sourcePlaylistId: String?
    /// A published chart to play instead, as `pluginId:chartId`. An ALTERNATIVE to the playlist pair rather than a companion, and it wins if both are sent: a playlist names copies the station can already fetch and a chart names records it has to look up
    public var sourceChartId: String?
    /// Which way round that chart is played. Absent is `countdown`, which ends on number one. Ignored without `sourceChartId`
    public var sourceChartOrder: ScheduleSlotSourceChartOrder?
    /// Who hosts this stretch of the day. Absent means the station's own active persona
    public var personaId: String?
    /// What this stretch of the day is asked to play, in the operator's own words. The same ceiling `PutOnAirInput.brief` has, because a changeover builds one of those from this and the two boxes are one field set on the console
    public var brief: String?
    /// The earliest release year this stretch of the day plays. Absent means no lower bound, and a record whose year the catalog does not know is played whatever the period
    public var eraFrom: Int?
    /// The latest release year, on the same terms. Set with `eraFrom` for a decade; either may stand alone
    public var eraTo: Int?
    /// Whether somebody phones in during this stretch of the day. Absent leaves the station's own setting standing, exactly as it does when an operator briefs a broadcast by hand; a `setlist` or a `feature` takes no calls whatever this says
    public var callins: Bool?
    public var mode: ScheduleSlotMode
    public var onEnd: ScheduleSlotOnEnd

    public init(label: String, startsAtMinutes: Int, endsAtMinutes: Int, days: [Int]? = nil, sourcePluginId: String? = nil, sourcePlaylistId: String? = nil, sourceChartId: String? = nil, sourceChartOrder: ScheduleSlotSourceChartOrder? = nil, personaId: String? = nil, brief: String? = nil, eraFrom: Int? = nil, eraTo: Int? = nil, callins: Bool? = nil, mode: ScheduleSlotMode, onEnd: ScheduleSlotOnEnd) {
        self.label = label
        self.startsAtMinutes = startsAtMinutes
        self.endsAtMinutes = endsAtMinutes
        self.days = days
        self.sourcePluginId = sourcePluginId
        self.sourcePlaylistId = sourcePlaylistId
        self.sourceChartId = sourceChartId
        self.sourceChartOrder = sourceChartOrder
        self.personaId = personaId
        self.brief = brief
        self.eraFrom = eraFrom
        self.eraTo = eraTo
        self.callins = callins
        self.mode = mode
        self.onEnd = onEnd
    }

    private enum CodingKeys: String, CodingKey {
        case label = "label"
        case startsAtMinutes = "startsAtMinutes"
        case endsAtMinutes = "endsAtMinutes"
        case days = "days"
        case sourcePluginId = "sourcePluginId"
        case sourcePlaylistId = "sourcePlaylistId"
        case sourceChartId = "sourceChartId"
        case sourceChartOrder = "sourceChartOrder"
        case personaId = "personaId"
        case brief = "brief"
        case eraFrom = "eraFrom"
        case eraTo = "eraTo"
        case callins = "callins"
        case mode = "mode"
        case onEnd = "onEnd"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.label = try container.decode(String.self, forKey: .label)
        self.startsAtMinutes = try container.decode(Int.self, forKey: .startsAtMinutes)
        self.endsAtMinutes = try container.decode(Int.self, forKey: .endsAtMinutes)
        self.days = try container.decodeIfPresent([Int].self, forKey: .days)
        self.sourcePluginId = try container.decodeIfPresent(String.self, forKey: .sourcePluginId)
        self.sourcePlaylistId = try container.decodeIfPresent(String.self, forKey: .sourcePlaylistId)
        self.sourceChartId = try container.decodeIfPresent(String.self, forKey: .sourceChartId)
        self.sourceChartOrder = try container.decodeIfPresent(ScheduleSlotSourceChartOrder.self, forKey: .sourceChartOrder)
        self.personaId = try container.decodeIfPresent(String.self, forKey: .personaId)
        self.brief = try container.decodeIfPresent(String.self, forKey: .brief)
        self.eraFrom = try container.decodeIfPresent(Int.self, forKey: .eraFrom)
        self.eraTo = try container.decodeIfPresent(Int.self, forKey: .eraTo)
        self.callins = try container.decodeIfPresent(Bool.self, forKey: .callins)
        self.mode = try container.decode(ScheduleSlotMode.self, forKey: .mode)
        self.onEnd = try container.decode(ScheduleSlotOnEnd.self, forKey: .onEnd)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.label, forKey: .label)
        try container.encode(self.startsAtMinutes, forKey: .startsAtMinutes)
        try container.encode(self.endsAtMinutes, forKey: .endsAtMinutes)
        try container.encodeIfPresent(self.days, forKey: .days)
        try container.encodeIfPresent(self.sourcePluginId, forKey: .sourcePluginId)
        try container.encodeIfPresent(self.sourcePlaylistId, forKey: .sourcePlaylistId)
        try container.encodeIfPresent(self.sourceChartId, forKey: .sourceChartId)
        try container.encodeIfPresent(self.sourceChartOrder, forKey: .sourceChartOrder)
        try container.encodeIfPresent(self.personaId, forKey: .personaId)
        try container.encodeIfPresent(self.brief, forKey: .brief)
        try container.encodeIfPresent(self.eraFrom, forKey: .eraFrom)
        try container.encodeIfPresent(self.eraTo, forKey: .eraTo)
        try container.encodeIfPresent(self.callins, forKey: .callins)
        try container.encode(self.mode, forKey: .mode)
        try container.encode(self.onEnd, forKey: .onEnd)
    }
}

/// A window of the station's day to draw
public struct ScheduleTimetableQuery: Codable, Equatable, Sendable {
    /// The first day to draw, as `YYYY-MM-DD` on the station's own calendar. Absent means the station's today, which is the only way a caller that does not know the station's timezone can anchor
    public var from: String?
    /// How many days from `from`. Defaults to a week
    public var days: Int?

    public init(from: String? = nil, days: Int? = nil) {
        self.from = from
        self.days = days
    }

    private enum CodingKeys: String, CodingKey {
        case from = "from"
        case days = "days"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.from = try container.decodeIfPresent(String.self, forKey: .from)
        self.days = try container.decodeIfPresent(Int.self, forKey: .days)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.from, forKey: .from)
        try container.encodeIfPresent(self.days, forKey: .days)
    }
}

/// One block: this slot, on this day, between these two times
public struct ScheduleOccurrence: Codable, Equatable, Sendable {
    public var slotId: String
    public var label: String
    /// `YYYY-MM-DD HH:mm:ss` on the station's own clock, deliberately carrying no timezone offset: it is a reading rather than a moment, so it draws as written wherever the console is running
    public var start: String
    /// The same, exclusive. Every block stays inside one day, so a slot running past midnight arrives as two
    public var end: String

    public init(slotId: String, label: String, start: String, end: String) {
        self.slotId = slotId
        self.label = label
        self.start = start
        self.end = end
    }

    private enum CodingKeys: String, CodingKey {
        case slotId = "slotId"
        case label = "label"
        case start = "start"
        case end = "end"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.slotId = try container.decode(String.self, forKey: .slotId)
        self.label = try container.decode(String.self, forKey: .label)
        self.start = try container.decode(String.self, forKey: .start)
        self.end = try container.decode(String.self, forKey: .end)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.slotId, forKey: .slotId)
        try container.encode(self.label, forKey: .label)
        try container.encode(self.start, forKey: .start)
        try container.encode(self.end, forKey: .end)
    }
}

public struct ScheduleSlotList: Codable, Equatable, Sendable {
    public var slots: [ScheduleSlot]

    public init(slots: [ScheduleSlot]) {
        self.slots = slots
    }

    private enum CodingKeys: String, CodingKey {
        case slots = "slots"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.slots = try container.decode([ScheduleSlot].self, forKey: .slots)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.slots, forKey: .slots)
    }
}

public struct ScheduleSlotListInput: Codable, Equatable, Sendable {
    public var slots: [ScheduleSlotInput]

    public init(slots: [ScheduleSlotInput]) {
        self.slots = slots
    }

    private enum CodingKeys: String, CodingKey {
        case slots = "slots"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.slots = try container.decode([ScheduleSlotInput].self, forKey: .slots)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.slots, forKey: .slots)
    }
}

/// The station's day as blocks, ready to draw
public struct ScheduleTimetable: Codable, Equatable, Sendable {
    /// The range actually drawn, echoed so a caller steps forward and back by adding days to a string rather than by knowing the station's timezone
    public var from: String
    public var days: Int
    public var occurrences: [ScheduleOccurrence]

    public init(from: String, days: Int, occurrences: [ScheduleOccurrence]) {
        self.from = from
        self.days = days
        self.occurrences = occurrences
    }

    private enum CodingKeys: String, CodingKey {
        case from = "from"
        case days = "days"
        case occurrences = "occurrences"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.from = try container.decode(String.self, forKey: .from)
        self.days = try container.decode(Int.self, forKey: .days)
        self.occurrences = try container.decode([ScheduleOccurrence].self, forKey: .occurrences)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.from, forKey: .from)
        try container.encode(self.days, forKey: .days)
        try container.encode(self.occurrences, forKey: .occurrences)
    }
}

/// Which slot the clock says should be on right now, and what follows it
public struct ScheduleNow: Codable, Equatable, Sendable {
    /// What time it is on the station's own clock, in the same zone-naive `YYYY-MM-DD HH:mm:ss` shape as a block's ends. It is here so a caller can say how much of the block is left without knowing the station's timezone: subtracting two readings taken in one frame is arithmetic, deriving one is not
    public var now: String
    /// The slot in force at this instant. Absent means the station has no schedule
    public var slotId: String?
    /// The slot the running order actually belongs to. Different from the one above while an operator's own choice holds, which it does until the next slot begins
    public var airingSlotId: String?
    /// The block on now, if there is one, and the few that follow it, earliest first. Empty for a station with nothing scheduled from here on. A gap is simply absent, exactly as it is on the timetable: what plays there is the sustaining source rather than a block
    public var upcoming: [ScheduleOccurrence]

    public init(now: String, slotId: String? = nil, airingSlotId: String? = nil, upcoming: [ScheduleOccurrence]) {
        self.now = now
        self.slotId = slotId
        self.airingSlotId = airingSlotId
        self.upcoming = upcoming
    }

    private enum CodingKeys: String, CodingKey {
        case now = "now"
        case slotId = "slotId"
        case airingSlotId = "airingSlotId"
        case upcoming = "upcoming"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.now = try container.decode(String.self, forKey: .now)
        self.slotId = try container.decodeIfPresent(String.self, forKey: .slotId)
        self.airingSlotId = try container.decodeIfPresent(String.self, forKey: .airingSlotId)
        self.upcoming = try container.decode([ScheduleOccurrence].self, forKey: .upcoming)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.now, forKey: .now)
        try container.encodeIfPresent(self.slotId, forKey: .slotId)
        try container.encodeIfPresent(self.airingSlotId, forKey: .airingSlotId)
        try container.encode(self.upcoming, forKey: .upcoming)
    }
}

/// Which way round that chart is played. Absent is `countdown`, which ends on number one. Ignored without `sourceChartId`
public enum ScheduleSlotSourceChartOrder: String, Codable, CaseIterable, Sendable {
    case countdown = "countdown"
    case ranked = "ranked"
    case unordered = "unordered"
}

public enum ScheduleSlotMode: String, Codable, CaseIterable, Sendable {
    case rotation = "rotation"
    case setlist = "setlist"
    case feature = "feature"
}

public enum ScheduleSlotOnEnd: String, Codable, CaseIterable, Sendable {
    case extend = "extend"
    case `repeat` = "repeat"
    case stop = "stop"
}
