import { Container, Registry } from 'injectkit';
import { AppConfig } from '@maroonedsoftware/appconfig';
import { ServerKitModule } from '@maroonedsoftware/koa';
import {
    explainToolErrors,
    McpConfig,
    McpDispatcher,
    McpResourceHandlerMap,
    McpServerFactory,
    McpSessionRegistry,
    McpToolHandlerMap,
} from '@maroonedsoftware/mcp';
import { buildVersion } from '#modules/shared/build.revision.js';
import { McpToolCatalog, registerMcpCatalog, registerMcpToolClasses, registerMcpTools } from '#src/mcp/mcp.tools.js';
import { SEARCH_API_TOOL, SearchApiTool } from '#src/mcp/search.api.tool.js';
import { WHOAMI_TOOL, WhoAmITool } from '#src/mcp/whoami.tool.js';

/** What an MCP client sees as `serverInfo.name` during `initialize`. */
export const MCP_SERVER_NAME = 'deadair';

/**
 * The tools `tools/list` reports: every operation a contract flags `mcp`, `whoami`, and `search_api`,
 * which reaches the rest.
 *
 * Every one is wrapped by `explainToolErrors`, so a refusal or a bad argument reaches the model as a
 * tool result it can act on ("not allowed", "these fields are missing") rather than as a JSON-RPC
 * error that ends the call.
 */
export function buildMcpTools(container: Container): McpToolHandlerMap {
    const tools = registerMcpTools(container);
    tools.set(WHOAMI_TOOL, container.get(WhoAmITool));
    tools.set(SEARCH_API_TOOL, container.get(SearchApiTool));
    return explainToolErrors(tools);
}

/**
 * Every operation a tool can serve, listed or not, for `search_api` to find: a handler per operation,
 * generated with `catalog: true` and never reported by `tools/list`. Explained like the listed tools,
 * so an operation reached through the catalog fails the same way one reached directly does.
 */
export function buildMcpCatalog(container: Container): McpToolCatalog {
    const catalog = new McpToolCatalog();
    for (const [name, handler] of explainToolErrors(registerMcpCatalog(container))) catalog.set(name, handler);
    return catalog;
}

/**
 * The station's MCP endpoint, `POST /api/mcp`.
 *
 * The route and the tools live in `src/mcp`. The tools are generated by ContractKit from operations
 * a contract flags `mcp`, plus the hand-written ones there. This module is only their wiring.
 *
 * **Every tool acts as the caller.** The tools are singletons built here at boot, when the scoped
 * `AuthorizationContext` holds the startup actor. So each one resolves its service and
 * `PolicyService` from the request's container on every call (`resolve: "perCall"`), and the route
 * hands that container over. A caller here is an OAuth grant's session, authenticated by the
 * station's own JWT chain like any other; the shared-token authentication the MCP package offers is
 * NOT registered.
 *
 * **Stateless**: each POST is one JSON-RPC exchange, so there is no session map to keep.
 *
 * Last in `modules.ts`: nothing resolves it, and its tools reach services in every module above it.
 * `start` resolves the dispatcher, and with it every tool, so a tool that cannot be built stops the
 * boot rather than failing the first call.
 */
export const McpModule: ServerKitModule = {
    name: 'Mcp',
    setup: async (registry: Registry, config: AppConfig) => {
        registry
            .register(McpConfig)
            .useFactory((): McpConfig => ({ serverName: MCP_SERVER_NAME, version: buildVersion(config) ?? 'dev', sessionMode: 'stateless' }))
            .asSingleton();
        registerMcpToolClasses(registry);
        registry.register(WhoAmITool).useClass(WhoAmITool).asSingleton();
        registry.register(McpToolCatalog).useFactory(buildMcpCatalog).asSingleton();
        registry.register(SearchApiTool).useClass(SearchApiTool).asSingleton();
        registry.register(McpToolHandlerMap).useFactory(buildMcpTools).asSingleton();
        // Empty, and registered anyway: the server factory takes both maps, and advertises only what
        // a non-empty one backs.
        registry.register(McpResourceHandlerMap).useInstance(new McpResourceHandlerMap());
        registry.register(McpServerFactory).useClass(McpServerFactory).asSingleton();
        // Stateless never reaches it, but the dispatcher takes it unconditionally.
        registry.register(McpSessionRegistry).useClass(McpSessionRegistry).asSingleton();
        registry.register(McpDispatcher).useClass(McpDispatcher).asSingleton();
    },
    start: async (container: Container) => {
        container.get(McpDispatcher);
    },
};
