import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One sidebar per audience, because the three of them share no pages.
 *
 * Somebody running a station, somebody writing a plugin and somebody calling the API were all
 * reading one autogenerated list before this file existed, which is how the API reference came to be
 * 27 groups deep and linked from nowhere in the navbar.
 *
 * The operator and developer sections are listed by hand rather than autogenerated. They are
 * hand-written pages, their order is an argument rather than an accident, and a list here fails the
 * build when a page is renamed instead of quietly moving it. The API reference is the opposite: it
 * is regenerated from the contracts by `pnpm build:contracts`, so it is autogenerated from the
 * directory and takes its order from the `_category_.json` files the generator writes.
 */
const sidebars: SidebarsConfig = {
    run: [
        'quick-start',
        'install',
        'unraid',
        {
            type: 'category',
            label: 'What it does',
            link: { type: 'doc', id: 'features/index' },
            collapsed: false,
            items: [
                'features/running-order',
                'features/programme',
                'features/breaks',
                'features/claims',
                'features/characters',
                'features/phone-ins',
                'features/podcasts',
                'features/narrations',
                'features/library',
                'features/check-up',
                'features/plugins',
                'features/models-and-voices',
                'features/console',
                'features/listening',
            ],
        },
        'licensing',
        'help',
    ],

    build: [
        {
            type: 'category',
            label: 'Develop',
            link: { type: 'doc', id: 'develop/index' },
            collapsed: false,
            items: ['develop/setup', 'develop/architecture', 'develop/contributing', 'develop/api'],
        },
        {
            type: 'category',
            label: 'Writing plugins',
            link: { type: 'doc', id: 'plugin-development/index' },
            collapsed: false,
            items: [
                'plugin-development/getting-started',
                'plugin-development/packaging',
                'plugin-development/testing',
                'plugin-development/versioning',
                'plugin-development/example',
                'plugin-development/contract',
                'plugin-development/listing',
            ],
        },
    ],

    api: [{ type: 'autogenerated', dirName: 'api-reference' }],
};

export default sidebars;
