// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.models

import kotlin.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** Which part of the station an entry came from, and the console's one filter axis */
@Serializable
enum class ActivityModule {
    @SerialName("playout")
    PLAYOUT,
    @SerialName("director")
    DIRECTOR,
    @SerialName("render")
    RENDER,
    @SerialName("catalog")
    CATALOG,
    @SerialName("plugins")
    PLUGINS,
}

/**
 * How an entry reads, not how bad it is. There is deliberately no `waiting`: a station idling for
 * want of a listener says so in its own words and stays `info`, for the same reason the transport
 * reports it as `ready` rather than as a mild fault
 */
@Serializable
enum class ActivitySeverity {
    @SerialName("info")
    INFO,
    @SerialName("warn")
    WARN,
    @SerialName("fault")
    FAULT,
}

/** One thing that happened, from whichever of the feed's sources holds it */
@Serializable
data class ActivityEntry(
    /** Unique across the whole feed, and half of the cursor below */
    val id: String,
    /** When it happened, as the database recorded it */
    val at: Instant,
    val module: ActivityModule,
    /** Dotted and stable: `silence.cause`, `air.on`, `segment.ready`, `track.aired`. What a console draws a line with, never something a decision is made on */
    val kind: String,
    val severity: ActivitySeverity,
    /** The sentence a person reads, phrased by whatever produced it */
    val detail: String,
    /** The structured half, for a reader that wants to filter or chart rather than read */
    val data: Map<String, JsonElement>? = null,
    /** The segment this is about, for an entry that came from one */
    val segmentId: String? = null,
    /** The catalog track this is about, for an entry that came from one */
    val trackId: String? = null,
)

/** One page of the feed, newest first */
@Serializable
data class ActivityQuery(
    val limit: Long? = null,
    /** Where the previous page ended. Opaque, and a keyset rather than an offset because rows arrive at the head continuously: an offset would re-show a row on every page as the feed grew under it. Pass back whatever `nextBefore` said and nothing else */
    val before: String? = null,
    val module: ActivityModule? = null,
    /** The floor, not the exact match: `warn` answers with warnings and faults. Absent is everything */
    val minSeverity: ActivitySeverity? = null,
)

@Serializable
data class ActivityPage(
    val entries: List<ActivityEntry>,
    /** The cursor for the page after this one, absent once the feed has been read to its end */
    val nextBefore: String? = null,
)
