// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.models

import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * What the station has been told about a record. `neutral` is the absence of an opinion rather than
 * a middling one, and it is what rating something back to nothing means.
 */
@Serializable
enum class Rating {
    @SerialName("liked")
    LIKED,
    @SerialName("neutral")
    NEUTRAL,
    @SerialName("disliked")
    DISLIKED,
}

/**
 * One provider's copy of a record, with whatever the station holds of it.
 *
 * PER BINDING and never per track, which is the rule the whole page is built on: one canonical
 * record may bind to several copies inside one provider, those copies are different files with
 * different loudness and different cue points, and the one that airs is the one that was resolved.
 * Collapsing them would make "clear the audio" ambiguous about which file it took.
 *
 * The failure columns are here rather than hidden because that is the question this page exists to
 * answer. A row with `attempts` and no `fetchedAt` is a remembered failure, and `lastError` with
 * `nextAttemptAt` is the whole of why a perfectly good-looking record will not play.
 */
@Serializable
data class TrackBinding(
    /** `track_sources.id`, which is also what the audio URL carries */
    val sourceId: Uuid,
    val pluginId: String,
    val externalId: String,
    /** False when the provider still knows the record but will not serve it here */
    val playable: Boolean,
    /** When the station gave up on this copy. Cleared by the next sync that sees it again */
    val missingAt: Instant? = null,
    /** `sync` if a playlist walk saw it, `discovered` if something looked it up */
    val origin: String,
    val bitrate: Long? = null,
    val format: String? = null,
    val lastSeenAt: Instant? = null,
    /** What the station holds of this copy, absent when nothing has ever fetched it. */
    val byteSize: Long? = null,
    val fetchedAt: Instant? = null,
    val lastServedAt: Instant? = null,
    /** CONSECUTIVE failures. Reset by a fetch that works */
    val attempts: Long,
    val lastError: String? = null,
    val nextAttemptAt: Instant? = null,
)

/**
 * One provider's copy of a record, with whatever the station holds of it.
 *
 * PER BINDING and never per track, which is the rule the whole page is built on: one canonical
 * record may bind to several copies inside one provider, those copies are different files with
 * different loudness and different cue points, and the one that airs is the one that was resolved.
 * Collapsing them would make "clear the audio" ambiguous about which file it took.
 *
 * The failure columns are here rather than hidden because that is the question this page exists to
 * answer. A row with `attempts` and no `fetchedAt` is a remembered failure, and `lastError` with
 * `nextAttemptAt` is the whole of why a perfectly good-looking record will not play.
 */
@Serializable
class TrackBindingInput

/**
 * What the measurement sidecar made of a record.
 *
 * `complete` is NOT `analyzedAt`, and the two are separate fields for a reason `0005_music.sql`
 * argues at length: a measurement of a truncated download is confident and wrong, so every reader in
 * the app filters on `complete` and a page that showed only a date would be reporting a record as
 * measured that nothing will use the measurement of.
 */
@Serializable
data class TrackAnalysis(
    val schemaVersion: Long,
    val complete: Boolean,
    /** The measuring thing itself, which is not the plugin adapting it */
    val analyzer: String? = null,
    val analyzerPluginId: String? = null,
    val analyzedAt: Instant? = null,
    val failedAt: Instant? = null,
    val failureReason: String? = null,
)

/**
 * What the measurement sidecar made of a record.
 *
 * `complete` is NOT `analyzedAt`, and the two are separate fields for a reason `0005_music.sql`
 * argues at length: a measurement of a truncated download is confident and wrong, so every reader in
 * the app filters on `complete` and a page that showed only a date would be reporting a record as
 * measured that nothing will use the measurement of.
 */
@Serializable
class TrackAnalysisInput

/** One airing of a record, as this page needs it: when, and under which broadcast. */
@Serializable
data class TrackPlay(
    val airedAt: Instant,
    val broadcastId: Uuid? = null,
    /** What put it in the running order */
    val source: String,
)

/** One airing of a record, as this page needs it: when, and under which broadcast. */
@Serializable
class TrackPlayInput

/**
 * What a clear actually did.
 *
 * A count rather than a bare 204, because the interesting answers are the small ones: clearing the
 * audio of a record with three copies and being told `1` is the station saying two of them were
 * never here — which is a fact about the record and not about the button.
 */
@Serializable
data class TrackClearResult(
    val trackId: Uuid,
    /** Rows this affected. Zero is an ordinary answer, not a failure */
    val cleared: Long,
    /** What happened, in the words the console shows */
    val detail: String,
)

/**
 * What a clear actually did.
 *
 * A count rather than a bare 204, because the interesting answers are the small ones: clearing the
 * audio of a record with three copies and being told `1` is the station saying two of them were
 * never here — which is a fact about the record and not about the button.
 */
@Serializable
class TrackClearResultInput

/**
 * Narrow a clear to one provider's answer, for the case where one source is wrong and the rest are
 * not. Absent clears every provider's.
 */
@Serializable
data class ClearEnrichmentQuery(
    val provider: String? = null,
)

/**
 * What an artist or album list is ordered BY, where `Pagination.sort` says only which direction.
 *
 *   name    the default, and the only key every row here has
 *   albums  how many records the station holds of them. Artists only
 *   tracks  how many songs. Artists only
 *   year    when the record came out. Albums only
 *   rating  the operator's own opinion
 *
 * One enum for both lists rather than two, because the alternative is a second near-identical
 * contract whose only content is which two keys it drops. A key the row cannot answer falls back to
 * name order rather than failing: an ordering nobody can serve is a page an operator cannot open.
 */
@Serializable
enum class CatalogSort {
    @SerialName("name")
    NAME,
    @SerialName("albums")
    ALBUMS,
    @SerialName("tracks")
    TRACKS,
    @SerialName("year")
    YEAR,
    @SerialName("rating")
    RATING,
}

/**
 * Which records to show, by what the station has of them rather than by what they are.
 *
 *   cached      the audio is on this machine, so it can be committed to the running order now
 *   uncached    it is not, which for most of a library is ordinary rather than wrong
 *   unmeasured  no trustworthy measurement, so no cue points and no level decided before air
 *   benched     every copy written off, which is the one state that means it CANNOT air
 *   failing     a fetch has failed and is backing off. Not benched yet, and often the state before it
 */
@Serializable
enum class TrackState {
    @SerialName("cached")
    CACHED,
    @SerialName("uncached")
    UNCACHED,
    @SerialName("unmeasured")
    UNMEASURED,
    @SerialName("benched")
    BENCHED,
    @SerialName("failing")
    FAILING,
}

/**
 * What a track list is ordered BY. Its own enum for `TrackQuery`'s own reason: none of these keys
 * means anything about an artist, and `name` is spelled `title` on a song.
 *
 * `state` is deliberately absent. It is three independent booleans rather than one column, so there
 * is no ordering of it an operator would agree with: a benched record and an unmeasured one are not
 * more or less than each other.
 */
@Serializable
enum class TrackSort {
    @SerialName("title")
    TITLE,
    @SerialName("artist")
    ARTIST,
    @SerialName("album")
    ALBUM,
    @SerialName("year")
    YEAR,
    @SerialName("duration")
    DURATION,
    @SerialName("rating")
    RATING,
}

/**
 * How much of the library is in each state, over the whole filtered set rather than this page.
 *
 * The aggregate is what an operator reads first — "13 of 581 measured" is the sentence that made
 * [analysis-queue-ordering](https://github.com/robert-dean/deadair/discussions/5) necessary, and it was a psql query then. `total` is the
 * same number as `meta.total` when nothing is filtered, and is repeated here so the counts can be
 * read as N of M without reaching into the pager.
 */
@Serializable
data class TrackStateCounts(
    val total: Long,
    val cached: Long,
    val measured: Long,
    val enriched: Long,
    val benched: Long,
    val failing: Long,
)

/**
 * How much of the library is in each state, over the whole filtered set rather than this page.
 *
 * The aggregate is what an operator reads first — "13 of 581 measured" is the sentence that made
 * [analysis-queue-ordering](https://github.com/robert-dean/deadair/discussions/5) necessary, and it was a psql query then. `total` is the
 * same number as `meta.total` when nothing is filtered, and is repeated here so the counts can be
 * read as N of M without reaching into the pager.
 */
@Serializable
class TrackStateCountsInput

@Serializable
data class EnrichmentExternalId(
    /** e.g. `musicbrainz`, `wikidata` */
    val source: String,
    val id: String,
)

/**
 * Narrowed to http(s) by the host before it is stored, since the console renders these as
 * something a human clicks.
 */
@Serializable
data class EnrichmentLink(
    val label: String,
    val url: String,
)

/**
 * One thing the station believes, and the words it read that say so. Extracted by the host out of
 * an article a plugin handed over, rather than said by any plugin: `sourceUrl` is where a person
 * checks it and `sourceQuote` is the span that supports it, and neither is ever absent.
 */
@Serializable
data class FactClaim(
    val id: Uuid,
    /** One sentence, as the DJ would say it */
    val claim: String,
    val category: String,
    /** `lead` for the article's own opening, `model` for what a model found */
    val source: String,
    val sourceProvider: String,
    val sourceUrl: String,
    val sourceQuote: String,
    val confidence: Double? = null,
    val model: String? = null,
    /** Absent means never said on air */
    val lastUsedAt: Instant? = null,
)

/**
 * One thing the station believes, and the words it read that say so. Extracted by the host out of
 * an article a plugin handed over, rather than said by any plugin: `sourceUrl` is where a person
 * checks it and `sourceQuote` is the span that supports it, and neither is ever absent.
 */
@Serializable
class FactClaimInput

/**
 * Rate an artist, a record or a song. Ratings are absolute: a dislike anywhere above a track
 * excludes it, and nothing the station programmes may turn that off.
 */
@Serializable
data class RateInput(
    val rating: Rating,
)

/**
 * The canonical work, not a binding to a provider. `deadair.artists` minus the columns that
 * only ingest cares about: `artist_key` is a match key, and a row with `merged_into_id` set is
 * never read out at all.
 *
 * `imageUrl` on both contracts below is one field with two spellings. An absolute URL is the
 * provider's own, still hotlinked because nothing has cached it yet; a relative `art/<uuid>` is
 * the station's copy, to be resolved against the API base the client already configures (the API
 * mounts at the root and does not know the `/api` prefix the edge adds). Prefer the local one by
 * doing nothing: the switch happens server-side as soon as the art cache pass has the bytes.
 */
@Serializable
data class Artist(
    val id: Uuid,
    val name: String,
    /** MusicBrainz artist id, absent until enrichment resolves one */
    val mbid: Uuid? = null,
    /** Absolute upstream URL, or an API-relative path to the local copy */
    val imageUrl: String? = null,
    val rating: Rating? = Rating.NEUTRAL,
    /** Unmerged albums credited to this artist */
    val albumCount: Long,
    /** Unmerged tracks credited to this artist */
    val trackCount: Long,
)

/**
 * The canonical work, not a binding to a provider. `deadair.artists` minus the columns that
 * only ingest cares about: `artist_key` is a match key, and a row with `merged_into_id` set is
 * never read out at all.
 *
 * `imageUrl` on both contracts below is one field with two spellings. An absolute URL is the
 * provider's own, still hotlinked because nothing has cached it yet; a relative `art/<uuid>` is
 * the station's copy, to be resolved against the API base the client already configures (the API
 * mounts at the root and does not know the `/api` prefix the edge adds). Prefer the local one by
 * doing nothing: the switch happens server-side as soon as the art cache pass has the bytes.
 */
@Serializable
data class ArtistInput(
    val name: String,
    /** MusicBrainz artist id, absent until enrichment resolves one */
    val mbid: Uuid? = null,
    /** Absolute upstream URL, or an API-relative path to the local copy */
    val imageUrl: String? = null,
    val rating: Rating? = Rating.NEUTRAL,
)

@Serializable
data class Album(
    val id: Uuid,
    val name: String,
    val artistId: Uuid,
    /** Joined, so a list renders without a second request per row */
    val artistName: String,
    /** MusicBrainz release-group id, absent until enrichment resolves one */
    val mbid: Uuid? = null,
    val year: Long? = null,
    /** Absolute upstream URL, or an API-relative path to the local copy */
    val imageUrl: String? = null,
    val rating: Rating? = Rating.NEUTRAL,
    val trackCount: Long,
)

@Serializable
data class AlbumInput(
    val name: String,
    /** MusicBrainz release-group id, absent until enrichment resolves one */
    val mbid: Uuid? = null,
    val year: Long? = null,
    /** Absolute upstream URL, or an API-relative path to the local copy */
    val imageUrl: String? = null,
    val rating: Rating? = Rating.NEUTRAL,
)

@Serializable
data class Track(
    val id: Uuid,
    val title: String,
    val artistId: Uuid,
    val artistName: String,
    /** Absent on a single ingested outside any release: `tracks.album_id` is nullable */
    val albumId: Uuid? = null,
    val albumName: String? = null,
    /** The record's cover, in the two spellings `Album.imageUrl` has. Nothing hangs art off a recording */
    val albumImageUrl: String? = null,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
)

@Serializable
data class TrackInput(
    val title: String,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
)

/**
 * Pagination plus a name filter. Every list operation here takes it, so the console's search box
 * narrows server-side rather than filtering one page client-side and lying about the total.
 */
@Serializable
data class CatalogQuery(
    /** The page number */
    val page: Long? = 0L,
    /** The page size */
    val pageSize: Long? = 25L,
    /** The sort order */
    val sort: PaginationSort? = PaginationSort.DESC,
    /** The total number of items */
    val total: Long,
    val search: String? = null,
    val sortBy: CatalogSort? = null,
)

/**
 * Pagination plus a name filter. Every list operation here takes it, so the console's search box
 * narrows server-side rather than filtering one page client-side and lying about the total.
 */
@Serializable
data class CatalogQueryInput(
    /** The page number */
    val page: Long? = 0L,
    /** The page size */
    val pageSize: Long? = 25L,
    /** The sort order */
    val sort: PaginationSort? = PaginationSort.DESC,
    val search: String? = null,
    val sortBy: CatalogSort? = null,
)

/**
 * `releaseDate` is a string and not `datetime` because it is a partial date: MusicBrainz answers
 * `1997`, `1997-06` or `1997-06-24` depending on what is actually known about the release, and the
 * SDK types it the same way. A `datetime` would reject the first two or invent a day and a time
 * for them, which is a precision the source never claimed.
 */
@Serializable
data class TrackEnrichmentData(
    val artist: String? = null,
    val title: String? = null,
    val album: String? = null,
    val year: Long? = null,
    val releaseDate: String? = null,
    val genres: List<String>? = null,
    val moods: List<String>? = null,
    val biography: String? = null,
    /** Short lines, each independently speakable */
    val facts: List<String>? = null,
    /** Not an integer: a tempo a source measured rather than declared is fractional */
    val bpm: Double? = null,
    val musicalKey: String? = null,
    val label: String? = null,
    val isrc: String? = null,
    val artworkUrl: String? = null,
    val externalIds: List<EnrichmentExternalId>? = null,
    val links: List<EnrichmentLink>? = null,
    /** What the plugin said that the SDK has no field for. Per provider only: the merged view drops it */
    val extra: Map<String, JsonElement>? = null,
)

@Serializable
data class ArtistEnrichmentData(
    val name: String? = null,
    val biography: String? = null,
    val imageUrl: String? = null,
    val genres: List<String>? = null,
    val facts: List<String>? = null,
    val externalIds: List<EnrichmentExternalId>? = null,
    val links: List<EnrichmentLink>? = null,
    val extra: Map<String, JsonElement>? = null,
)

@Serializable
data class AlbumEnrichmentData(
    val name: String? = null,
    /** The record's own credit, which is not always the track's */
    val artist: String? = null,
    val year: Long? = null,
    /** Partial, exactly as on TrackEnrichmentData */
    val releaseDate: String? = null,
    val label: String? = null,
    val genres: List<String>? = null,
    val facts: List<String>? = null,
    val artworkUrl: String? = null,
    val externalIds: List<EnrichmentExternalId>? = null,
    val links: List<EnrichmentLink>? = null,
    val extra: Map<String, JsonElement>? = null,
)

/** One page of artists, with the totals the request was counted against */
@Serializable
data class ArtistPage(
    val meta: Pagination,
    val data: List<Artist>,
)

/** One page of artists, with the totals the request was counted against */
@Serializable
data class ArtistPageInput(
    val meta: PaginationInput,
    val data: List<ArtistInput>,
)

/** One page of albums */
@Serializable
data class AlbumPage(
    val meta: Pagination,
    val data: List<Album>,
)

/** One page of albums */
@Serializable
data class AlbumPageInput(
    val meta: PaginationInput,
    val data: List<AlbumInput>,
)

/**
 * Everything one record has accumulated, in one read.
 *
 * The enrichment is deliberately NOT here. It has its own operation already, answering
 * `TrackEnrichmentDetail` with every provider's payload and the station's own sourced claims, and
 * the console draws it through the same panel the list uses. One enrichment shape rather than two.
 */
@Serializable
data class TrackDetail(
    val id: Uuid,
    val title: String,
    val artistId: Uuid,
    val artistName: String,
    /** Absent on a single ingested outside any release: `tracks.album_id` is nullable */
    val albumId: Uuid? = null,
    val albumName: String? = null,
    /** The record's cover, in the two spellings `Album.imageUrl` has. Nothing hangs art off a recording */
    val albumImageUrl: String? = null,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
    val bindings: List<TrackBinding>,
    /** Absent for a record the walk has not reached */
    val analysis: TrackAnalysis? = null,
    /** The most recent airings, newest first */
    val plays: List<TrackPlay>,
    /** How many times in all, which the list above is only the head of */
    val playCount: Long,
)

/**
 * Everything one record has accumulated, in one read.
 *
 * The enrichment is deliberately NOT here. It has its own operation already, answering
 * `TrackEnrichmentDetail` with every provider's payload and the station's own sourced claims, and
 * the console draws it through the same panel the list uses. One enrichment shape rather than two.
 */
@Serializable
data class TrackDetailInput(
    val title: String,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
    val bindings: List<TrackBindingInput>,
    /** Absent for a record the walk has not reached */
    val analysis: TrackAnalysisInput? = null,
    /** The most recent airings, newest first */
    val plays: List<TrackPlayInput>,
)

/**
 * A track as a LIST shows it: the record, plus three facts about what the station has of it.
 *
 * Three booleans and no more, deliberately. They are what a row can afford — one `exists` each, off
 * the query that was already running — and everything wider (which providers, how many bytes, why the
 * last fetch failed) is `TrackDetail`'s, one click away. A fourth would be the beginning of putting
 * the detail page in a table cell.
 */
@Serializable
data class TrackRow(
    val id: Uuid,
    val title: String,
    val artistId: Uuid,
    val artistName: String,
    /** Absent on a single ingested outside any release: `tracks.album_id` is nullable */
    val albumId: Uuid? = null,
    val albumName: String? = null,
    /** The record's cover, in the two spellings `Album.imageUrl` has. Nothing hangs art off a recording */
    val albumImageUrl: String? = null,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
    /** The bytes are on this machine */
    val hasAudio: Boolean,
    /** Measured, COMPLETE, and at a schema version the station still trusts */
    val measured: Boolean,
    /** At least one provider has answered about it */
    val enriched: Boolean,
)

/**
 * A track as a LIST shows it: the record, plus three facts about what the station has of it.
 *
 * Three booleans and no more, deliberately. They are what a row can afford — one `exists` each, off
 * the query that was already running — and everything wider (which providers, how many bytes, why the
 * last fetch failed) is `TrackDetail`'s, one click away. A fourth would be the beginning of putting
 * the detail page in a table cell.
 */
@Serializable
data class TrackRowInput(
    val title: String,
    /** Display credit as written on the release ("X feat. Y"), not a join key */
    val artists: String,
    val genre: String? = null,
    val year: Long? = null,
    val durationMs: Long? = null,
    val rating: Rating? = Rating.NEUTRAL,
)

/**
 * A track list, narrowed by what the station has of each record as well as by name.
 *
 * Its own contract rather than a field on `CatalogQuery`, because that one is shared with the artist
 * and album lists where none of these states means anything.
 */
@Serializable
data class TrackQuery(
    /** The page number */
    val page: Long? = 0L,
    /** The page size */
    val pageSize: Long? = 25L,
    /** The sort order */
    val sort: PaginationSort? = PaginationSort.DESC,
    /** The total number of items */
    val total: Long,
    val search: String? = null,
    val sortBy: TrackSort? = null,
    val state: TrackState? = null,
)

/**
 * A track list, narrowed by what the station has of each record as well as by name.
 *
 * Its own contract rather than a field on `CatalogQuery`, because that one is shared with the artist
 * and album lists where none of these states means anything.
 */
@Serializable
data class TrackQueryInput(
    /** The page number */
    val page: Long? = 0L,
    /** The page size */
    val pageSize: Long? = 25L,
    /** The sort order */
    val sort: PaginationSort? = PaginationSort.DESC,
    val search: String? = null,
    val sortBy: TrackSort? = null,
    val state: TrackState? = null,
)

/**
 * One provider's stored answer. `found: false` is a recorded miss, which is a fact rather than a
 * failure: the provider was asked, had nothing, and is not asked again until `expiresAt`. A provider
 * that could not be asked at all is `failed` instead, and the two never both hold.
 */
@Serializable
data class TrackEnrichmentSource(
    val provider: String,
    /** The id it was fetched under. Provenance, not identity */
    val providerRef: String? = null,
    val fetchedAt: Instant,
    val expiresAt: Instant? = null,
    /** Past its TTL, so the next pass will ask again */
    val stale: Boolean,
    val found: Boolean,
    /** The last attempt errored, so `expiresAt` is a backoff rather than a TTL */
    val failed: Boolean,
    val data: TrackEnrichmentData,
)

/**
 * One provider's stored answer. `found: false` is a recorded miss, which is a fact rather than a
 * failure: the provider was asked, had nothing, and is not asked again until `expiresAt`. A provider
 * that could not be asked at all is `failed` instead, and the two never both hold.
 */
@Serializable
data class TrackEnrichmentSourceInput(
    val data: TrackEnrichmentData,
)

@Serializable
data class ArtistEnrichmentSource(
    val provider: String,
    val providerRef: String? = null,
    val fetchedAt: Instant,
    val expiresAt: Instant? = null,
    val stale: Boolean,
    val found: Boolean,
    /** The last attempt errored, so `expiresAt` is a backoff rather than a TTL */
    val failed: Boolean,
    val data: ArtistEnrichmentData,
)

@Serializable
data class ArtistEnrichmentSourceInput(
    val data: ArtistEnrichmentData,
)

@Serializable
data class AlbumEnrichmentSource(
    val provider: String,
    val providerRef: String? = null,
    val fetchedAt: Instant,
    val expiresAt: Instant? = null,
    val stale: Boolean,
    val found: Boolean,
    /** The last attempt errored, so `expiresAt` is a backoff rather than a TTL */
    val failed: Boolean,
    val data: AlbumEnrichmentData,
)

@Serializable
data class AlbumEnrichmentSourceInput(
    val data: AlbumEnrichmentData,
)

/** One page of tracks, with what the station has of each and of the whole set */
@Serializable
data class TrackPage(
    val meta: Pagination,
    val data: List<TrackRow>,
    val states: TrackStateCounts,
)

/** One page of tracks, with what the station has of each and of the whole set */
@Serializable
data class TrackPageInput(
    val meta: PaginationInput,
    val data: List<TrackRowInput>,
    val states: TrackStateCountsInput,
)

/**
 * Every provider's answer, plus the same merge the promotion step used, so the console and the
 * canonical columns cannot tell different stories. `sources` is empty on a row the walk has not
 * reached yet.
 *
 * `claims` sits beside them rather than inside `merged`, because a claim is the host's own and not
 * any provider's. The articles they were read out of are deliberately NOT here: raw source prose is
 * stored and never sent.
 */
@Serializable
data class TrackEnrichmentDetail(
    val trackId: Uuid,
    val merged: TrackEnrichmentData,
    val sources: List<TrackEnrichmentSource>,
    val claims: List<FactClaim>,
)

/**
 * Every provider's answer, plus the same merge the promotion step used, so the console and the
 * canonical columns cannot tell different stories. `sources` is empty on a row the walk has not
 * reached yet.
 *
 * `claims` sits beside them rather than inside `merged`, because a claim is the host's own and not
 * any provider's. The articles they were read out of are deliberately NOT here: raw source prose is
 * stored and never sent.
 */
@Serializable
data class TrackEnrichmentDetailInput(
    val merged: TrackEnrichmentData,
    val sources: List<TrackEnrichmentSourceInput>,
    val claims: List<FactClaimInput>,
)

@Serializable
data class ArtistEnrichmentDetail(
    val artistId: Uuid,
    val merged: ArtistEnrichmentData,
    val sources: List<ArtistEnrichmentSource>,
    val claims: List<FactClaim>,
)

@Serializable
data class ArtistEnrichmentDetailInput(
    val merged: ArtistEnrichmentData,
    val sources: List<ArtistEnrichmentSourceInput>,
    val claims: List<FactClaimInput>,
)

@Serializable
data class AlbumEnrichmentDetail(
    val albumId: Uuid,
    val merged: AlbumEnrichmentData,
    val sources: List<AlbumEnrichmentSource>,
    val claims: List<FactClaim>,
)

@Serializable
data class AlbumEnrichmentDetailInput(
    val merged: AlbumEnrichmentData,
    val sources: List<AlbumEnrichmentSourceInput>,
    val claims: List<FactClaimInput>,
)
