// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.models

import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** What a listener is hearing right now: a record, or the station talking */
@Serializable
data class NowPlayingTrack(
    /** `record` is music. `break` is the station speaking on its own between two records (an ident, a bulletin, a talk break), with `artist` empty and `title` the break's own label. A presenter talking over the start of a record is not a break: the record is what is on air, and it stays `record`. Absent means `record`, which is all a station older than this field ever reported */
    val kind: NowPlayingTrackKind? = NowPlayingTrackKind.RECORD,
    val title: String,
    /** Comma-joined, as a display line rather than a list: this is what a player or a device shows, not something to iterate. Empty for a `break` */
    val artist: String,
    val album: String? = null,
    /** The station's own cached cover, as a path under the API root (`art/...`). Absent while the station does not yet hold the cover, which a player answers with the station's logo; never a provider's URL */
    val artworkUrl: String? = null,
    val durationMs: Long? = null,
    /** Unix epoch millis, as observed when the player reported the track started */
    val startedAt: Long,
    /** Absent when the decoder cannot say. It leads the listener by the encoder and client buffers, so it is a display value and not a schedule */
    val remainingMs: Long? = null,
)

/** One way to listen to this station right now */
@Serializable
data class NowPlayingMount(
    /** `hls` is the master playlist rather than an Icecast mount, which is why this enum has an arm `PlayoutMount` does not */
    val format: NowPlayingMountFormat,
    /** Same-origin path, leading slash included. A path and not a URL: the station is reached through whatever edge served this answer, never at the address the app itself uses */
    val path: String,
    /** Absent for FLAC, which is lossless and has no rate to set, and for HLS, whose rate is the AAC variant's */
    val bitrateKbps: Long? = null,
)

/** The programme on air, as a listener would be told it */
@Serializable
data class NowPlayingShow(
    /** What this broadcast is called. It changes the moment the station changes programme, which can be one record before the new programme's first record is heard: a changeover never cuts a listener off mid-record */
    val name: String,
    /** Who is presenting, by the name they go by on air. Absent when there is no name to give: no persona on air with one, and no station-wide presenter name set. Never the persona's console label */
    val host: String? = null,
    /** A picture of whoever is presenting, when the operator gave their persona one. A path under the API root, like a cover's. Absent for a persona with no picture, which a player answers by showing the record's cover as before */
    val hostArtUrl: String? = null,
)

/** The words of whatever record is on air, and where it is in them */
@Serializable
data class NowPlayingLyrics(
    /** False when nothing is airing, with everything else absent */
    val onAir: Boolean,
    /** The catalog record on air. Absent while the station is talking, and for a record the catalog has never held */
    val trackId: Uuid? = null,
    /** Unix epoch millis when the record went on air, the same instant `/nowplaying` reports. Match on it before pairing these lyrics with a `/nowplaying` reading */
    val startedAt: Long? = null,
    /** Where in the file the record started playing. Absent means the top of the file */
    val cueInMs: Long? = null,
    /** Where in the file the record stops playing. A line's `atMs` counts from the top of the file and the decoder's `remainingMs` counts down to this point, so the position to highlight is this (or the record's `durationMs` when absent) minus `remainingMs`. Absent for a record nothing has measured, which plays to the end of the file */
    val cueOutMs: Long? = null,
    /** The station's answer for that record. Absent with no `trackId` */
    val lyrics: TrackLyrics? = null,
)

/** The words of whatever record is on air, and where it is in them */
@Serializable
data class NowPlayingLyricsInput(
    /** False when nothing is airing, with everything else absent */
    val onAir: Boolean,
    /** The catalog record on air. Absent while the station is talking, and for a record the catalog has never held */
    val trackId: Uuid? = null,
    /** Unix epoch millis when the record went on air, the same instant `/nowplaying` reports. Match on it before pairing these lyrics with a `/nowplaying` reading */
    val startedAt: Long? = null,
    /** Where in the file the record started playing. Absent means the top of the file */
    val cueInMs: Long? = null,
    /** Where in the file the record stops playing. A line's `atMs` counts from the top of the file and the decoder's `remainingMs` counts down to this point, so the position to highlight is this (or the record's `durationMs` when absent) minus `remainingMs`. Absent for a record nothing has measured, which plays to the end of the file */
    val cueOutMs: Long? = null,
    /** The station's answer for that record. Absent with no `trackId` */
    val lyrics: TrackLyricsInput? = null,
)

/** What the station is playing, for anything that wants to display it */
@Serializable
data class NowPlaying(
    /** The station's on-air name */
    val station: String,
    /** False means the station is not broadcasting. `track` is absent in that case, which is an ordinary state and not an error */
    val onAir: Boolean,
    /** How many people are listening right now. Public because it says only what Icecast's own status document already says to anyone who asks, and a station page should not need a session to show it */
    val listeners: Long,
    /** Every way to listen, MP3 first. Never empty: MP3 has no switch. A format the operator has not switched on is ABSENT rather than present and disabled, because a client asking this wants the mounts that are actually there — and a client that had to find out by connecting to each one would put an audience-gated station on air to do it */
    val mounts: List<NowPlayingMount>,
    /** Present whenever `track` is and the station has said what programme it belongs to. Absent off air, and while a station warming up has nothing airing yet */
    val show: NowPlayingShow? = null,
    val track: NowPlayingTrack? = null,
)

/** `record` is music. `break` is the station speaking on its own between two records (an ident, a bulletin, a talk break), with `artist` empty and `title` the break's own label. A presenter talking over the start of a record is not a break: the record is what is on air, and it stays `record`. Absent means `record`, which is all a station older than this field ever reported */
@Serializable
enum class NowPlayingTrackKind {
    @SerialName("record")
    RECORD,
    @SerialName("break")
    BREAK,
}

/** `hls` is the master playlist rather than an Icecast mount, which is why this enum has an arm `PlayoutMount` does not */
@Serializable
enum class NowPlayingMountFormat {
    @SerialName("mp3")
    MP3,
    @SerialName("opus")
    OPUS,
    @SerialName("aac")
    AAC,
    @SerialName("flac")
    FLAC,
    @SerialName("hls")
    HLS,
}
