// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class OnboardingRequirementKey {
    @SerialName("admin.account")
    ADMIN_ACCOUNT,
}

/** A single onboarding requirement */
@Serializable
data class CoreOnboardingRequirement(
    /** The key of the requirement */
    val key: OnboardingRequirementKey,
    /** Human-readable label for the onboarding checklist */
    val title: String,
    /** Optional longer explanation */
    val description: String? = null,
    /** Whether the requirement is optional for onboarding */
    val optional: Boolean,
)

/** A single onboarding requirement */
@Serializable
data class CoreOnboardingRequirementInput(
    /** The key of the requirement */
    val key: OnboardingRequirementKey,
)

@Serializable
data class AdminAccountOnboardingRequirement(
    val key: String = "admin.account",
    /** Human-readable label for the onboarding checklist */
    val title: String,
    /** Optional longer explanation */
    val description: String? = null,
    /** Whether the requirement is optional for onboarding */
    val optional: Boolean,
)

@Serializable
data class AdminAccountOnboardingRequirementInput(
    val key: String = "admin.account",
    val value: AdminAccountOnboardingRequirementValue,
)

typealias OnboardingRequirement = AdminAccountOnboardingRequirement
typealias OnboardingRequirementInput = AdminAccountOnboardingRequirementInput

@Serializable
data class AdminAccountOnboardingRequirementValue(
    val email: String,
    /** The password */
    val password: String,
)
