// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.models

import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** A record the station holds and could be asked for */
@Serializable
data class RequestableTrack(
    /** What to send as `trackId` to make the request */
    val trackId: Uuid,
    val title: String,
    /** The lead artist */
    val artist: String,
    val album: String? = null,
    val year: Long? = null,
)

@Serializable
enum class RequestStatus {
    @SerialName("waiting")
    WAITING,
    @SerialName("pending")
    PENDING,
    @SerialName("queued")
    QUEUED,
    @SerialName("aired")
    AIRED,
    @SerialName("declined")
    DECLINED,
    @SerialName("expired")
    EXPIRED,
}

@Serializable
enum class RequestSource {
    @SerialName("app")
    APP,
    @SerialName("chat")
    CHAT,
}

/** Ask the station to play a record */
@Serializable
data class ListenerRequestCreate(
    /** A record from the request search */
    val trackId: Uuid,
    /** What the station should call you. Omitted, you are "a listener": your account's email address is never shown or read out */
    val name: String? = null,
    /** Dedicate it to somebody. The station may say this name on air */
    val dedicateTo: String? = null,
    /** A few words to go with it. The presenter may put them in their own words on air, and leaves out anything unfit to broadcast; the words themselves are never read out */
    val message: String? = null,
)

/** Turn a request down */
@Serializable
data class ListenerRequestDecline(
    /** What to tell the listener. Omit for a plain no */
    val reason: String? = null,
)

/** Records matching a search, best matches first */
@Serializable
data class RequestableTrackList(
    val tracks: List<RequestableTrack>,
)

/** A record somebody asked the station to play, and what became of it */
@Serializable
data class ListenerRequest(
    val id: Uuid,
    /** `waiting` for an operator to approve it, `pending` while its audio is fetched or a place is found for it, `queued` in the running order, `aired` once heard, `declined` or `expired` when it never will be */
    val status: RequestStatus,
    /** The record, as it was called when it was asked for */
    val title: String,
    val artist: String,
    /** Who asked, by the name their account or chat platform gave */
    val requesterName: String,
    /** Whether it came from an app or a chat platform */
    val source: RequestSource,
    /** When it was asked for */
    val createdAt: Instant,
    /** Why it was declined or expired, in the station's words or an operator's */
    val reason: String? = null,
    /** When it aired */
    val airedAt: Instant? = null,
    /** Who the listener dedicated it to */
    val dedicateTo: String? = null,
    /** What the listener asked to have said with it, in their own words */
    val message: String? = null,
)

/** Requests, newest first */
@Serializable
data class ListenerRequestList(
    val requests: List<ListenerRequest>,
)
