// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.models

import kotlin.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A playlist the station owns: records it holds in its own library, in an order somebody chose, cloned
 * from somewhere else and free to differ from it afterwards
 */
@Serializable
data class StationPlaylist(
    val id: String,
    val name: String,
    /** What this playlist is for, in the operator's own words. Empty when nobody said */
    val prompt: String,
    /** The plugin this was cloned from, for a badge and nothing else. Absent for one read from a file or made here */
    val originPluginId: String? = null,
    /** Every row, placeholders included */
    val trackCount: Long,
    /** The rows that name a record in the library, which are the ones that can air */
    val resolvedCount: Long,
    val createdAt: Instant,
    val updatedAt: Instant,
)

/**
 * A playlist the station owns: records it holds in its own library, in an order somebody chose, cloned
 * from somewhere else and free to differ from it afterwards
 */
@Serializable
data class StationPlaylistInput(
    val name: String,
    /** What this playlist is for, in the operator's own words. Empty when nobody said */
    val prompt: String,
)

/** One row of a station playlist: a record in the library, or a placeholder for one it does not hold yet */
@Serializable
data class StationPlaylistTrack(
    /** The row's own id, not the record's */
    val id: String,
    val position: Long,
    val title: String,
    /** Ordered, primary artist first */
    val artists: List<String>,
    val album: String? = null,
    val durationMs: Long? = null,
    /** The library record this row plays. Absent on a placeholder */
    val trackId: String? = null,
    val artistId: String? = null,
    val albumId: String? = null,
    /** On a placeholder, the plugin whose copy it was cloned from. Absent on one read from a file, which names a record and no copy of it */
    val originPluginId: String? = null,
)

/** What may change about a station playlist after it exists. Absent fields are left alone */
@Serializable
data class StationPlaylistUpdate(
    val name: String? = null,
    val prompt: String? = null,
)

/**
 * Where a record in a file came from, when it came from a provider's copy. Carried so a record the
 * receiving library does not hold can still be matched by that copy later
 */
@Serializable
data class PlaylistFileOrigin(
    val pluginId: String,
    val externalId: String,
)

/** What importing one record would do here */
@Serializable
data class PlaylistImportEntry(
    val position: Long,
    val title: String,
    val artists: List<String>,
    /** `matched`: the library holds it. `toAdd`: it names a provider's copy, which the station can add to its library. `toLookUp`: it names only a record, which the station has to search its providers for */
    val outcome: PlaylistImportEntryOutcome,
    /** The library record a `matched` row plays */
    val trackId: String? = null,
)

@Serializable
data class StationPlaylistList(
    val playlists: List<StationPlaylist>,
)

@Serializable
data class StationPlaylistListInput(
    val playlists: List<StationPlaylistInput>,
)

@Serializable
data class StationPlaylistDetail(
    val id: String,
    val name: String,
    /** What this playlist is for, in the operator's own words. Empty when nobody said */
    val prompt: String,
    /** The plugin this was cloned from, for a badge and nothing else. Absent for one read from a file or made here */
    val originPluginId: String? = null,
    /** Every row, placeholders included */
    val trackCount: Long,
    /** The rows that name a record in the library, which are the ones that can air */
    val resolvedCount: Long,
    val createdAt: Instant,
    val updatedAt: Instant,
    val tracks: List<StationPlaylistTrack>,
)

@Serializable
data class StationPlaylistDetailInput(
    val name: String,
    /** What this playlist is for, in the operator's own words. Empty when nobody said */
    val prompt: String,
    val tracks: List<StationPlaylistTrack>,
)

/**
 * One record as a playlist file names it. By its words and its ISRC, never by an id of this station's:
 * ids are minted afresh by every library, so a file keyed by them would restore onto nothing
 */
@Serializable
data class PlaylistFileTrack(
    val title: String,
    /** Ordered, primary artist first */
    val artists: List<String>,
    val album: String? = null,
    val durationMs: Long? = null,
    val isrc: String? = null,
    val origin: PlaylistFileOrigin? = null,
)

/** What an import WOULD do, written nowhere */
@Serializable
data class PlaylistImportPlan(
    val name: String,
    val matched: Long,
    val toAdd: Long,
    val toLookUp: Long,
    /** Lines of the source that named no record the station could read */
    val skipped: Long,
    val entries: List<PlaylistImportEntry>,
    /** Anything about the source as a whole an operator should know before importing it */
    val notices: List<String>,
)

/** A playlist as a file: everything somebody would need to rebuild it on another station */
@Serializable
data class PlaylistFile(
    /** What shape this is, so a file from a later build says so rather than being read wrongly */
    val format: String,
    /** When it was exported, ISO-8601 */
    val takenAt: String,
    /** The station it was taken from. Provenance only */
    val station: String? = null,
    val name: String,
    val prompt: String? = null,
    val tracks: List<PlaylistFileTrack>,
)

@Serializable
data class PlaylistImportResult(
    val plan: PlaylistImportPlan,
    val playlist: StationPlaylist,
)

@Serializable
data class PlaylistImportResultInput(
    val plan: PlaylistImportPlan,
    val playlist: StationPlaylistInput,
)

/** Something to import a playlist from. Exactly one source */
@Serializable
data class PlaylistImportInput(
    /** A playlist exported from a deadair station */
    val file: PlaylistFile? = null,
    /** What to call the new playlist. Absent keeps the name the source gives it */
    val name: String? = null,
)

/** `matched`: the library holds it. `toAdd`: it names a provider's copy, which the station can add to its library. `toLookUp`: it names only a record, which the station has to search its providers for */
@Serializable
enum class PlaylistImportEntryOutcome {
    @SerialName("matched")
    MATCHED,
    @SerialName("toAdd")
    TO_ADD,
    @SerialName("toLookUp")
    TO_LOOK_UP,
}
