// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** What a break can be about: a news category, and later a weather location. The operator's own vocabulary, per sort of break */
@Serializable
data class Topic(
    val id: String,
    /** Which sort of break this is a subject for, as `segments.kind` spells it */
    val kind: String,
    /** A stable slug, unique within its kind. What the format clock points a band at and what a seeded topic is recognised by */
    val key: String,
    /** What a break calls it out loud, so it is the phrasing you would want to hear */
    val label: String,
    /** This sort of break's own settings for this subject, in the fields its kind declares. Nothing generic reads them */
    val config: Map<String, JsonElement>,
    /** Your own order, for the list. Two subjects never contest anything, so it means nothing else */
    val position: Long,
)

/** What a break can be about: a news category, and later a weather location. The operator's own vocabulary, per sort of break */
@Serializable
data class TopicInput(
    /** Which sort of break this is a subject for, as `segments.kind` spells it */
    val kind: String,
    /** A stable slug, unique within its kind. What the format clock points a band at and what a seeded topic is recognised by */
    val key: String,
    /** What a break calls it out loud, so it is the phrasing you would want to hear */
    val label: String,
    /** This sort of break's own settings for this subject, in the fields its kind declares. Nothing generic reads them */
    val config: Map<String, JsonElement>,
    /** Your own order, for the list. Two subjects never contest anything, so it means nothing else */
    val position: Long,
)

/** A sort of break that has subjects at all, and how one of its subjects is edited. `ConfigFieldDescriptor` is the plugins area's, shared for the reason a station setting shares it: one form component renders them all */
@Serializable
data class TopicKindDescriptor(
    val kind: String,
    /** What to call one of these: a news subject is a category and a weather subject is a location */
    val nounOne: String,
    val nounMany: String,
    val description: String,
    val fields: List<ConfigFieldDescriptor>,
)

@Serializable
data class TopicQuery(
    /** One sort of break, or absent for every subject this station has named */
    val kind: String? = null,
)

@Serializable
data class TopicList(
    val topics: List<Topic>,
)

@Serializable
data class TopicListInput(
    val topics: List<TopicInput>,
)

@Serializable
data class TopicKindList(
    val kinds: List<TopicKindDescriptor>,
)
