// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `art.ck`. */
class ArtClient(private val http: SdkHttp) {
    /**
     * Get source art
     * The bytes of a cover the station fetches on first ask, addressed by its sealed source
     */
    suspend fun getSourceArt(token: String): GetSourceArtResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("art", "source", segment(token))
        }
        return when (response.status.value) {
            304 -> {
                GetSourceArtResponse.Status304
            }
            else -> {
                val headers = GetSourceArt200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "image/png" -> GetSourceArtResponse.Status200ImagePng(response.bytes, headers)
                    "image/webp" -> GetSourceArtResponse.Status200ImageWebp(response.bytes, headers)
                    "image/gif" -> GetSourceArtResponse.Status200ImageGif(response.bytes, headers)
                    else -> GetSourceArtResponse.Status200ImageJpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Get source art file
     * The bytes of a cover the station fetches on first ask, under any filename
     */
    suspend fun getSourceArtFile(token: String, filename: String): GetSourceArtFileResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("art", "source", segment(token), segment(filename))
        }
        return when (response.status.value) {
            304 -> {
                GetSourceArtFileResponse.Status304
            }
            else -> {
                val headers = GetSourceArtFile200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "image/png" -> GetSourceArtFileResponse.Status200ImagePng(response.bytes, headers)
                    "image/webp" -> GetSourceArtFileResponse.Status200ImageWebp(response.bytes, headers)
                    "image/gif" -> GetSourceArtFileResponse.Status200ImageGif(response.bytes, headers)
                    else -> GetSourceArtFileResponse.Status200ImageJpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Get art
     * The bytes of one cached image, addressed by its id alone
     */
    suspend fun getArt(id: Uuid): GetArtResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("art", segment(id))
        }
        return when (response.status.value) {
            304 -> {
                GetArtResponse.Status304
            }
            else -> {
                val headers = GetArt200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "image/png" -> GetArtResponse.Status200ImagePng(response.bytes, headers)
                    "image/webp" -> GetArtResponse.Status200ImageWebp(response.bytes, headers)
                    "image/gif" -> GetArtResponse.Status200ImageGif(response.bytes, headers)
                    else -> GetArtResponse.Status200ImageJpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Get art file
     * The bytes of one cached image, under any filename
     */
    suspend fun getArtFile(id: Uuid, filename: String): GetArtFileResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("art", segment(id), segment(filename))
        }
        return when (response.status.value) {
            304 -> {
                GetArtFileResponse.Status304
            }
            else -> {
                val headers = GetArtFile200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "image/png" -> GetArtFileResponse.Status200ImagePng(response.bytes, headers)
                    "image/webp" -> GetArtFileResponse.Status200ImageWebp(response.bytes, headers)
                    "image/gif" -> GetArtFileResponse.Status200ImageGif(response.bytes, headers)
                    else -> GetArtFileResponse.Status200ImageJpeg(response.bytes, headers)
                }
            }
        }
    }
}

/** Response headers declared on GET /art/source/{token}. */
data class GetSourceArt200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /art/source/{token} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetSourceArtResponse {
    data class Status200ImageJpeg(
        val data: ByteArray,
    val headers: GetSourceArt200Headers,
    ) : GetSourceArtResponse
    data class Status200ImagePng(
        val data: ByteArray,
    val headers: GetSourceArt200Headers,
    ) : GetSourceArtResponse
    data class Status200ImageWebp(
        val data: ByteArray,
    val headers: GetSourceArt200Headers,
    ) : GetSourceArtResponse
    data class Status200ImageGif(
        val data: ByteArray,
    val headers: GetSourceArt200Headers,
    ) : GetSourceArtResponse
    data object Status304 : GetSourceArtResponse
}

/** Response headers declared on GET /art/source/{token}/{filename}. */
data class GetSourceArtFile200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /art/source/{token}/{filename} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetSourceArtFileResponse {
    data class Status200ImageJpeg(
        val data: ByteArray,
    val headers: GetSourceArtFile200Headers,
    ) : GetSourceArtFileResponse
    data class Status200ImagePng(
        val data: ByteArray,
    val headers: GetSourceArtFile200Headers,
    ) : GetSourceArtFileResponse
    data class Status200ImageWebp(
        val data: ByteArray,
    val headers: GetSourceArtFile200Headers,
    ) : GetSourceArtFileResponse
    data class Status200ImageGif(
        val data: ByteArray,
    val headers: GetSourceArtFile200Headers,
    ) : GetSourceArtFileResponse
    data object Status304 : GetSourceArtFileResponse
}

/** Response headers declared on GET /art/{id}. */
data class GetArt200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /art/{id} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetArtResponse {
    data class Status200ImageJpeg(
        val data: ByteArray,
    val headers: GetArt200Headers,
    ) : GetArtResponse
    data class Status200ImagePng(
        val data: ByteArray,
    val headers: GetArt200Headers,
    ) : GetArtResponse
    data class Status200ImageWebp(
        val data: ByteArray,
    val headers: GetArt200Headers,
    ) : GetArtResponse
    data class Status200ImageGif(
        val data: ByteArray,
    val headers: GetArt200Headers,
    ) : GetArtResponse
    data object Status304 : GetArtResponse
}

/** Response headers declared on GET /art/{id}/{filename}. */
data class GetArtFile200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /art/{id}/{filename} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetArtFileResponse {
    data class Status200ImageJpeg(
        val data: ByteArray,
    val headers: GetArtFile200Headers,
    ) : GetArtFileResponse
    data class Status200ImagePng(
        val data: ByteArray,
    val headers: GetArtFile200Headers,
    ) : GetArtFileResponse
    data class Status200ImageWebp(
        val data: ByteArray,
    val headers: GetArtFile200Headers,
    ) : GetArtFileResponse
    data class Status200ImageGif(
        val data: ByteArray,
    val headers: GetArtFile200Headers,
    ) : GetArtFileResponse
    data object Status304 : GetArtFileResponse
}
