// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.AuthSession
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `authentication.sessions.ck`. */
class AuthenticationSessionsClient(private val http: SdkHttp) {
    /**
     * Logout
     * revoke the caller's current session (self sign-out). Deliberately carries no policy gate: signing out must always clear the browser's httpOnly refresh cookie, including for a caller whose access token has already expired. A 401 here would leave a 30-day refresh cookie behind that silently signs the user back in on the next page load. SessionsService revokes the session only when the caller is actually authenticated; an anonymous caller still gets 204 and a cleared cookie.
     */
    suspend fun logout() {
        http.execute(HttpMethod.Post) {
            path("auth", "logout")
        }
    }

    /**
     * Read session
     * Who the caller is and which platform roles they hold
     */
    suspend fun readSession(): AuthSession {
        val response = http.execute(HttpMethod.Get) {
            path("auth", "session")
        }
        return http.decodeJson(response)
    }
}
