// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.AuthenticationFactor
import com.maroonedsoftware.deadair.sdk.models.AuthenticationFactorRegistration
import com.maroonedsoftware.deadair.sdk.models.AuthenticationFactorRegistrationResponse
import com.maroonedsoftware.deadair.sdk.models.AuthenticationFactorRegistrationVerification
import com.maroonedsoftware.deadair.sdk.models.AuthenticationToken
import com.maroonedsoftware.deadair.sdk.models.FactorChallengeStartRequest
import com.maroonedsoftware.deadair.sdk.models.FactorChallengeStartResponse
import com.maroonedsoftware.deadair.sdk.models.StepUpStartRequest
import com.maroonedsoftware.deadair.sdk.models.StepUpStartResponse
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `authentication.factor.ck`. */
class AuthenticationFactorClient(private val http: SdkHttp) {
    /**
     * List factors
     * List authentication factors
     */
    suspend fun listFactors(): List<AuthenticationFactor> {
        val response = http.execute(HttpMethod.Get) {
            path("auth", "factors")
        }
        return http.decodeJson(response)
    }

    /**
     * Register factor
     * Register an authentication factor
     */
    suspend fun registerFactor(body: AuthenticationFactorRegistration): AuthenticationFactorRegistrationResponse {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "factors", "register")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Verify factor registration
     * Verify an authentication factor registration
     */
    suspend fun verifyFactorRegistration(body: AuthenticationFactorRegistrationVerification): AuthenticationToken {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "factors", "verify")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Start factor challenge
     * Issue a factor verification challenge for a pending MFA round. Authenticated via the short-lived `mfa_challenge_id` in the body, not by session — this is the only /auth/factors/\* route that does not require an authenticated session.
     */
    suspend fun startFactorChallenge(body: FactorChallengeStartRequest): FactorChallengeStartResponse {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "factors", "start")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Start MFA challenge
     * Mint a fresh MFA challenge for the *current* authenticated session so the SPA can satisfy a `step_up_required` denial. Optionally filters eligible factors against an inbound `StepUpRequirement` hint. Returns `enrollment_required` when no enrolled factor matches the requirement so the SPA can route the user into enrollment instead of getting stuck.
     */
    suspend fun startMfaChallenge(body: StepUpStartRequest): StepUpStartResponse {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "mfa", "start")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }
}
