// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.Album
import com.maroonedsoftware.deadair.sdk.models.AlbumEnrichmentDetail
import com.maroonedsoftware.deadair.sdk.models.AlbumPage
import com.maroonedsoftware.deadair.sdk.models.Artist
import com.maroonedsoftware.deadair.sdk.models.ArtistEnrichmentDetail
import com.maroonedsoftware.deadair.sdk.models.ArtistPage
import com.maroonedsoftware.deadair.sdk.models.CatalogQueryInput
import com.maroonedsoftware.deadair.sdk.models.ClearEnrichmentQuery
import com.maroonedsoftware.deadair.sdk.models.RateInput
import com.maroonedsoftware.deadair.sdk.models.Track
import com.maroonedsoftware.deadair.sdk.models.TrackClearResult
import com.maroonedsoftware.deadair.sdk.models.TrackDetail
import com.maroonedsoftware.deadair.sdk.models.TrackEnrichmentDetail
import com.maroonedsoftware.deadair.sdk.models.TrackPage
import com.maroonedsoftware.deadair.sdk.models.TrackQueryInput
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `catalog.ck`. */
class CatalogClient(private val http: SdkHttp) {
    /**
     * List artists
     * Every artist the station has ingested, ordered by name
     */
    suspend fun listArtists(query: CatalogQueryInput? = null): ArtistPage {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "artists")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Get artist
     * One artist. 404s on an id that was merged away, since reads never return merged rows
     */
    suspend fun getArtist(id: Uuid): Artist {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "artists", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Get artist enrichment
     * What every enrichment provider said about this artist, and when each of them said it
     */
    suspend fun getArtistEnrichment(id: Uuid): ArtistEnrichmentDetail {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "artists", segment(id), "enrichment")
        }
        return http.decodeJson(response)
    }

    /**
     * List artist albums
     * The albums credited to one artist
     */
    suspend fun listArtistAlbums(id: Uuid, query: CatalogQueryInput? = null): AlbumPage {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "artists", segment(id), "albums")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Rate artist
     * What the station thinks of this artist. A dislike here excludes every record they are credited on
     */
    suspend fun rateArtist(id: Uuid, body: RateInput): Artist {
        val response = http.execute(HttpMethod.Put) {
            path("catalog", "artists", segment(id), "rating")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /** List albums */
    suspend fun listAlbums(query: CatalogQueryInput? = null): AlbumPage {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "albums")
            params(query)
        }
        return http.decodeJson(response)
    }

    /** Get album */
    suspend fun getAlbum(id: Uuid): Album {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "albums", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Get album enrichment
     * The record's own enrichment: the label, pressing and cover belong to the release, not to a track on it
     */
    suspend fun getAlbumEnrichment(id: Uuid): AlbumEnrichmentDetail {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "albums", segment(id), "enrichment")
        }
        return http.decodeJson(response)
    }

    /**
     * List album tracks
     * One album's tracks
     */
    suspend fun listAlbumTracks(id: Uuid, query: TrackQueryInput? = null): TrackPage {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "albums", segment(id), "tracks")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Rate album
     * What the station thinks of this record. A dislike here excludes every track on it
     */
    suspend fun rateAlbum(id: Uuid, body: RateInput): Album {
        val response = http.execute(HttpMethod.Put) {
            path("catalog", "albums", segment(id), "rating")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Get track
     * One record and everything it has accumulated: its copies, its bytes, its measurement, what it has aired
     */
    suspend fun getTrack(id: Uuid): TrackDetail {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "tracks", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Clear track audio
     * Drop the station's own copies of this record. The next play fetches them again
     * @throws SdkError on 409
     */
    suspend fun clearTrackAudio(id: Uuid): TrackClearResult {
        val response = http.execute(HttpMethod.Delete) {
            path("catalog", "tracks", segment(id), "audio")
        }
        return http.decodeJson(response)
    }

    /**
     * Clear track analysis
     * Forget the measurement, so the walk takes it again
     */
    suspend fun clearTrackAnalysis(id: Uuid): TrackClearResult {
        val response = http.execute(HttpMethod.Delete) {
            path("catalog", "tracks", segment(id), "analysis")
        }
        return http.decodeJson(response)
    }

    /**
     * Retry track audio
     * Try this record's copies again now, rather than when the backoff says
     */
    suspend fun retryTrackAudio(id: Uuid): TrackClearResult {
        val response = http.execute(HttpMethod.Post) {
            path("catalog", "tracks", segment(id), "retry")
        }
        return http.decodeJson(response)
    }

    /**
     * Offer track copies again
     * Put copies a provider refused back on offer, and clear their backoff so they are tried now
     */
    suspend fun offerTrackCopiesAgain(id: Uuid): TrackClearResult {
        val response = http.execute(HttpMethod.Post) {
            path("catalog", "tracks", segment(id), "offer")
        }
        return http.decodeJson(response)
    }

    /**
     * Get track enrichment
     * What the providers said about one recording, including everything no canonical column holds
     */
    suspend fun getTrackEnrichment(id: Uuid): TrackEnrichmentDetail {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "tracks", segment(id), "enrichment")
        }
        return http.decodeJson(response)
    }

    /**
     * Clear track enrichment
     * Forget what the providers said, so the enrichment pass asks again
     */
    suspend fun clearTrackEnrichment(id: Uuid, query: ClearEnrichmentQuery? = null): TrackClearResult {
        val response = http.execute(HttpMethod.Delete) {
            path("catalog", "tracks", segment(id), "enrichment")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * List tracks
     * Every track, flat. The only way to answer "do we have this song?" without knowing its artist
     */
    suspend fun listTracks(query: TrackQueryInput? = null): TrackPage {
        val response = http.execute(HttpMethod.Get) {
            path("catalog", "tracks")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Rate track
     * What the station thinks of this song, which is the narrowest thing an opinion can be about
     */
    suspend fun rateTrack(id: Uuid, body: RateInput): Track {
        val response = http.execute(HttpMethod.Put) {
            path("catalog", "tracks", segment(id), "rating")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }
}
