// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.HistoryPage
import com.maroonedsoftware.deadair.sdk.models.HistoryQuery
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `history.ck`. */
class HistoryClient(private val http: SdkHttp) {
    /**
     * Read history
     * What the station played, newest first, one page at a time
     */
    suspend fun readHistory(query: HistoryQuery? = null): HistoryPage {
        val response = http.execute(HttpMethod.Get) {
            path("history")
            params(query)
        }
        return http.decodeJson(response)
    }
}
