// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.MessagingLinkCode
import com.maroonedsoftware.deadair.sdk.models.MessagingLinkList
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `messaging.ck`. */
class MessagingClient(private val http: SdkHttp) {
    /**
     * List messaging links
     * The chat accounts linked to the signed-in account
     */
    suspend fun listMessagingLinks(): MessagingLinkList {
        val response = http.execute(HttpMethod.Get) {
            path("messaging", "links")
        }
        return http.decodeJson(response)
    }

    /**
     * Create messaging link code
     * A new one-time code for linking a chat account. It replaces any earlier code and stops working after ten minutes
     */
    suspend fun createMessagingLinkCode(): MessagingLinkCode {
        val response = http.execute(HttpMethod.Post) {
            path("messaging", "links", "code")
        }
        return http.decodeJson(response)
    }

    /**
     * Remove messaging link
     * Unlink a chat account. Its operator commands are refused from the next one on
     */
    suspend fun removeMessagingLink(pluginId: String, platformUserId: String) {
        http.execute(HttpMethod.Delete) {
            path("messaging", "links", segment(pluginId), segment(platformUserId))
        }
    }
}
