// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.OAuthAuthorizationContextResult
import com.maroonedsoftware.deadair.sdk.models.OAuthAuthorizationDecision
import com.maroonedsoftware.deadair.sdk.models.OAuthAuthorizationOutcome
import com.maroonedsoftware.deadair.sdk.models.OAuthAuthorizationQuery
import com.maroonedsoftware.deadair.sdk.models.OAuthClientCreate
import com.maroonedsoftware.deadair.sdk.models.OAuthClientIssued
import com.maroonedsoftware.deadair.sdk.models.OAuthClientList
import com.maroonedsoftware.deadair.sdk.models.OAuthGrantList
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `oauth.ck`. */
class OauthClient(private val http: SdkHttp) {
    /**
     * Describe authorization request
     * Validate an app's authorization request for the consent page, and stash it for the signed-in person. A POST because it stashes: what is approved is exactly what was validated here
     */
    suspend fun describeAuthorizationRequest(body: OAuthAuthorizationQuery): OAuthAuthorizationContextResult {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "oauth", "authorize", "context")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Approve authorization request
     * Let the app act as the signed-in person. Once the account has a strong second factor, this needs one verified in the last five minutes
     */
    suspend fun approveAuthorizationRequest(body: OAuthAuthorizationDecision): OAuthAuthorizationOutcome {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "oauth", "authorize", "approve")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Deny authorization request
     * Turn the app away. It is told the person said no
     */
    suspend fun denyAuthorizationRequest(body: OAuthAuthorizationDecision): OAuthAuthorizationOutcome {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "oauth", "authorize", "deny")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * List OAuth clients
     * Every app registered with the station, by an operator or by itself
     */
    suspend fun listOAuthClients(): OAuthClientList {
        val response = http.execute(HttpMethod.Get) {
            path("auth", "oauth", "clients")
        }
        return http.decodeJson(response)
    }

    /**
     * Create OAuth client
     * Register an app by hand. The secret, for an app that keeps one, is in this response and nowhere else
     */
    suspend fun createOAuthClient(body: OAuthClientCreate): OAuthClientIssued {
        val response = http.execute(HttpMethod.Post) {
            path("auth", "oauth", "clients")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Revoke OAuth client
     * Withdraw an app. Every person's approval of it ends, and so does every token it holds
     */
    suspend fun revokeOAuthClient(clientId: String) {
        http.execute(HttpMethod.Delete) {
            path("auth", "oauth", "clients", segment(clientId))
        }
    }

    /**
     * List OAuth grants
     * The apps the signed-in person has let act as them
     */
    suspend fun listOAuthGrants(): OAuthGrantList {
        val response = http.execute(HttpMethod.Get) {
            path("auth", "oauth", "grants")
        }
        return http.decodeJson(response)
    }

    /**
     * Revoke OAuth grant
     * Disconnect an app. Every token it holds for this person stops working at once
     */
    suspend fun revokeOAuthGrant(id: Uuid) {
        http.execute(HttpMethod.Delete) {
            path("auth", "oauth", "grants", segment(id))
        }
    }
}
