// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.GeneratedPersona
import com.maroonedsoftware.deadair.sdk.models.PersonaFile
import com.maroonedsoftware.deadair.sdk.models.PersonaImportPlan
import com.maroonedsoftware.deadair.sdk.models.PersonaImportResult
import com.maroonedsoftware.deadair.sdk.models.PersonaInput
import com.maroonedsoftware.deadair.sdk.models.PersonaList
import com.maroonedsoftware.deadair.sdk.models.PersonaNoteList
import com.maroonedsoftware.deadair.sdk.models.PersonaNoteState
import com.maroonedsoftware.deadair.sdk.models.PersonaNoteWrite
import com.maroonedsoftware.deadair.sdk.models.PersonaRehearsal
import com.maroonedsoftware.deadair.sdk.models.PersonaRequest
import com.maroonedsoftware.deadair.sdk.models.PersonaStoryDetailWrite
import com.maroonedsoftware.deadair.sdk.models.PersonaStoryList
import com.maroonedsoftware.deadair.sdk.models.PersonaStoryState
import com.maroonedsoftware.deadair.sdk.models.PersonaStoryWrite
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `personas.ck`. */
class PersonasClient(private val http: SdkHttp) {
    /**
     * List personas
     * Every persona this station has, oldest first
     */
    suspend fun listPersonas(): PersonaList {
        val response = http.execute(HttpMethod.Get) {
            path("personas")
        }
        return http.decodeJson(response)
    }

    /**
     * Create persona
     * Writes a new persona. It is not put on air by creating it
     */
    suspend fun createPersona(body: PersonaInput): PersonaList {
        val response = http.execute(HttpMethod.Post) {
            path("personas")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Generate persona
     * Turns a description of a character into a whole persona, checked against its own sample lines and handed back unsaved
     */
    suspend fun generatePersona(body: PersonaRequest): GeneratedPersona {
        val response = http.execute(HttpMethod.Post) {
            path("personas", "generate")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Restore station personas
     * Writes back whichever of the station's own personas this station is missing, touching nothing it already has and putting nothing on air
     */
    suspend fun restoreStationPersonas(): PersonaList {
        val response = http.execute(HttpMethod.Post) {
            path("personas", "restore")
        }
        return http.decodeJson(response)
    }

    /**
     * Export personas
     * Every character this station holds, as one file
     */
    suspend fun exportPersonas(): ExportPersonasResult {
        val response = http.execute(HttpMethod.Get) {
            path("personas", "export")
        }
        val headers = ExportPersonasHeaders(
            response.headers["Content-Disposition"]?.let { it },
        )
        return ExportPersonasResult(http.decodeJson(response), headers)
    }

    /**
     * Export persona
     * One character, its sheet and its stories, as a file
     * @throws SdkError on 404
     */
    suspend fun exportPersona(id: String): ExportPersonaResult {
        val response = http.execute(HttpMethod.Get) {
            path("personas", segment(id), "export")
        }
        val headers = ExportPersonaHeaders(
            response.headers["Content-Disposition"]?.let { it },
        )
        return ExportPersonaResult(http.decodeJson(response), headers)
    }

    /**
     * Preview persona import
     * Reads a file and reports what importing it would create, rewrite and skip. Writes nothing
     */
    suspend fun previewPersonaImport(body: PersonaFile): PersonaImportPlan {
        val response = http.execute(HttpMethod.Post) {
            path("personas", "import", "preview")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Import personas
     * Writes a file into this station, merging by key, and answers with what it did
     */
    suspend fun importPersonas(body: PersonaFile): PersonaImportResult {
        val response = http.execute(HttpMethod.Post) {
            path("personas", "import")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update persona
     * Rewrites one persona. An edit to the one on air is heard on the next break
     */
    suspend fun updatePersona(id: String, body: PersonaInput): PersonaList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete persona
     * Removes a persona, including the one on air, which leaves the station with none
     */
    suspend fun deletePersona(id: String): PersonaList {
        val response = http.execute(HttpMethod.Delete) {
            path("personas", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Put persona on air
     * Puts this persona on air and takes the previous one off
     */
    suspend fun putPersonaOnAir(id: String): PersonaList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "active")
        }
        return http.decodeJson(response)
    }

    /**
     * List persona notes
     * Everything this character has accumulated, oldest first, in every state
     */
    suspend fun listPersonaNotes(id: String): PersonaNoteList {
        val response = http.execute(HttpMethod.Get) {
            path("personas", segment(id), "notes")
        }
        return http.decodeJson(response)
    }

    /**
     * Write persona note
     * Writes a note by hand. An operator's own note is active from the moment it exists; only the distil pass proposes
     */
    suspend fun writePersonaNote(id: String, body: PersonaNoteWrite): PersonaNoteList {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "notes")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update persona note
     * Rewrites one note's words, whoever wrote it. Editing what the station proposed is most of the point of the panel
     */
    suspend fun updatePersonaNote(id: String, noteId: String, body: PersonaNoteWrite): PersonaNoteList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "notes", segment(noteId))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete persona note
     * Removes a note outright. Turning down a PROPOSAL is a state rather than this, or the next pass writes it again
     */
    suspend fun deletePersonaNote(id: String, noteId: String): PersonaNoteList {
        val response = http.execute(HttpMethod.Delete) {
            path("personas", segment(id), "notes", segment(noteId))
        }
        return http.decodeJson(response)
    }

    /**
     * Set persona note state
     * Accepts a proposal, turns one down, or rests an active note. Mirrors the lexicon's own state route
     */
    suspend fun setPersonaNoteState(id: String, noteId: String, body: PersonaNoteState): PersonaNoteList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "notes", segment(noteId), "state")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * List persona stories
     * Every story this character holds, oldest first, in every state
     */
    suspend fun listPersonaStories(id: String): PersonaStoryList {
        val response = http.execute(HttpMethod.Get) {
            path("personas", segment(id), "stories")
        }
        return http.decodeJson(response)
    }

    /**
     * Write persona story
     * Writes a story by hand. An operator's own is tellable from the moment it exists; only the enrichment pass proposes
     */
    suspend fun writePersonaStory(id: String, body: PersonaStoryWrite): PersonaStoryList {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "stories")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update persona story
     * Rewrites one story's handle and telling, whoever wrote it
     */
    suspend fun updatePersonaStory(id: String, storyId: String, body: PersonaStoryWrite): PersonaStoryList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "stories", segment(storyId))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete persona story
     * Removes a story outright, details and all. Turning down a PROPOSAL is a state rather than this, or the next pass writes it again
     */
    suspend fun deletePersonaStory(id: String, storyId: String): PersonaStoryList {
        val response = http.execute(HttpMethod.Delete) {
            path("personas", segment(id), "stories", segment(storyId))
        }
        return http.decodeJson(response)
    }

    /**
     * Set persona story state
     * Accepts a proposal, turns one down, or takes a story out of the rotation without losing it
     */
    suspend fun setPersonaStoryState(id: String, storyId: String, body: PersonaStoryState): PersonaStoryList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "stories", segment(storyId), "state")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Add persona story detail
     * Adds one thing to a story that already exists
     */
    suspend fun addPersonaStoryDetail(id: String, storyId: String, body: PersonaStoryDetailWrite): PersonaStoryList {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "stories", segment(storyId), "details")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update persona story detail
     * Rewrites one detail's words
     */
    suspend fun updatePersonaStoryDetail(id: String, storyId: String, detailId: String, body: PersonaStoryDetailWrite): PersonaStoryList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "stories", segment(storyId), "details", segment(detailId))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete persona story detail
     * Removes one detail, leaving the story it was hung on alone
     */
    suspend fun deletePersonaStoryDetail(id: String, storyId: String, detailId: String): PersonaStoryList {
        val response = http.execute(HttpMethod.Delete) {
            path("personas", segment(id), "stories", segment(storyId), "details", segment(detailId))
        }
        return http.decodeJson(response)
    }

    /**
     * Set persona story detail state
     * Accepts a proposed detail or turns it down, which has to outlive the pass that proposed it
     */
    suspend fun setPersonaStoryDetailState(id: String, storyId: String, detailId: String, body: PersonaStoryState): PersonaStoryList {
        val response = http.execute(HttpMethod.Put) {
            path("personas", segment(id), "stories", segment(storyId), "details", segment(detailId), "state")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Rehearse persona
     * Writes a talk break under this persona against two fixed invented records, and answers with every writer that was asked
     */
    suspend fun rehearsePersona(id: String): PersonaRehearsal {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "rehearse")
        }
        return http.decodeJson(response)
    }
}

/** Response headers declared on GET /personas/export. */
data class ExportPersonasHeaders(
    val contentDisposition: String?,
)

/** The body of GET /personas/export, with the response headers the contract declares. */
data class ExportPersonasResult(
    val data: PersonaFile,
    val headers: ExportPersonasHeaders,
)

/** Response headers declared on GET /personas/{id}/export. */
data class ExportPersonaHeaders(
    val contentDisposition: String?,
)

/** The body of GET /personas/{id}/export, with the response headers the contract declares. */
data class ExportPersonaResult(
    val data: PersonaFile,
    val headers: ExportPersonaHeaders,
)
