// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.PersonaAudition
import com.maroonedsoftware.deadair.sdk.models.PersonaAuditionList
import com.maroonedsoftware.deadair.sdk.models.PersonaAuditionRequest
import com.maroonedsoftware.deadair.sdk.models.PersonaAuditionSummary
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `personas.auditions.ck`. */
class PersonasAuditionsClient(private val http: SdkHttp) {
    /**
     * List persona auditions
     * Every audition of this character, newest first, without their breaks
     */
    suspend fun listPersonaAuditions(id: String): PersonaAuditionList {
        val response = http.execute(HttpMethod.Get) {
            path("personas", segment(id), "auditions")
        }
        return http.decodeJson(response)
    }

    /**
     * Start persona audition
     * Asks the station to put this character through a playlist. It is queued, not written
     */
    suspend fun startPersonaAudition(id: String, body: PersonaAuditionRequest): PersonaAudition {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "auditions")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Get persona audition
     * One audition with every break it has written so far, in order
     */
    suspend fun getPersonaAudition(id: String, auditionId: String): PersonaAudition {
        val response = http.execute(HttpMethod.Get) {
            path("personas", segment(id), "auditions", segment(auditionId))
        }
        return http.decodeJson(response)
    }

    /**
     * Cancel persona audition
     * Stops an audition where it stands, keeping the breaks it has already written
     */
    suspend fun cancelPersonaAudition(id: String, auditionId: String): PersonaAuditionSummary {
        val response = http.execute(HttpMethod.Post) {
            path("personas", segment(id), "auditions", segment(auditionId), "cancel")
        }
        return http.decodeJson(response)
    }
}
