// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.CatalogPlaylistPage
import com.maroonedsoftware.deadair.sdk.models.CatalogPlaylistTracks
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `playlists.ck`. */
class PlaylistsClient(private val http: SdkHttp) {
    /**
     * List importable playlists
     * Fans out across every installed plugin that declares AND implements the `catalog` capability
     */
    suspend fun listImportablePlaylists(): CatalogPlaylistPage {
        val response = http.execute(HttpMethod.Get) {
            path("playlists")
        }
        return http.decodeJson(response)
    }

    /**
     * Get playlist tracks
     * One playlist's tracks from one plugin
     */
    suspend fun getPlaylistTracks(pluginId: String, playlistId: String): CatalogPlaylistTracks {
        val response = http.execute(HttpMethod.Get) {
            path("playlists", segment(pluginId), segment(playlistId), "tracks")
        }
        return http.decodeJson(response)
    }

    /**
     * Hide playlist
     * Hides one playlist from this station: the listing marks it hidden, the pickers stop offering it and the library sync stops reading it. Hiding one already hidden changes nothing
     */
    suspend fun hidePlaylist(pluginId: String, playlistId: String) {
        http.execute(HttpMethod.Put) {
            path("playlists", segment(pluginId), segment(playlistId), "hidden")
        }
    }

    /**
     * Show playlist
     * Shows a hidden playlist again. Showing one that is not hidden changes nothing
     */
    suspend fun showPlaylist(pluginId: String, playlistId: String) {
        http.execute(HttpMethod.Delete) {
            path("playlists", segment(pluginId), segment(playlistId), "hidden")
        }
    }

    /**
     * Refresh playlists
     * Reads every playlist on every music source again, in the background, rather than waiting for the next scheduled read. New records reach the library; records gone from every playlist are retired
     */
    suspend fun refreshPlaylists() {
        http.execute(HttpMethod.Post) {
            path("playlists", "refresh")
        }
    }

    /**
     * Refresh playlist
     * Reads one playlist again, in the background. New records reach the library; a record taken out of it stays until the next full read judges it
     */
    suspend fun refreshPlaylist(pluginId: String, playlistId: String) {
        http.execute(HttpMethod.Post) {
            path("playlists", segment(pluginId), segment(playlistId), "refresh")
        }
    }
}
