// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.Production
import com.maroonedsoftware.deadair.sdk.models.ProductionList
import com.maroonedsoftware.deadair.sdk.models.ProductionRequest
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `productions.ck`. */
class ProductionsClient(private val http: SdkHttp) {
    /**
     * List productions
     * Everything the station has made or is making, newest first
     */
    suspend fun listProductions(): ProductionList {
        val response = http.execute(HttpMethod.Get) {
            path("productions")
        }
        return http.decodeJson(response)
    }

    /**
     * Request production
     * Asks the station to make one. It is queued, not started
     */
    suspend fun requestProduction(body: ProductionRequest): Production {
        val response = http.execute(HttpMethod.Post) {
            path("productions")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Cancel production
     * Stops a production being made, for good
     */
    suspend fun cancelProduction(id: String): Production {
        val response = http.execute(HttpMethod.Post) {
            path("productions", segment(id), "cancel")
        }
        return http.decodeJson(response)
    }
}
