// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.PadFetch
import com.maroonedsoftware.deadair.sdk.models.PadList
import com.maroonedsoftware.deadair.sdk.models.PadScanResult
import com.maroonedsoftware.deadair.sdk.models.PadSetMembership
import com.maroonedsoftware.deadair.sdk.models.PadSetWrite
import com.maroonedsoftware.deadair.sdk.models.PadState
import com.maroonedsoftware.deadair.sdk.models.PronunciationList
import com.maroonedsoftware.deadair.sdk.models.PronunciationQuery
import com.maroonedsoftware.deadair.sdk.models.PronunciationStateWrite
import com.maroonedsoftware.deadair.sdk.models.PronunciationWrite
import com.maroonedsoftware.deadair.sdk.models.ScriptAttempt
import com.maroonedsoftware.deadair.sdk.models.ScriptHistoryPage
import com.maroonedsoftware.deadair.sdk.models.ScriptHistoryQuery
import com.maroonedsoftware.deadair.sdk.models.ScriptHistorySummary
import com.maroonedsoftware.deadair.sdk.models.ScriptHistorySummaryQuery
import com.maroonedsoftware.deadair.sdk.models.ScriptRatingInput
import com.maroonedsoftware.deadair.sdk.models.Segment
import com.maroonedsoftware.deadair.sdk.models.SegmentCreate
import com.maroonedsoftware.deadair.sdk.models.SegmentList
import com.maroonedsoftware.deadair.sdk.models.SegmentScanResult
import com.maroonedsoftware.deadair.sdk.models.SpeechPreviewRequest
import com.maroonedsoftware.deadair.sdk.models.VoiceList
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import io.ktor.http.content.PartData
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `render.ck`. */
class RenderClient(private val http: SdkHttp) {
    /**
     * List segments
     * Everything the station can play that is not a record
     */
    suspend fun listSegments(): SegmentList {
        val response = http.execute(HttpMethod.Get) {
            path("segments")
        }
        return http.decodeJson(response)
    }

    /**
     * Create segment
     * Plans something for the station to say, and starts rendering it
     */
    suspend fun createSegment(body: SegmentCreate): Segment {
        val response = http.execute(HttpMethod.Post) {
            path("segments")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Upload segment
     * Takes a recording in from the browser and puts it in the library, ready to air
     * @throws SdkError on 400, 413, 415
     */
    suspend fun uploadSegment(body: List<PartData>): Segment {
        val response = http.execute(HttpMethod.Post) {
            path("segments", "upload")
            multipartBody(body)
        }
        return http.decodeJson(response)
    }

    /**
     * Scan the segment inbox
     * Takes whatever audio is sitting in the inbox directory into the library. Safe to repeat: a segment is identified by its audio, so the same recording arriving twice is one segment
     */
    suspend fun scanTheSegmentInbox(): SegmentScanResult {
        val response = http.execute(HttpMethod.Post) {
            path("segments", "scan")
        }
        return http.decodeJson(response)
    }

    /**
     * Read script history
     * What the station has written lately, newest first, one page at a time
     */
    suspend fun readScriptHistory(query: ScriptHistoryQuery? = null): ScriptHistoryPage {
        val response = http.execute(HttpMethod.Get) {
            path("scripts")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Rate script
     * What the operator thought of this attempt. Nothing acts on it automatically
     */
    suspend fun rateScript(id: Uuid, body: ScriptRatingInput): ScriptAttempt {
        val response = http.execute(HttpMethod.Put) {
            path("scripts", segment(id), "rating")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Read script summary
     * Write attempts by outcome, per presenter, over a recent window
     */
    suspend fun readScriptSummary(query: ScriptHistorySummaryQuery? = null): ScriptHistorySummary {
        val response = http.execute(HttpMethod.Get) {
            path("scripts", "summary")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * List voices
     * The voices the station can be asked to speak in
     */
    suspend fun listVoices(): VoiceList {
        val response = http.execute(HttpMethod.Get) {
            path("voices")
        }
        return http.decodeJson(response)
    }

    /**
     * Get default voice sample
     * A short line spoken in whichever voice the plugin falls back to
     */
    suspend fun getDefaultVoiceSample(): GetDefaultVoiceSampleResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("voices", "sample")
        }
        return when (response.status.value) {
            304 -> {
                GetDefaultVoiceSampleResponse.Status304
            }
            else -> {
                val headers = GetDefaultVoiceSample200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "audio/wav" -> GetDefaultVoiceSampleResponse.Status200AudioWav(response.bytes, headers)
                    "audio/ogg" -> GetDefaultVoiceSampleResponse.Status200AudioOgg(response.bytes, headers)
                    "audio/flac" -> GetDefaultVoiceSampleResponse.Status200AudioFlac(response.bytes, headers)
                    "audio/mp4" -> GetDefaultVoiceSampleResponse.Status200AudioMp4(response.bytes, headers)
                    else -> GetDefaultVoiceSampleResponse.Status200AudioMpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Get voice sample
     * A short line spoken in one voice, so an operator can hear it before choosing it
     */
    suspend fun getVoiceSample(voiceId: String): GetVoiceSampleResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("voices", segment(voiceId), "sample")
        }
        return when (response.status.value) {
            304 -> {
                GetVoiceSampleResponse.Status304
            }
            else -> {
                val headers = GetVoiceSample200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "audio/wav" -> GetVoiceSampleResponse.Status200AudioWav(response.bytes, headers)
                    "audio/ogg" -> GetVoiceSampleResponse.Status200AudioOgg(response.bytes, headers)
                    "audio/flac" -> GetVoiceSampleResponse.Status200AudioFlac(response.bytes, headers)
                    "audio/mp4" -> GetVoiceSampleResponse.Status200AudioMp4(response.bytes, headers)
                    else -> GetVoiceSampleResponse.Status200AudioMpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Preview speech
     * Speaks the caller's words in one voice, so a break can be heard before it is written for air
     */
    suspend fun previewSpeech(body: SpeechPreviewRequest): PreviewSpeechResponse {
        val response = http.execute(HttpMethod.Post) {
            path("voices", "preview")
            jsonBody(body, "application/json")
        }
        return when (response.contentType) {
            "audio/wav" -> PreviewSpeechResponse.AudioWav(response.bytes)
            "audio/ogg" -> PreviewSpeechResponse.AudioOgg(response.bytes)
            "audio/flac" -> PreviewSpeechResponse.AudioFlac(response.bytes)
            "audio/mp4" -> PreviewSpeechResponse.AudioMp4(response.bytes)
            else -> PreviewSpeechResponse.AudioMpeg(response.bytes)
        }
    }

    /**
     * Delete segment
     * Removes a recording and the inbox file behind it, so the next scan does not read it back in
     * @throws SdkError on 404, 409
     */
    suspend fun deleteSegment(id: Uuid): SegmentList {
        val response = http.execute(HttpMethod.Delete) {
            path("segments", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Get segment audio
     * The audio of one segment
     */
    suspend fun getSegmentAudio(id: Uuid): GetSegmentAudioResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("segments", segment(id), "audio")
        }
        return when (response.status.value) {
            304 -> {
                GetSegmentAudioResponse.Status304
            }
            else -> {
                val headers = GetSegmentAudio200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "audio/wav" -> GetSegmentAudioResponse.Status200AudioWav(response.bytes, headers)
                    "audio/ogg" -> GetSegmentAudioResponse.Status200AudioOgg(response.bytes, headers)
                    "audio/flac" -> GetSegmentAudioResponse.Status200AudioFlac(response.bytes, headers)
                    "audio/mp4" -> GetSegmentAudioResponse.Status200AudioMp4(response.bytes, headers)
                    else -> GetSegmentAudioResponse.Status200AudioMpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Get stored audio
     * Audio out of the segment store, addressed by content rather than by row
     */
    suspend fun getStoredAudio(checksum: String, ext: String): GetStoredAudioResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("audio", segment(checksum), segment(ext))
        }
        return when (response.status.value) {
            304 -> {
                GetStoredAudioResponse.Status304
            }
            else -> {
                val headers = GetStoredAudio200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "audio/wav" -> GetStoredAudioResponse.Status200AudioWav(response.bytes, headers)
                    "audio/ogg" -> GetStoredAudioResponse.Status200AudioOgg(response.bytes, headers)
                    "audio/flac" -> GetStoredAudioResponse.Status200AudioFlac(response.bytes, headers)
                    "audio/mp4" -> GetStoredAudioResponse.Status200AudioMp4(response.bytes, headers)
                    else -> GetStoredAudioResponse.Status200AudioMpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * List pronunciations
     * The station's lexicon: what it says, what has been proposed to it, and what it has turned down
     */
    suspend fun listPronunciations(query: PronunciationQuery? = null): PronunciationList {
        val response = http.execute(HttpMethod.Get) {
            path("pronunciations")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Create pronunciation
     * Adds one the operator typed. It is said from the next render on
     */
    suspend fun createPronunciation(body: PronunciationWrite): PronunciationList {
        val response = http.execute(HttpMethod.Post) {
            path("pronunciations")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update pronunciation
     * Rewrites one entry's words, whoever proposed it
     */
    suspend fun updatePronunciation(id: Uuid, body: PronunciationWrite): PronunciationList {
        val response = http.execute(HttpMethod.Put) {
            path("pronunciations", segment(id))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete pronunciation
     * Removes an entry outright. Turning a PROPOSAL down is a state rather than a deletion, because a deleted one comes back on the next pass
     */
    suspend fun deletePronunciation(id: Uuid): PronunciationList {
        val response = http.execute(HttpMethod.Delete) {
            path("pronunciations", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Set pronunciation state
     * Accepts a proposal, turns one down, or takes an entry out of use without losing what it said
     */
    suspend fun setPronunciationState(id: Uuid, body: PronunciationStateWrite): PronunciationList {
        val response = http.execute(HttpMethod.Put) {
            path("pronunciations", segment(id), "state")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * List pads
     * Every sound the station holds, board by board
     */
    suspend fun listPads(): PadList {
        val response = http.execute(HttpMethod.Get) {
            path("pads")
        }
        return http.decodeJson(response)
    }

    /**
     * Upload pad
     * Takes a sound in from the browser and puts it on a board. The file lands in the pad library on disk, so it survives a rebuild and an archive carries it
     * @throws SdkError on 400, 409, 413, 415
     */
    suspend fun uploadPad(body: List<PartData>): PadList {
        val response = http.execute(HttpMethod.Post) {
            path("pads")
            multipartBody(body)
        }
        return http.decodeJson(response)
    }

    /**
     * Scan the pad library
     * Takes whatever audio is sitting in the pad library directory onto its board. Safe to repeat: a file nobody has touched is seen and left alone
     */
    suspend fun scanThePadLibrary(): PadScanResult {
        val response = http.execute(HttpMethod.Post) {
            path("pads", "scan")
        }
        return http.decodeJson(response)
    }

    /**
     * Fetch pad
     * Fetches a sound from an address and puts it on a board. The operator names the address, so this is them choosing a file exactly as dropping one in the library is
     * @throws SdkError on 400, 409, 413, 415, 502
     */
    suspend fun fetchPad(body: PadFetch): PadList {
        val response = http.execute(HttpMethod.Post) {
            path("pads", "fetch")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete pad
     * Removes a sound the console put there, and the file it wrote for it
     * @throws SdkError on 404, 409
     */
    suspend fun deletePad(id: Uuid): PadList {
        val response = http.execute(HttpMethod.Delete) {
            path("pads", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Set pad state
     * Turns a sound down, or puts one back. Answers the whole rack, since one pad changing state is one row moving between two sections of the same page
     */
    suspend fun setPadState(id: Uuid, body: PadState): PadList {
        val response = http.execute(HttpMethod.Put) {
            path("pads", segment(id), "state")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Get pad audio
     * The sound itself, so an operator can hear what they dropped in
     */
    suspend fun getPadAudio(id: Uuid): GetPadAudioResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(304)) {
            path("pads", segment(id), "audio")
        }
        return when (response.status.value) {
            304 -> {
                GetPadAudioResponse.Status304
            }
            else -> {
                val headers = GetPadAudio200Headers(
                    response.headers["cache-control"]?.let { it },
                    response.headers["etag"]?.let { it },
                )
                when (response.contentType) {
                    "audio/wav" -> GetPadAudioResponse.Status200AudioWav(response.bytes, headers)
                    "audio/ogg" -> GetPadAudioResponse.Status200AudioOgg(response.bytes, headers)
                    "audio/flac" -> GetPadAudioResponse.Status200AudioFlac(response.bytes, headers)
                    "audio/mp4" -> GetPadAudioResponse.Status200AudioMp4(response.bytes, headers)
                    else -> GetPadAudioResponse.Status200AudioMpeg(response.bytes, headers)
                }
            }
        }
    }

    /**
     * Create pad set
     * Names a new set, or answers the one already under that key
     */
    suspend fun createPadSet(body: PadSetWrite): PadList {
        val response = http.execute(HttpMethod.Post) {
            path("pads", "sets")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Update pad set
     * Renames a set. The KEY moves with it, so every persona naming the old one stops finding it
     */
    suspend fun updatePadSet(id: Uuid, body: PadSetWrite): PadList {
        val response = http.execute(HttpMethod.Put) {
            path("pads", "sets", segment(id))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete pad set
     * Removes a set and its memberships, and no pads at all
     */
    suspend fun deletePadSet(id: Uuid): PadList {
        val response = http.execute(HttpMethod.Delete) {
            path("pads", "sets", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Set pad membership
     * Puts a pad on a set or takes it off. Refused where the set already answers to that name, because a script writes a name
     */
    suspend fun setPadMembership(id: Uuid, body: PadSetMembership): PadList {
        val response = http.execute(HttpMethod.Put) {
            path("pads", "sets", segment(id), "pads")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }
}

/** Response headers declared on GET /voices/sample. */
data class GetDefaultVoiceSample200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /voices/sample returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetDefaultVoiceSampleResponse {
    data class Status200AudioMpeg(
        val data: ByteArray,
    val headers: GetDefaultVoiceSample200Headers,
    ) : GetDefaultVoiceSampleResponse
    data class Status200AudioWav(
        val data: ByteArray,
    val headers: GetDefaultVoiceSample200Headers,
    ) : GetDefaultVoiceSampleResponse
    data class Status200AudioOgg(
        val data: ByteArray,
    val headers: GetDefaultVoiceSample200Headers,
    ) : GetDefaultVoiceSampleResponse
    data class Status200AudioFlac(
        val data: ByteArray,
    val headers: GetDefaultVoiceSample200Headers,
    ) : GetDefaultVoiceSampleResponse
    data class Status200AudioMp4(
        val data: ByteArray,
    val headers: GetDefaultVoiceSample200Headers,
    ) : GetDefaultVoiceSampleResponse
    data object Status304 : GetDefaultVoiceSampleResponse
}

/** Response headers declared on GET /voices/{voiceId}/sample. */
data class GetVoiceSample200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /voices/{voiceId}/sample returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetVoiceSampleResponse {
    data class Status200AudioMpeg(
        val data: ByteArray,
    val headers: GetVoiceSample200Headers,
    ) : GetVoiceSampleResponse
    data class Status200AudioWav(
        val data: ByteArray,
    val headers: GetVoiceSample200Headers,
    ) : GetVoiceSampleResponse
    data class Status200AudioOgg(
        val data: ByteArray,
    val headers: GetVoiceSample200Headers,
    ) : GetVoiceSampleResponse
    data class Status200AudioFlac(
        val data: ByteArray,
    val headers: GetVoiceSample200Headers,
    ) : GetVoiceSampleResponse
    data class Status200AudioMp4(
        val data: ByteArray,
    val headers: GetVoiceSample200Headers,
    ) : GetVoiceSampleResponse
    data object Status304 : GetVoiceSampleResponse
}

/**
 * What POST /voices/preview returned.
 *
 * The status declares several content types, so which one arrived is part of the value.
 */
sealed interface PreviewSpeechResponse {
    data class AudioMpeg(
        val data: ByteArray,
    ) : PreviewSpeechResponse
    data class AudioWav(
        val data: ByteArray,
    ) : PreviewSpeechResponse
    data class AudioOgg(
        val data: ByteArray,
    ) : PreviewSpeechResponse
    data class AudioFlac(
        val data: ByteArray,
    ) : PreviewSpeechResponse
    data class AudioMp4(
        val data: ByteArray,
    ) : PreviewSpeechResponse
}

/** Response headers declared on GET /segments/{id}/audio. */
data class GetSegmentAudio200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /segments/{id}/audio returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetSegmentAudioResponse {
    data class Status200AudioMpeg(
        val data: ByteArray,
    val headers: GetSegmentAudio200Headers,
    ) : GetSegmentAudioResponse
    data class Status200AudioWav(
        val data: ByteArray,
    val headers: GetSegmentAudio200Headers,
    ) : GetSegmentAudioResponse
    data class Status200AudioOgg(
        val data: ByteArray,
    val headers: GetSegmentAudio200Headers,
    ) : GetSegmentAudioResponse
    data class Status200AudioFlac(
        val data: ByteArray,
    val headers: GetSegmentAudio200Headers,
    ) : GetSegmentAudioResponse
    data class Status200AudioMp4(
        val data: ByteArray,
    val headers: GetSegmentAudio200Headers,
    ) : GetSegmentAudioResponse
    data object Status304 : GetSegmentAudioResponse
}

/** Response headers declared on GET /audio/{checksum}/{ext}. */
data class GetStoredAudio200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /audio/{checksum}/{ext} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetStoredAudioResponse {
    data class Status200AudioMpeg(
        val data: ByteArray,
    val headers: GetStoredAudio200Headers,
    ) : GetStoredAudioResponse
    data class Status200AudioWav(
        val data: ByteArray,
    val headers: GetStoredAudio200Headers,
    ) : GetStoredAudioResponse
    data class Status200AudioOgg(
        val data: ByteArray,
    val headers: GetStoredAudio200Headers,
    ) : GetStoredAudioResponse
    data class Status200AudioFlac(
        val data: ByteArray,
    val headers: GetStoredAudio200Headers,
    ) : GetStoredAudioResponse
    data class Status200AudioMp4(
        val data: ByteArray,
    val headers: GetStoredAudio200Headers,
    ) : GetStoredAudioResponse
    data object Status304 : GetStoredAudioResponse
}

/** Response headers declared on GET /pads/{id}/audio. */
data class GetPadAudio200Headers(
    val cacheControl: String?,
    val etag: String?,
)

/**
 * What GET /pads/{id}/audio returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetPadAudioResponse {
    data class Status200AudioMpeg(
        val data: ByteArray,
    val headers: GetPadAudio200Headers,
    ) : GetPadAudioResponse
    data class Status200AudioWav(
        val data: ByteArray,
    val headers: GetPadAudio200Headers,
    ) : GetPadAudioResponse
    data class Status200AudioOgg(
        val data: ByteArray,
    val headers: GetPadAudio200Headers,
    ) : GetPadAudioResponse
    data class Status200AudioFlac(
        val data: ByteArray,
    val headers: GetPadAudio200Headers,
    ) : GetPadAudioResponse
    data class Status200AudioMp4(
        val data: ByteArray,
    val headers: GetPadAudio200Headers,
    ) : GetPadAudioResponse
    data object Status304 : GetPadAudioResponse
}
