// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.ScheduleNow
import com.maroonedsoftware.deadair.sdk.models.ScheduleSlotInput
import com.maroonedsoftware.deadair.sdk.models.ScheduleSlotList
import com.maroonedsoftware.deadair.sdk.models.ScheduleTimetable
import com.maroonedsoftware.deadair.sdk.models.ScheduleTimetableQuery
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod

/** Operations declared in `schedule.ck`. */
class ScheduleClient(private val http: SdkHttp) {
    /**
     * List schedule
     * Every slot in this station's schedule, earliest in the day first
     */
    suspend fun listSchedule(): ScheduleSlotList {
        val response = http.execute(HttpMethod.Get) {
            path("schedule")
        }
        return http.decodeJson(response)
    }

    /**
     * Create schedule slot
     * Adds a slot. The station does not change over until its start time comes round
     */
    suspend fun createScheduleSlot(body: ScheduleSlotInput): ScheduleSlotList {
        val response = http.execute(HttpMethod.Post) {
            path("schedule")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Read current slot
     * Which slot the clock says should be on, and which one the station is actually airing
     */
    suspend fun readCurrentSlot(): ScheduleNow {
        val response = http.execute(HttpMethod.Get) {
            path("schedule", "current")
        }
        return http.decodeJson(response)
    }

    /**
     * Read timetable
     * The station's day as blocks, contiguous and gapless, for drawing
     */
    suspend fun readTimetable(query: ScheduleTimetableQuery? = null): ScheduleTimetable {
        val response = http.execute(HttpMethod.Get) {
            path("schedule", "timetable")
            params(query)
        }
        return http.decodeJson(response)
    }

    /**
     * Update schedule slot
     * Rewrites a slot. Takes effect at its next boundary rather than immediately
     */
    suspend fun updateScheduleSlot(id: String, body: ScheduleSlotInput): ScheduleSlotList {
        val response = http.execute(HttpMethod.Put) {
            path("schedule", segment(id))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete schedule slot
     * Removes a slot. Whatever is on air stays on until the next slot begins
     */
    suspend fun deleteScheduleSlot(id: String): ScheduleSlotList {
        val response = http.execute(HttpMethod.Delete) {
            path("schedule", segment(id))
        }
        return http.decodeJson(response)
    }
}
