// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.maroonedsoftware.deadair.sdk.clients

import com.maroonedsoftware.deadair.sdk.models.PlaylistFile
import com.maroonedsoftware.deadair.sdk.models.PlaylistImportInput
import com.maroonedsoftware.deadair.sdk.models.PlaylistImportPlan
import com.maroonedsoftware.deadair.sdk.models.PlaylistImportResult
import com.maroonedsoftware.deadair.sdk.models.StationPlaylist
import com.maroonedsoftware.deadair.sdk.models.StationPlaylistDetail
import com.maroonedsoftware.deadair.sdk.models.StationPlaylistList
import com.maroonedsoftware.deadair.sdk.models.StationPlaylistUpdate
import com.maroonedsoftware.deadair.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `station.playlists.ck`. */
class StationPlaylistsClient(private val http: SdkHttp) {
    /**
     * List station playlists
     * Every playlist the station owns, newest first
     */
    suspend fun listStationPlaylists(): StationPlaylistList {
        val response = http.execute(HttpMethod.Get) {
            path("station-playlists")
        }
        return http.decodeJson(response)
    }

    /**
     * Get station playlist
     * One station playlist with its records in order, placeholders included
     * @throws SdkError on 404
     */
    suspend fun getStationPlaylist(id: Uuid): StationPlaylistDetail {
        val response = http.execute(HttpMethod.Get) {
            path("station-playlists", segment(id))
        }
        return http.decodeJson(response)
    }

    /**
     * Update station playlist
     * Renames a station playlist, or rewrites what it is for
     * @throws SdkError on 404
     */
    suspend fun updateStationPlaylist(id: Uuid, body: StationPlaylistUpdate): StationPlaylist {
        val response = http.execute(HttpMethod.Patch) {
            path("station-playlists", segment(id))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Delete station playlist
     * Deletes a station playlist. The records it named stay in the library
     * @throws SdkError on 404
     */
    suspend fun deleteStationPlaylist(id: Uuid) {
        http.execute(HttpMethod.Delete) {
            path("station-playlists", segment(id))
        }
    }

    /**
     * Fill station playlist
     * Looks up the records this playlist names and the library does not hold, in the background, and adds the ones a provider has. The activity feed says how it went
     * @throws SdkError on 404
     */
    suspend fun fillStationPlaylist(id: Uuid) {
        http.execute(HttpMethod.Post) {
            path("station-playlists", segment(id), "fill")
        }
    }

    /**
     * Export station playlist
     * One station playlist as a file another station can import
     * @throws SdkError on 404
     */
    suspend fun exportStationPlaylist(id: Uuid): ExportStationPlaylistResult {
        val response = http.execute(HttpMethod.Get) {
            path("station-playlists", segment(id), "export")
        }
        val headers = ExportStationPlaylistHeaders(
            response.headers["Content-Disposition"]?.let { it },
        )
        return ExportStationPlaylistResult(http.decodeJson(response), headers)
    }

    /**
     * Preview playlist import
     * Reads a source and reports which of its records the library holds and which it would have to find. Writes nothing
     */
    suspend fun previewPlaylistImport(body: PlaylistImportInput): PlaylistImportPlan {
        val response = http.execute(HttpMethod.Post) {
            path("station-playlists", "import", "preview")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /**
     * Import playlist
     * Makes a new station playlist from a source and answers with what it did
     */
    suspend fun importPlaylist(body: PlaylistImportInput): PlaylistImportResult {
        val response = http.execute(HttpMethod.Post) {
            path("station-playlists", "import")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }
}

/** Response headers declared on GET /station-playlists/{id}/export. */
data class ExportStationPlaylistHeaders(
    val contentDisposition: String?,
)

/** The body of GET /station-playlists/{id}/export, with the response headers the contract declares. */
data class ExportStationPlaylistResult(
    val data: PlaylistFile,
    val headers: ExportStationPlaylistHeaders,
)
