// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>Something the station can read out, as one installed plugin describes it</summary>
public sealed record StationSeries
{
    /// <summary>Unique across the station: the plugin's own id for the series, qualified with the plugin that offered it</summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("pluginId")]
    public required string PluginId { get; init; }

    /// <summary>What the series is called, which is what a presenter says out loud</summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>How it is worked through: `serial` from the beginning in order, `latest` its newest piece and nothing once that has aired</summary>
    [JsonPropertyName("order")]
    public required StationSeriesOrder Order { get; init; }

    [JsonPropertyName("author")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Author { get; init; }

    /// <summary>What the series says about itself, as plain text</summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    [JsonPropertyName("artworkUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ArtworkUrl { get; init; }

    [JsonPropertyName("homeUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? HomeUrl { get; init; }

    /// <summary>ISO 639-1, or the source's own tag. Also what the station splits sentences by when it cuts a long piece up</summary>
    [JsonPropertyName("language")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Language { get; init; }
}

/// <summary>One instalment, and what the station has done with it</summary>
public sealed record StationPiece
{
    /// <summary>The station's own id for this piece</summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>Qualified, matching `StationSeries.id`</summary>
    [JsonPropertyName("seriesId")]
    public required string SeriesId { get; init; }

    /// <summary>The plugin's own id for the piece, stable across refreshes</summary>
    [JsonPropertyName("pieceId")]
    public required string PieceId { get; init; }

    [JsonPropertyName("seriesTitle")]
    public required string SeriesTitle { get; init; }

    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>How its series is worked through, copied onto the piece by every refresh</summary>
    [JsonPropertyName("order")]
    public required StationPieceOrder Order { get; init; }

    [JsonPropertyName("author")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Author { get; init; }

    /// <summary>What it is about, as plain text</summary>
    [JsonPropertyName("summary")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Summary { get; init; }

    /// <summary>The piece's page, for a person</summary>
    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Url { get; init; }

    [JsonPropertyName("artworkUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ArtworkUrl { get; init; }

    /// <summary>Where it comes in a serial, from 0. Absent for a `latest` series</summary>
    [JsonPropertyName("ordinal")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Ordinal { get; init; }

    /// <summary>ISO-8601</summary>
    [JsonPropertyName("publishedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PublishedAt { get; init; }

    /// <summary>Roughly how many words it runs to, as the plugin counted them</summary>
    [JsonPropertyName("wordCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? WordCount { get; init; }

    /// <summary>ISO-8601: when a refresh last saw it listed</summary>
    [JsonPropertyName("seenAt")]
    public required string SeenAt { get; init; }

    /// <summary>ISO-8601: when a refresh found its plugin no longer listing it. The station never picks a withdrawn piece; the row is kept so what was done with it is not lost</summary>
    [JsonPropertyName("withdrawnAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? WithdrawnAt { get; init; }

    /// <summary>Whether the station has the spoken audio, ready to air</summary>
    [JsonPropertyName("rendered")]
    public required bool Rendered { get; init; }

    /// <summary>Whether the words are being spoken right now</summary>
    [JsonPropertyName("rendering")]
    public required bool Rendering { get; init; }

    /// <summary>ISO-8601: when the station last asked for it to be spoken</summary>
    [JsonPropertyName("renderRequestedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RenderRequestedAt { get; init; }

    /// <summary>Why the last attempt to speak it failed, when it did</summary>
    [JsonPropertyName("renderError")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RenderError { get; init; }

    /// <summary>ISO-8601: the slot it was made for</summary>
    [JsonPropertyName("scheduledFor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ScheduledFor { get; init; }

    /// <summary>ISO-8601: when a listener could first have heard it. A piece airs once, and for a serial this is also the station's place in the book</summary>
    [JsonPropertyName("airedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AiredAt { get; init; }
}

public sealed record StationPieceQuery
{
    /// <summary>One series' pieces in its own order, or absent for every series' newest first</summary>
    [JsonPropertyName("seriesId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SeriesId { get; init; }

    [JsonPropertyName("limit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Limit { get; init; }
}

public sealed record StationSeriesList
{
    [JsonPropertyName("series")]
    public required List<StationSeries> Series { get; init; }
}

public sealed record StationPiecePage
{
    /// <summary>Empty when the station knows of none, which is not an error</summary>
    [JsonPropertyName("pieces")]
    public required List<StationPiece> Pieces { get; init; }
}

/// <summary>How it is worked through: `serial` from the beginning in order, `latest` its newest piece and nothing once that has aired</summary>
[JsonConverter(typeof(JsonStringEnumConverter<StationSeriesOrder>))]
public enum StationSeriesOrder
{
    [JsonStringEnumMemberName("serial")]
    Serial,

    [JsonStringEnumMemberName("latest")]
    Latest,
}

/// <summary>How its series is worked through, copied onto the piece by every refresh</summary>
[JsonConverter(typeof(JsonStringEnumConverter<StationPieceOrder>))]
public enum StationPieceOrder
{
    [JsonStringEnumMemberName("serial")]
    Serial,

    [JsonStringEnumMemberName("latest")]
    Latest,
}
