// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>An app's authorization request, as the consent page received it</summary>
public sealed record OAuthAuthorizationQuery
{
    /// <summary>The query string the app sent the browser to the consent page with, as `window.location.search` holds it</summary>
    [JsonPropertyName("query")]
    public required string Query { get; init; }
}

/// <summary>How the station knows an app: registered by an operator, registered by itself, or described by a document on its own website</summary>
[JsonConverter(typeof(JsonStringEnumConverter<OAuthClientKind>))]
public enum OAuthClientKind
{
    [JsonStringEnumMemberName("preregistered")]
    Preregistered,

    [JsonStringEnumMemberName("dynamic")]
    Dynamic,

    [JsonStringEnumMemberName("metadata_document")]
    MetadataDocument,
}

/// <summary>A request with something wrong that the app should be told about: send the browser back to it</summary>
public sealed record OAuthAuthorizationRedirect : OAuthAuthorizationContextResult
{
    /// <summary>Discriminator</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = "redirect";

    /// <summary>Where to send the browser</summary>
    [JsonPropertyName("redirectUrl")]
    public required string RedirectUrl { get; init; }
}

/// <summary>A request that names no app the station knows, or an address the app did not register. Never sent anywhere</summary>
public sealed record OAuthAuthorizationRefusal : OAuthAuthorizationContextResult
{
    /// <summary>Discriminator</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = "refuse";

    /// <summary>The OAuth error code</summary>
    [JsonPropertyName("error")]
    public required string Error { get; init; }

    /// <summary>What was wrong, in words</summary>
    [JsonPropertyName("description")]
    public required string Description { get; init; }
}

/// <summary>Approving or denying a stashed request</summary>
public sealed record OAuthAuthorizationDecision
{
    /// <summary>From the context</summary>
    [JsonPropertyName("requestId")]
    public required string RequestId { get; init; }
}

/// <summary>Where to send the browser now</summary>
public sealed record OAuthAuthorizationOutcome
{
    /// <summary>The app's own address, carrying the code or the refusal</summary>
    [JsonPropertyName("redirectUrl")]
    public required string RedirectUrl { get; init; }
}

/// <summary>How the app proves itself at the token endpoint. `none` is a public client, which is what apps on somebody's own device are</summary>
[JsonConverter(typeof(JsonStringEnumConverter<OAuthClientAuthMethod>))]
public enum OAuthClientAuthMethod
{
    [JsonStringEnumMemberName("none")]
    None,

    [JsonStringEnumMemberName("client_secret_post")]
    ClientSecretPost,

    [JsonStringEnumMemberName("client_secret_basic")]
    ClientSecretBasic,
}

/// <summary>An app the signed-in person has let act as them</summary>
public sealed record OAuthGrant
{
    /// <summary>For disconnecting it</summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>The app's client id</summary>
    [JsonPropertyName("clientId")]
    public required string ClientId { get; init; }

    /// <summary>What the app calls itself, when the station can still find out</summary>
    [JsonPropertyName("clientName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ClientName { get; init; }

    /// <summary>What it can reach</summary>
    [JsonPropertyName("resource")]
    public required string Resource { get; init; }

    /// <summary>What it asked for</summary>
    [JsonPropertyName("scope")]
    public required List<string> Scope { get; init; }

    /// <summary>When it was first approved</summary>
    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>When it last obtained a token</summary>
    [JsonPropertyName("lastUsedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? LastUsedAt { get; init; }
}

/// <summary>A valid request, stashed for the signed-in person to approve or deny</summary>
public sealed record OAuthAuthorizationContext : OAuthAuthorizationContextResult
{
    /// <summary>Discriminator</summary>
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = "context";

    /// <summary>What approving or denying names. Good for a few minutes, and only for the person it was shown to</summary>
    [JsonPropertyName("requestId")]
    public required string RequestId { get; init; }

    /// <summary>The app's client id</summary>
    [JsonPropertyName("clientId")]
    public required string ClientId { get; init; }

    /// <summary>How the station knows the app</summary>
    [JsonPropertyName("clientKind")]
    public required OAuthClientKind ClientKind { get; init; }

    /// <summary>What the app calls itself</summary>
    [JsonPropertyName("clientName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ClientName { get; init; }

    /// <summary>The app's own website, when it gave one</summary>
    [JsonPropertyName("clientUri")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ClientUri { get; init; }

    /// <summary>The app's logo, when it gave one</summary>
    [JsonPropertyName("logoUri")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LogoUri { get; init; }

    /// <summary>The host the browser is sent back to, which is who actually receives the approval</summary>
    [JsonPropertyName("redirectHost")]
    public required string RedirectHost { get; init; }

    /// <summary>Whether every address the app registered is this computer's own, which only an app running on it should use</summary>
    [JsonPropertyName("loopbackOnly")]
    public required bool LoopbackOnly { get; init; }

    /// <summary>What the app asked for. It acts as the person approving it whatever this says</summary>
    [JsonPropertyName("scope")]
    public required List<string> Scope { get; init; }

    /// <summary>What the app will be able to reach: the station's MCP endpoint</summary>
    [JsonPropertyName("resource")]
    public required string Resource { get; init; }
}

/// <summary>An app registered with the station</summary>
public sealed record OAuthClientSummary
{
    /// <summary>Its client id</summary>
    [JsonPropertyName("clientId")]
    public required string ClientId { get; init; }

    /// <summary>Created by an operator, or registered by itself</summary>
    [JsonPropertyName("kind")]
    public required OAuthClientSummaryKind Kind { get; init; }

    /// <summary>What it is called</summary>
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }

    /// <summary>Where it may be sent back to</summary>
    [JsonPropertyName("redirectUris")]
    public required List<string> RedirectUris { get; init; }

    /// <summary>How it proves itself</summary>
    [JsonPropertyName("tokenEndpointAuthMethod")]
    public required OAuthClientAuthMethod TokenEndpointAuthMethod { get; init; }

    /// <summary>When it was registered</summary>
    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>When it last obtained a token</summary>
    [JsonPropertyName("lastUsedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? LastUsedAt { get; init; }

    /// <summary>When a self-registered app lapses unless used again</summary>
    [JsonPropertyName("expiresAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? ExpiresAt { get; init; }
}

/// <summary>An app an operator registers by hand, for a client that cannot register itself</summary>
public sealed record OAuthClientCreate
{
    /// <summary>What to call it</summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>Where it may be sent back to. At least one; https, or this computer's own address</summary>
    [JsonPropertyName("redirectUris")]
    public required List<string> RedirectUris { get; init; }

    /// <summary>`none` for an app on somebody's own device, otherwise a secret it keeps</summary>
    [JsonPropertyName("tokenEndpointAuthMethod")]
    public required OAuthClientAuthMethod TokenEndpointAuthMethod { get; init; }
}

public sealed record OAuthGrantList
{
    /// <summary>Most recent first</summary>
    [JsonPropertyName("grants")]
    public required List<OAuthGrant> Grants { get; init; }
}

public sealed record OAuthClientList
{
    /// <summary>Newest first. Apps that describe themselves are not listed: nothing is stored for them</summary>
    [JsonPropertyName("clients")]
    public required List<OAuthClientSummary> Clients { get; init; }
}

/// <summary>A registered app, with its secret. The only time the secret is ever returned</summary>
public sealed record OAuthClientIssued
{
    /// <summary>The app as it will appear in the list</summary>
    [JsonPropertyName("client")]
    public required OAuthClientSummary Client { get; init; }

    /// <summary>Present for an app that keeps a secret. Store it now: nothing can show it again</summary>
    [JsonPropertyName("clientSecret")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ClientSecret { get; init; }
}

[JsonConverter(typeof(OAuthAuthorizationContextResultConverter))]
public interface OAuthAuthorizationContextResult
{
}

/// <summary>Reads <see cref="OAuthAuthorizationContextResult"/> by dispatching on its 'kind' tag.</summary>
public sealed class OAuthAuthorizationContextResultConverter : JsonConverter<OAuthAuthorizationContextResult>
{
    public override OAuthAuthorizationContextResult Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;
        var tag = element.TryGetProperty("kind", out var tagElement) && tagElement.ValueKind == JsonValueKind.String
            ? tagElement.GetString()
            : null;

        return tag switch
        {
            "context" => element.Deserialize<OAuthAuthorizationContext>(options)!,
            "redirect" => element.Deserialize<OAuthAuthorizationRedirect>(options)!,
            "refuse" => element.Deserialize<OAuthAuthorizationRefusal>(options)!,
            _ => throw new JsonException($"Unknown OAuthAuthorizationContextResult kind: {tag}"),
        };
    }

    public override void Write(Utf8JsonWriter writer, OAuthAuthorizationContextResult value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case OAuthAuthorizationContext member:
                JsonSerializer.Serialize(writer, member, options);
                break;
            case OAuthAuthorizationRedirect member:
                JsonSerializer.Serialize(writer, member, options);
                break;
            case OAuthAuthorizationRefusal member:
                JsonSerializer.Serialize(writer, member, options);
                break;
            default:
                throw new JsonException($"Unknown OAuthAuthorizationContextResult member {value.GetType().Name}.");
        }
    }
}

/// <summary>Created by an operator, or registered by itself</summary>
[JsonConverter(typeof(JsonStringEnumConverter<OAuthClientSummaryKind>))]
public enum OAuthClientSummaryKind
{
    [JsonStringEnumMemberName("preregistered")]
    Preregistered,

    [JsonStringEnumMemberName("dynamic")]
    Dynamic,
}
