// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>The plugin playlist to load into the running order</summary>
public sealed record PlayoutPlaylistInput
{
    [JsonPropertyName("pluginId")]
    public required string PluginId { get; init; }

    [JsonPropertyName("playlistId")]
    public required string PlaylistId { get; init; }
}

/// <summary>The published chart to build the running order from</summary>
public sealed record PlayoutChartInput
{
    /// <summary>As `pluginId:chartId`, which is how `GET /charts` lists them</summary>
    [JsonPropertyName("chartId")]
    public required string ChartId { get; init; }

    /// <summary>Which way round to play it. Absent is `countdown`, which opens on the lowest rank and ends on number one</summary>
    [JsonPropertyName("chartOrder")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlayoutChartInputChartOrder? ChartOrder { get; init; }
}

/// <summary>One item in the running order, as the console sees it</summary>
public sealed record PlayoutItem
{
    /// <summary>deadair's own id for this item, not the provider's: a playlist may hold the same track twice</summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("pluginId")]
    public required string PluginId { get; init; }

    /// <summary>The track's id in its plugin's id space</summary>
    [JsonPropertyName("externalId")]
    public required string ExternalId { get; init; }

    [JsonPropertyName("title")]
    public required string Title { get; init; }

    [JsonPropertyName("artists")]
    public required List<string> Artists { get; init; }

    /// <summary>Integer milliseconds. Deliberately not the `duration` scalar, which is a Luxon `Duration` over an ISO-8601 string</summary>
    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DurationMs { get; init; }

    [JsonPropertyName("album")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Album { get; init; }

    /// <summary>The locally cached cover where there is one, the provider's URL otherwise</summary>
    [JsonPropertyName("artworkUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ArtworkUrl { get; init; }

    /// <summary>First release year, when the catalog knows one</summary>
    [JsonPropertyName("year")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Year { get; init; }

    /// <summary>The canonical `deadair.tracks` id, when this item is a track the catalog holds. Absent for anything the catalog has never seen</summary>
    [JsonPropertyName("trackId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TrackId { get; init; }
}

/// <summary>
/// A stream container still running config the app has replaced. Icecast and Liquidsoap read
/// their rendered config ONCE, at startup, and nothing restarts or signals them when it is
/// re-rendered — so a reseeded secret leaves a process holding credentials that match nothing,
/// and the symptom names something else entirely (every listener refused, or no mount at all).
/// The app cannot restart a sibling container and should not be able to, so it reports.
/// </summary>
public sealed record StreamConfigWarning
{
    /// <summary>Which one is behind</summary>
    [JsonPropertyName("container")]
    public required StreamConfigWarningContainer Container { get; init; }

    /// <summary>What is wrong and how it is known, in a sentence</summary>
    [JsonPropertyName("detail")]
    public required string Detail { get; init; }

    /// <summary>The exact command that adopts the new config, which is the only thing that does</summary>
    [JsonPropertyName("restart")]
    public required string Restart { get; init; }
}

/// <summary>
/// Which gate is keeping the station quiet, or `airing` when none of them is. Ordered by cause: a
/// stalled transport loop makes every reading under it stale, so it is ruled out first
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<SilenceCause>))]
public enum SilenceCause
{
    [JsonStringEnumMemberName("airing")]
    Airing,

    [JsonStringEnumMemberName("transportStalled")]
    TransportStalled,

    [JsonStringEnumMemberName("controlDenied")]
    ControlDenied,

    [JsonStringEnumMemberName("streamUnreachable")]
    StreamUnreachable,

    [JsonStringEnumMemberName("configNotAdopted")]
    ConfigNotAdopted,

    [JsonStringEnumMemberName("stoodDown")]
    StoodDown,

    [JsonStringEnumMemberName("noProgramme")]
    NoProgramme,

    [JsonStringEnumMemberName("noAudience")]
    NoAudience,

    [JsonStringEnumMemberName("warmingUp")]
    WarmingUp,

    [JsonStringEnumMemberName("waitingOnAudio")]
    WaitingOnAudio,

    [JsonStringEnumMemberName("notDriving")]
    NotDriving,

    [JsonStringEnumMemberName("starved")]
    Starved,
}

/// <summary>
/// How one gate is doing. `waiting` is its own state rather than a mild fault, because a station
/// idling for want of a listener and a station that cannot reach its stream are both silent and only
/// one of them is something to go and fix
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<SilenceState>))]
public enum SilenceState
{
    [JsonStringEnumMemberName("ok")]
    Ok,

    [JsonStringEnumMemberName("waiting")]
    Waiting,

    [JsonStringEnumMemberName("fault")]
    Fault,
}

/// <summary>One mount the station is publishing right now</summary>
public sealed record PlayoutMount
{
    [JsonPropertyName("format")]
    public required PlayoutMountFormat Format { get; init; }

    /// <summary>Same-origin path, on the same terms as `PlayoutStatus.mountPath`</summary>
    [JsonPropertyName("path")]
    public required string Path { get; init; }

    /// <summary>Absent for FLAC, which is lossless and has no rate to set</summary>
    [JsonPropertyName("bitrateKbps")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? BitrateKbps { get; init; }
}

/// <summary>Which rundown item Liquidsoap has just started playing</summary>
public sealed record PlayoutAiredQuery
{
    /// <summary>The id the app put on the pushed uri's `annotate:` metadata</summary>
    [JsonPropertyName("item")]
    public required string Item { get; init; }
}

/// <summary>Which way the running order went, and how long it had been that way</summary>
public sealed record PlayoutStarveQuery
{
    /// <summary>`starved`: the queue stopped producing while deadair was driving, so the mount fell through to the local bed. `recovered`: it is producing again</summary>
    [JsonPropertyName("state")]
    public required PlayoutStarveQueryState State { get; init; }

    /// <summary>How long the PREVIOUS state lasted, in milliseconds. On a recovery this is the length of the gap, which is the number worth reading</summary>
    [JsonPropertyName("forMs")]
    public required long ForMs { get; init; }
}

/// <summary>What the PLAYER says is airing, which is not the same as what was last handed to it</summary>
public sealed record PlayoutNowPlaying
{
    [JsonPropertyName("item")]
    public required PlayoutItem Item { get; init; }

    /// <summary>Unix epoch millis, as observed when the player reported it</summary>
    [JsonPropertyName("startedAt")]
    public required long StartedAt { get; init; }

    /// <summary>The decoder's own countdown, absent when it cannot say. It leads the listener by the encoder and client buffers</summary>
    [JsonPropertyName("remainingMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? RemainingMs { get; init; }
}

/// <summary>One gate's answer about itself</summary>
public sealed record SilenceCheck
{
    /// <summary>Never `airing`, which is the absence of a blocking gate rather than a gate</summary>
    [JsonPropertyName("code")]
    public required SilenceCause Code { get; init; }

    [JsonPropertyName("state")]
    public required SilenceState State { get; init; }

    /// <summary>What this gate is doing right now, whether or not it is the one blocking</summary>
    [JsonPropertyName("detail")]
    public required string Detail { get; init; }

    /// <summary>What would clear it, where there is something an operator can actually do</summary>
    [JsonPropertyName("remedy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Remedy { get; init; }
}

/// <summary>Why the station cannot be heard, as one answer</summary>
public sealed record StationSilence
{
    /// <summary>Whether the station believes its programme is reaching the mount. NOT whether anybody is hearing it: a station can be audible with no listeners in `always` mode, and can have listeners while airing the local bed</summary>
    [JsonPropertyName("audible")]
    public required bool Audible { get; init; }

    [JsonPropertyName("cause")]
    public required SilenceCause Cause { get; init; }

    [JsonPropertyName("detail")]
    public required string Detail { get; init; }

    [JsonPropertyName("remedy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Remedy { get; init; }

    /// <summary>Every gate, in the order they are judged, so a console can say what it ruled out. A `configNotAdopted` fault appears here and is never the cause, because a station can air perfectly well while it is true</summary>
    [JsonPropertyName("checks")]
    public required List<SilenceCheck> Checks { get; init; }
}

/// <summary>The station's transport, as one reading</summary>
public sealed record PlayoutStatus
{
    /// <summary>Whether Liquidsoap's control API is answering at all. False means nothing can air, whatever the running order holds</summary>
    [JsonPropertyName("streamUp")]
    public required bool StreamUp { get; init; }

    /// <summary>Whether the station is actually broadcasting. deadair holds the mount on a lease it renews only while it has a programme, so a reachable stream with nothing to play is up and NOT on air: it is connected, and airing silence</summary>
    [JsonPropertyName("onAir")]
    public required bool OnAir { get; init; }

    /// <summary>Same-origin path of the Icecast MP3 mount, which is always published and is the one a console names when it can only name one. A path rather than a URL: the browser reaches Icecast through whatever edge served the SPA, never at the address the app itself uses</summary>
    [JsonPropertyName("mountPath")]
    public required string MountPath { get; init; }

    /// <summary>Every mount being published, MP3 first, so a console can offer the others rather than implying the station is only on one. Never empty: MP3 has no switch. A format the operator has not switched on is absent rather than present and disabled, because every consumer of this wants the mounts that are actually there</summary>
    [JsonPropertyName("mounts")]
    public required List<PlayoutMount> Mounts { get; init; }

    [JsonPropertyName("nowPlaying")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlayoutNowPlaying? NowPlaying { get; init; }

    /// <summary>Waiting here, in order. Excludes what the player already holds</summary>
    [JsonPropertyName("upNext")]
    public required List<PlayoutItem> UpNext { get; init; }

    /// <summary>How many items are waiting in total, of which `upNext` is the head</summary>
    [JsonPropertyName("queuedCount")]
    public required long QueuedCount { get; init; }

    /// <summary>How many clients Icecast has attached to the mount. Zero both for "nobody is listening" and for an Icecast that is not answering, which `audience` is where to tell apart</summary>
    [JsonPropertyName("listeners")]
    public required long Listeners { get; init; }

    /// <summary>Whether the station counts as having an audience, which lingers for a minute past the last listener so a reconnecting player does not cut the broadcast</summary>
    [JsonPropertyName("audience")]
    public required bool Audience { get; init; }

    /// <summary>Containers running config the app has since replaced. Empty is the ordinary state, and so is empty for anything the app has no evidence about: a warning here has never been a guess</summary>
    [JsonPropertyName("staleStreamConfig")]
    public required List<StreamConfigWarning> StaleStreamConfig { get; init; }

    /// <summary>Which gate is keeping the station quiet, composed from every one of them rather than inferred from the fields above. `streamUp`, `onAir`, `audience` and `queuedCount` each answer for one gate and a console reading them alone has to guess at the rest</summary>
    [JsonPropertyName("silence")]
    public required StationSilence Silence { get; init; }
}

/// <summary>Which way round to play it. Absent is `countdown`, which opens on the lowest rank and ends on number one</summary>
[JsonConverter(typeof(JsonStringEnumConverter<PlayoutChartInputChartOrder>))]
public enum PlayoutChartInputChartOrder
{
    [JsonStringEnumMemberName("countdown")]
    Countdown,

    [JsonStringEnumMemberName("ranked")]
    Ranked,

    [JsonStringEnumMemberName("unordered")]
    Unordered,
}

/// <summary>Which one is behind</summary>
[JsonConverter(typeof(JsonStringEnumConverter<StreamConfigWarningContainer>))]
public enum StreamConfigWarningContainer
{
    [JsonStringEnumMemberName("icecast")]
    Icecast,

    [JsonStringEnumMemberName("liquidsoap")]
    Liquidsoap,
}

[JsonConverter(typeof(JsonStringEnumConverter<PlayoutMountFormat>))]
public enum PlayoutMountFormat
{
    [JsonStringEnumMemberName("mp3")]
    Mp3,

    [JsonStringEnumMemberName("opus")]
    Opus,

    [JsonStringEnumMemberName("aac")]
    Aac,

    [JsonStringEnumMemberName("flac")]
    Flac,
}

/// <summary>`starved`: the queue stopped producing while deadair was driving, so the mount fell through to the local bed. `recovered`: it is producing again</summary>
[JsonConverter(typeof(JsonStringEnumConverter<PlayoutStarveQueryState>))]
public enum PlayoutStarveQueryState
{
    [JsonStringEnumMemberName("starved")]
    Starved,

    [JsonStringEnumMemberName("recovered")]
    Recovered,
}
