// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>A record the station holds and could be asked for</summary>
public sealed record RequestableTrack
{
    /// <summary>What to send as `trackId` to make the request</summary>
    [JsonPropertyName("trackId")]
    public required Guid TrackId { get; init; }

    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>The lead artist</summary>
    [JsonPropertyName("artist")]
    public required string Artist { get; init; }

    [JsonPropertyName("album")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Album { get; init; }

    [JsonPropertyName("year")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Year { get; init; }
}

[JsonConverter(typeof(JsonStringEnumConverter<RequestStatus>))]
public enum RequestStatus
{
    [JsonStringEnumMemberName("waiting")]
    Waiting,

    [JsonStringEnumMemberName("pending")]
    Pending,

    [JsonStringEnumMemberName("queued")]
    Queued,

    [JsonStringEnumMemberName("aired")]
    Aired,

    [JsonStringEnumMemberName("declined")]
    Declined,

    [JsonStringEnumMemberName("expired")]
    Expired,
}

[JsonConverter(typeof(JsonStringEnumConverter<RequestSource>))]
public enum RequestSource
{
    [JsonStringEnumMemberName("app")]
    App,

    [JsonStringEnumMemberName("chat")]
    Chat,
}

/// <summary>Ask the station to play a record</summary>
public sealed record ListenerRequestCreate
{
    /// <summary>A record from the request search</summary>
    [JsonPropertyName("trackId")]
    public required Guid TrackId { get; init; }

    /// <summary>What the station should call you. Omitted, you are "a listener": your account's email address is never shown or read out</summary>
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }

    /// <summary>Dedicate it to somebody. The station may say this name on air</summary>
    [JsonPropertyName("dedicateTo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? DedicateTo { get; init; }

    /// <summary>A few words to go with it. The presenter may put them in their own words on air, and leaves out anything unfit to broadcast; the words themselves are never read out</summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; init; }
}

/// <summary>Turn a request down</summary>
public sealed record ListenerRequestDecline
{
    /// <summary>What to tell the listener. Omit for a plain no</summary>
    [JsonPropertyName("reason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Reason { get; init; }
}

/// <summary>Records matching a search, best matches first</summary>
public sealed record RequestableTrackList
{
    [JsonPropertyName("tracks")]
    public required List<RequestableTrack> Tracks { get; init; }
}

/// <summary>A record somebody asked the station to play, and what became of it</summary>
public sealed record ListenerRequest
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>`waiting` for an operator to approve it, `pending` while its audio is fetched or a place is found for it, `queued` in the running order, `aired` once heard, `declined` or `expired` when it never will be</summary>
    [JsonPropertyName("status")]
    public required RequestStatus Status { get; init; }

    /// <summary>The record, as it was called when it was asked for</summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    [JsonPropertyName("artist")]
    public required string Artist { get; init; }

    /// <summary>Who asked, by the name their account or chat platform gave</summary>
    [JsonPropertyName("requesterName")]
    public required string RequesterName { get; init; }

    /// <summary>Whether it came from an app or a chat platform</summary>
    [JsonPropertyName("source")]
    public required RequestSource Source { get; init; }

    /// <summary>When it was asked for</summary>
    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>Why it was declined or expired, in the station's words or an operator's</summary>
    [JsonPropertyName("reason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Reason { get; init; }

    /// <summary>When it aired</summary>
    [JsonPropertyName("airedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? AiredAt { get; init; }

    /// <summary>Who the listener dedicated it to</summary>
    [JsonPropertyName("dedicateTo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? DedicateTo { get; init; }

    /// <summary>What the listener asked to have said with it, in their own words</summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; init; }
}

/// <summary>Requests, newest first</summary>
public sealed record ListenerRequestList
{
    [JsonPropertyName("requests")]
    public required List<ListenerRequest> Requests { get; init; }
}
