// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>
/// A never-play rule: a KIND of record the station must not play. Absolute, like a dislike, and
/// exclude-only: there is no "only these" rule, because one could leave the station nothing to play.
/// Every scope is optional and an absent one means "always"
/// </summary>
public sealed record BlockRule
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>`genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag</summary>
    [JsonPropertyName("field")]
    public required BlockRuleField Field { get; init; }

    /// <summary>The genre or tag, as you would write it</summary>
    [JsonPropertyName("value")]
    public required string Value { get; init; }

    /// <summary>First day it holds, as `MM-DD`. With `seasonTo`; a season starting after it ends wraps the year end</summary>
    [JsonPropertyName("seasonFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SeasonFrom { get; init; }

    /// <summary>Last day it holds, as `MM-DD`</summary>
    [JsonPropertyName("seasonTo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SeasonTo { get; init; }

    /// <summary>First hour of the station's day it holds. With `untilHour`; a window starting after it ends wraps midnight</summary>
    [JsonPropertyName("fromHour")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? FromHour { get; init; }

    /// <summary>The hour it stops holding, exclusive</summary>
    [JsonPropertyName("untilHour")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? UntilHour { get; init; }

    /// <summary>Only while the station is in one of these modes. Absent or empty means every mode</summary>
    [JsonPropertyName("modes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<BlockRuleModes>? Modes { get; init; }

    /// <summary>Only during these schedule blocks. Absent or empty means whatever is on</summary>
    [JsonPropertyName("slotIds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? SlotIds { get; init; }

    /// <summary>When it stops holding. Absent means until it is removed</summary>
    [JsonPropertyName("endsAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? EndsAt { get; init; }

    /// <summary>Whether it holds right now, on the station's clock, for what is on air</summary>
    [JsonPropertyName("inForce")]
    public required bool InForce { get; init; }
}

/// <summary>
/// A never-play rule: a KIND of record the station must not play. Absolute, like a dislike, and
/// exclude-only: there is no "only these" rule, because one could leave the station nothing to play.
/// Every scope is optional and an absent one means "always"
/// </summary>
public sealed record BlockRuleInput
{
    /// <summary>`genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag</summary>
    [JsonPropertyName("field")]
    public required BlockRuleField Field { get; init; }

    /// <summary>The genre or tag, as you would write it</summary>
    [JsonPropertyName("value")]
    public required string Value { get; init; }

    /// <summary>First day it holds, as `MM-DD`. With `seasonTo`; a season starting after it ends wraps the year end</summary>
    [JsonPropertyName("seasonFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SeasonFrom { get; init; }

    /// <summary>Last day it holds, as `MM-DD`</summary>
    [JsonPropertyName("seasonTo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SeasonTo { get; init; }

    /// <summary>First hour of the station's day it holds. With `untilHour`; a window starting after it ends wraps midnight</summary>
    [JsonPropertyName("fromHour")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? FromHour { get; init; }

    /// <summary>The hour it stops holding, exclusive</summary>
    [JsonPropertyName("untilHour")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? UntilHour { get; init; }

    /// <summary>Only while the station is in one of these modes. Absent or empty means every mode</summary>
    [JsonPropertyName("modes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<BlockRuleModes>? Modes { get; init; }

    /// <summary>Only during these schedule blocks. Absent or empty means whatever is on</summary>
    [JsonPropertyName("slotIds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? SlotIds { get; init; }

    /// <summary>When it stops holding. Absent means until it is removed</summary>
    [JsonPropertyName("endsAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? EndsAt { get; init; }
}

/// <summary>
/// A lean toward some genres for a while. The opposite of a rule: the station favours them when it
/// chooses records, and still plays anything else rather than run dry
/// </summary>
public sealed record GenreSteer
{
    /// <summary>What to favour, as genres. A record tagged with any of them, or a kind of one, is preferred</summary>
    [JsonPropertyName("genres")]
    public required List<string> Genres { get; init; }

    /// <summary>When the station goes back to choosing as it ordinarily does</summary>
    [JsonPropertyName("endsAt")]
    public required DateTimeOffset EndsAt { get; init; }
}

/// <summary>Lean the station toward some genres for a number of hours</summary>
public sealed record GenreSteerInput
{
    [JsonPropertyName("genres")]
    public required List<string> Genres { get; init; }

    /// <summary>How long it lasts, from now</summary>
    [JsonPropertyName("hours")]
    public required long Hours { get; init; }
}

/// <summary>Every rule on the station, newest first</summary>
public sealed record BlockRuleList
{
    [JsonPropertyName("rules")]
    public required List<BlockRule> Rules { get; init; }
}

/// <summary>Every rule on the station, newest first</summary>
public sealed record BlockRuleListInput
{
    [JsonPropertyName("rules")]
    public required List<BlockRuleInput> Rules { get; init; }
}

/// <summary>The lean in force, or none</summary>
public sealed record GenreSteerReading
{
    /// <summary>Absent when nothing is leaning the station, including once one has run out</summary>
    [JsonPropertyName("steer")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public GenreSteer? Steer { get; init; }
}

/// <summary>`genre` refuses any record tagged with this genre or a kind of it (`Punk Rock` under `Punk`, never `Pop` under `Pop Punk`, never `Trap` under `Rap`). `tag` refuses a record carrying exactly this tag</summary>
[JsonConverter(typeof(JsonStringEnumConverter<BlockRuleField>))]
public enum BlockRuleField
{
    [JsonStringEnumMemberName("genre")]
    Genre,

    [JsonStringEnumMemberName("tag")]
    Tag,
}

[JsonConverter(typeof(JsonStringEnumConverter<BlockRuleModes>))]
public enum BlockRuleModes
{
    [JsonStringEnumMemberName("rotation")]
    Rotation,

    [JsonStringEnumMemberName("setlist")]
    Setlist,

    [JsonStringEnumMemberName("feature")]
    Feature,
}
