// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>Which part of the console owns a setting. Every one of these but `schedule` is a section of the settings page; `schedule` is edited on the schedule page, beside the timetable it describes.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<SettingGroup>))]
public enum SettingGroup
{
    [JsonStringEnumMemberName("station")]
    Station,

    [JsonStringEnumMemberName("stream")]
    Stream,

    [JsonStringEnumMemberName("housekeeping")]
    Housekeeping,

    [JsonStringEnumMemberName("secrets")]
    Secrets,

    [JsonStringEnumMemberName("mail")]
    Mail,

    [JsonStringEnumMemberName("rotation")]
    Rotation,

    [JsonStringEnumMemberName("playout")]
    Playout,

    [JsonStringEnumMemberName("render")]
    Render,

    [JsonStringEnumMemberName("llm")]
    Llm,

    [JsonStringEnumMemberName("analysis")]
    Analysis,

    [JsonStringEnumMemberName("schedule")]
    Schedule,
}

/// <summary>
/// A submitted settings form. Partial: a key that is present is written, a key that is absent is left
/// alone, so a console may send one field. A secret submitted blank clears it
/// </summary>
public sealed record StationSettingsInput
{
    [JsonPropertyName("values")]
    public required Dictionary<string, JsonElement> Values { get; init; }
}

/// <summary>
/// A station setting as the console needs to render it. `ConfigFieldDescriptor` is the plugins area's,
/// and shared deliberately: a plugin's settings form and the station's are the same problem, and the
/// console renders both with one component
/// </summary>
public sealed record StationSettingDescriptor
{
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    [JsonPropertyName("label")]
    public required string Label { get; init; }

    [JsonPropertyName("type")]
    public required ConfigFieldType Type { get; init; }

    [JsonPropertyName("required")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Required { get; init; }

    [JsonPropertyName("default")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConfigFieldDescriptorDefault? Default { get; init; }

    /// <summary>`number` only, and ignored elsewhere</summary>
    [JsonPropertyName("unit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConfigFieldUnit? Unit { get; init; }

    /// <summary>`slider` for a `number` with both `min` and `max`, `tags` for a `string` holding a comma-separated set</summary>
    [JsonPropertyName("control")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConfigFieldControl? Control { get; init; }

    /// <summary>How coarsely a `control` moves, in the field's own unit. Ignored without one, and defaults to 1</summary>
    [JsonPropertyName("step")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Step { get; init; }

    /// <summary>`number` only: the smallest value that will be accepted, inclusive</summary>
    [JsonPropertyName("min")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Min { get; init; }

    /// <summary>`number` only: the largest value that will be accepted, inclusive</summary>
    [JsonPropertyName("max")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Max { get; init; }

    [JsonPropertyName("placeholder")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Placeholder { get; init; }

    [JsonPropertyName("help")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Help { get; init; }

    [JsonPropertyName("options")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ConfigFieldOption>? Options { get; init; }

    /// <summary>Choices only the console can enumerate. Merged where a plugin's own suggestions are, and outranked by them</summary>
    [JsonPropertyName("optionsFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConfigFieldOptionSource? OptionsFrom { get; init; }

    /// <summary>`list` only, and ignored elsewhere</summary>
    [JsonPropertyName("columns")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ConfigFieldColumn>? Columns { get; init; }

    /// <summary>Key of the field this one is only relevant to</summary>
    [JsonPropertyName("dependsOn")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? DependsOn { get; init; }

    /// <summary>Key of the `number` field that is the upper end of the range this one opens, declared on the lower end only. Still two settings, each validated by name; the console draws them as one control whose handles cannot cross</summary>
    [JsonPropertyName("rangeWith")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RangeWith { get; init; }

    [JsonPropertyName("group")]
    public required SettingGroup Group { get; init; }
}

/// <summary>Every station setting, with what it is currently worth</summary>
public sealed record StationSettings
{
    [JsonPropertyName("descriptors")]
    public required List<StationSettingDescriptor> Descriptors { get; init; }

    /// <summary>Every NON-secret setting, with defaults filled in for whatever is not stored</summary>
    [JsonPropertyName("values")]
    public required Dictionary<string, JsonElement> Values { get; init; }

    /// <summary>One entry per `secret` setting: whether a value is currently stored. Never the value itself</summary>
    [JsonPropertyName("configured")]
    public required Dictionary<string, bool> Configured { get; init; }
}
