// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using MaroonedSoftware.Deadair.Sdk.Runtime;

namespace MaroonedSoftware.Deadair.Sdk.Models;

/// <summary>
/// A playlist the station owns: records it holds in its own library, in an order somebody chose, cloned
/// from somewhere else and free to differ from it afterwards
/// </summary>
public sealed record StationPlaylist
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>What this playlist is for, in the operator's own words. Empty when nobody said</summary>
    [JsonPropertyName("prompt")]
    public required string Prompt { get; init; }

    /// <summary>The plugin this was cloned from, for a badge and nothing else. Absent for one read from a file or made here</summary>
    [JsonPropertyName("originPluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OriginPluginId { get; init; }

    /// <summary>Every row, placeholders included</summary>
    [JsonPropertyName("trackCount")]
    public required long TrackCount { get; init; }

    /// <summary>The rows that name a record in the library, which are the ones that can air</summary>
    [JsonPropertyName("resolvedCount")]
    public required long ResolvedCount { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("updatedAt")]
    public required DateTimeOffset UpdatedAt { get; init; }
}

/// <summary>
/// A playlist the station owns: records it holds in its own library, in an order somebody chose, cloned
/// from somewhere else and free to differ from it afterwards
/// </summary>
public sealed record StationPlaylistInput
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>What this playlist is for, in the operator's own words. Empty when nobody said</summary>
    [JsonPropertyName("prompt")]
    public required string Prompt { get; init; }
}

/// <summary>One row of a station playlist: a record in the library, or a placeholder for one it does not hold yet</summary>
public sealed record StationPlaylistTrack
{
    /// <summary>The row's own id, not the record's</summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("position")]
    public required long Position { get; init; }

    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>Ordered, primary artist first</summary>
    [JsonPropertyName("artists")]
    public required List<string> Artists { get; init; }

    [JsonPropertyName("album")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Album { get; init; }

    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DurationMs { get; init; }

    /// <summary>The library record this row plays. Absent on a placeholder</summary>
    [JsonPropertyName("trackId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TrackId { get; init; }

    [JsonPropertyName("artistId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ArtistId { get; init; }

    [JsonPropertyName("albumId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AlbumId { get; init; }

    /// <summary>On a placeholder, the plugin whose copy it was cloned from. Absent on one read from a file, which names a record and no copy of it</summary>
    [JsonPropertyName("originPluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OriginPluginId { get; init; }
}

/// <summary>What may change about a station playlist after it exists. Absent fields are left alone</summary>
public sealed record StationPlaylistUpdate
{
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }

    [JsonPropertyName("prompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Prompt { get; init; }
}

/// <summary>
/// Where a record in a file came from, when it came from a provider's copy. Carried so a record the
/// receiving library does not hold can still be matched by that copy later
/// </summary>
public sealed record PlaylistFileOrigin
{
    [JsonPropertyName("pluginId")]
    public required string PluginId { get; init; }

    [JsonPropertyName("externalId")]
    public required string ExternalId { get; init; }
}

/// <summary>A playlist one of the station's music sources holds, named the way the playlists listing names it</summary>
public sealed record PlaylistProviderRef
{
    [JsonPropertyName("pluginId")]
    public required string PluginId { get; init; }

    [JsonPropertyName("playlistId")]
    public required string PlaylistId { get; init; }
}

/// <summary>What importing one record would do here</summary>
public sealed record PlaylistImportEntry
{
    [JsonPropertyName("position")]
    public required long Position { get; init; }

    [JsonPropertyName("title")]
    public required string Title { get; init; }

    [JsonPropertyName("artists")]
    public required List<string> Artists { get; init; }

    /// <summary>`matched`: the library holds it. `toAdd`: it names a provider's copy, which the station can add to its library. `toLookUp`: it names only a record, which the station has to search its providers for</summary>
    [JsonPropertyName("outcome")]
    public required PlaylistImportEntryOutcome Outcome { get; init; }

    /// <summary>The library record a `matched` row plays</summary>
    [JsonPropertyName("trackId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TrackId { get; init; }
}

public sealed record StationPlaylistList
{
    [JsonPropertyName("playlists")]
    public required List<StationPlaylist> Playlists { get; init; }
}

public sealed record StationPlaylistListInput
{
    [JsonPropertyName("playlists")]
    public required List<StationPlaylistInput> Playlists { get; init; }
}

public sealed record StationPlaylistDetail
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>What this playlist is for, in the operator's own words. Empty when nobody said</summary>
    [JsonPropertyName("prompt")]
    public required string Prompt { get; init; }

    /// <summary>The plugin this was cloned from, for a badge and nothing else. Absent for one read from a file or made here</summary>
    [JsonPropertyName("originPluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OriginPluginId { get; init; }

    /// <summary>Every row, placeholders included</summary>
    [JsonPropertyName("trackCount")]
    public required long TrackCount { get; init; }

    /// <summary>The rows that name a record in the library, which are the ones that can air</summary>
    [JsonPropertyName("resolvedCount")]
    public required long ResolvedCount { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("updatedAt")]
    public required DateTimeOffset UpdatedAt { get; init; }

    [JsonPropertyName("tracks")]
    public required List<StationPlaylistTrack> Tracks { get; init; }
}

public sealed record StationPlaylistDetailInput
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>What this playlist is for, in the operator's own words. Empty when nobody said</summary>
    [JsonPropertyName("prompt")]
    public required string Prompt { get; init; }

    [JsonPropertyName("tracks")]
    public required List<StationPlaylistTrack> Tracks { get; init; }
}

/// <summary>
/// One record as a playlist file names it. By its words and its ISRC, never by an id of this station's:
/// ids are minted afresh by every library, so a file keyed by them would restore onto nothing
/// </summary>
public sealed record PlaylistFileTrack
{
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>Ordered, primary artist first</summary>
    [JsonPropertyName("artists")]
    public required List<string> Artists { get; init; }

    [JsonPropertyName("album")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Album { get; init; }

    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DurationMs { get; init; }

    [JsonPropertyName("isrc")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Isrc { get; init; }

    [JsonPropertyName("origin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlaylistFileOrigin? Origin { get; init; }
}

/// <summary>What an import WOULD do, written nowhere</summary>
public sealed record PlaylistImportPlan
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("matched")]
    public required long Matched { get; init; }

    [JsonPropertyName("toAdd")]
    public required long ToAdd { get; init; }

    [JsonPropertyName("toLookUp")]
    public required long ToLookUp { get; init; }

    /// <summary>Lines of the source that named no record the station could read</summary>
    [JsonPropertyName("skipped")]
    public required long Skipped { get; init; }

    [JsonPropertyName("entries")]
    public required List<PlaylistImportEntry> Entries { get; init; }

    /// <summary>Anything about the source as a whole an operator should know before importing it</summary>
    [JsonPropertyName("notices")]
    public required List<string> Notices { get; init; }
}

/// <summary>A playlist as a file: everything somebody would need to rebuild it on another station</summary>
public sealed record PlaylistFile
{
    /// <summary>What shape this is, so a file from a later build says so rather than being read wrongly</summary>
    [JsonPropertyName("format")]
    public required string Format { get; init; }

    /// <summary>When it was exported, ISO-8601</summary>
    [JsonPropertyName("takenAt")]
    public required string TakenAt { get; init; }

    /// <summary>The station it was taken from. Provenance only</summary>
    [JsonPropertyName("station")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Station { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("prompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Prompt { get; init; }

    [JsonPropertyName("tracks")]
    public required List<PlaylistFileTrack> Tracks { get; init; }
}

public sealed record PlaylistImportResult
{
    [JsonPropertyName("plan")]
    public required PlaylistImportPlan Plan { get; init; }

    [JsonPropertyName("playlist")]
    public required StationPlaylist Playlist { get; init; }
}

public sealed record PlaylistImportResultInput
{
    [JsonPropertyName("plan")]
    public required PlaylistImportPlan Plan { get; init; }

    [JsonPropertyName("playlist")]
    public required StationPlaylistInput Playlist { get; init; }
}

/// <summary>Something to import a playlist from. Exactly one source</summary>
public sealed record PlaylistImportInput
{
    /// <summary>A playlist exported from a deadair station</summary>
    [JsonPropertyName("file")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlaylistFile? File { get; init; }

    /// <summary>A playlist another program wrote, as its text: an M3U, a CSV with a header row, or one `Artist - Title` per line</summary>
    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Text { get; init; }

    /// <summary>Which of those `text` is. Absent works it out from the text</summary>
    [JsonPropertyName("format")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlaylistImportInputFormat? Format { get; init; }

    /// <summary>The name of the file `text` came from, which names the playlist when the text does not</summary>
    [JsonPropertyName("fileName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? FileName { get; init; }

    /// <summary>A link to a playlist at one of the station's music sources, as a browser or an app shows it</summary>
    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Url { get; init; }

    /// <summary>A playlist a music source lists here, by its plugin and its id</summary>
    [JsonPropertyName("providerPlaylist")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PlaylistProviderRef? ProviderPlaylist { get; init; }

    /// <summary>What to call the new playlist. Absent keeps the name the source gives it</summary>
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }
}

/// <summary>Which of those `text` is. Absent works it out from the text</summary>
[JsonConverter(typeof(JsonStringEnumConverter<PlaylistImportInputFormat>))]
public enum PlaylistImportInputFormat
{
    [JsonStringEnumMemberName("m3u")]
    M3u,

    [JsonStringEnumMemberName("csv")]
    Csv,

    [JsonStringEnumMemberName("text")]
    Text,
}

/// <summary>`matched`: the library holds it. `toAdd`: it names a provider's copy, which the station can add to its library. `toLookUp`: it names only a record, which the station has to search its providers for</summary>
[JsonConverter(typeof(JsonStringEnumConverter<PlaylistImportEntryOutcome>))]
public enum PlaylistImportEntryOutcome
{
    [JsonStringEnumMemberName("matched")]
    Matched,

    [JsonStringEnumMemberName("toAdd")]
    ToAdd,

    [JsonStringEnumMemberName("toLookUp")]
    ToLookUp,
}
