/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { DateTime } from "luxon";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface DeadairActors {
  active: Generated<boolean>;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  type: "user" | "system" | "vendor";
  updatedAt: Generated<DateTime>;
}

export interface DeadairActorsAuthenticatorFactors {
  active: Generated<boolean>;
  actorId: string;
  algorithm: "sha1" | "sha256" | "sha512";
  counter: number;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  label: string | null;
  periodSeconds: number;
  secret: string;
  secretDek: string;
  tokenLength: number;
  type: "totp" | "hotp";
  updatedAt: Generated<DateTime>;
}

export interface DeadairActorsEmailFactors {
  active: Generated<boolean>;
  actorId: string;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  updatedAt: Generated<DateTime>;
  value: string;
}

export interface DeadairActorSessionEvents {
  actorId: string;
  eventType: "created" | "refreshed" | "revoked" | "expired" | "step_up" | "validation_failed";
  id: Generated<bigint>;
  ip: string | null;
  metadata: Json | null;
  occurredAt: Generated<DateTime>;
  sessionToken: string;
  userAgent: string | null;
}

export interface DeadairActorsFidoFactors {
  active: Generated<boolean>;
  actorId: string;
  counter: number;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  label: string | null;
  publicKey: string;
  publicKeyId: string;
  updatedAt: Generated<DateTime>;
}

export interface DeadairActorsOidcFactors {
  active: Generated<boolean>;
  actorId: string;
  createdAt: Generated<DateTime>;
  email: string | null;
  encryptedRefreshToken: string | null;
  encryptedRefreshTokenDek: string | null;
  id: Generated<string>;
  picture: string | null;
  provider: string;
  refreshTokenExpiresAt: DateTime | null;
  subject: string;
  updatedAt: Generated<DateTime>;
}

export interface DeadairActorsPasswordFactors {
  active: Generated<boolean>;
  actorId: string;
  createdAt: Generated<DateTime>;
  hash: string;
  needsReset: Generated<boolean>;
  salt: string;
  updatedAt: Generated<DateTime>;
}

export interface DeadairActorsPasswordFactorsArchive {
  actorId: string;
  archivedAt: Generated<DateTime>;
  hash: string;
  id: Generated<string>;
  salt: string;
}

export interface DeadairAlbumEnrichment {
  albumId: string;
  createdAt: Generated<DateTime>;
  data: Json;
  expiresAt: DateTime | null;
  fetchedAt: Generated<DateTime>;
  id: Generated<string>;
  provider: string;
  providerRef: string | null;
  updatedAt: Generated<DateTime>;
}

export interface DeadairAlbums {
  artistId: string;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  imageUrl: string | null;
  mbid: string | null;
  mergedIntoId: string | null;
  name: string;
  nameKey: string;
  rating: Generated<number>;
  updatedAt: Generated<DateTime>;
  year: number | null;
}

export interface DeadairAlbumSources {
  albumId: string;
  coverArtId: string | null;
  createdAt: Generated<DateTime>;
  externalId: string;
  id: Generated<string>;
  lastSeenAt: DateTime | null;
  missingAt: DateTime | null;
  pluginId: string;
  raw: Json | null;
  updatedAt: Generated<DateTime>;
  uri: string | null;
}

export interface DeadairArtAssets {
  attempts: Generated<number>;
  byteSize: number | null;
  checksum: string | null;
  contentType: string | null;
  createdAt: Generated<DateTime>;
  ext: string | null;
  fetchedAt: DateTime | null;
  id: Generated<string>;
  lastError: string | null;
  nextAttemptAt: DateTime | null;
  sourceUrl: string;
  updatedAt: Generated<DateTime>;
}

export interface DeadairArtistEnrichment {
  artistId: string;
  createdAt: Generated<DateTime>;
  data: Json;
  expiresAt: DateTime | null;
  fetchedAt: Generated<DateTime>;
  id: Generated<string>;
  provider: string;
  providerRef: string | null;
  updatedAt: Generated<DateTime>;
}

export interface DeadairArtists {
  artistKey: string;
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  imageUrl: string | null;
  mbid: string | null;
  mergedIntoId: string | null;
  name: string;
  rating: Generated<number>;
  updatedAt: Generated<DateTime>;
}

export interface DeadairArtistSources {
  artistId: string;
  createdAt: Generated<DateTime>;
  externalId: string;
  id: Generated<string>;
  imageUrl: string | null;
  lastSeenAt: DateTime | null;
  missingAt: DateTime | null;
  pluginId: string;
  raw: Json | null;
  updatedAt: Generated<DateTime>;
  uri: string | null;
}

export interface DeadairLineups {
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  items: Generated<Json>;
  mode: Generated<"rotation" | "setlist" | "feature">;
  name: string;
  onEnd: Generated<"extend" | "repeat" | "resume" | "rotation" | "stop">;
  revision: Generated<number>;
  rules: Json | null;
  source: Generated<string>;
  sourcePlaylistId: string | null;
  sourcePluginId: string | null;
  updatedAt: Generated<DateTime>;
}

export interface DeadairLoginEvents {
  actorId: string;
  factorId: string | null;
  factorType: string;
  id: Generated<bigint>;
  ip: string | null;
  mfaSatisfied: boolean;
  occurredAt: Generated<DateTime>;
  sessionToken: string | null;
  userAgent: string | null;
}

export interface DeadairLoginFailureCounters {
  actorId: string | null;
  attemptCount: Generated<number>;
  bucketStart: DateTime;
  factorType: string;
  identifier: string | null;
  identifierHash: string;
  ip: string;
  lastReason: string | null;
  lastSeenAt: Generated<DateTime>;
}

export interface DeadairPermissionsRelationTuples {
  createdAt: Generated<DateTime>;
  createdBy: string | null;
  id: Generated<string>;
  objectId: string;
  objectNamespace: string;
  relation: string;
  subjectId: string;
  subjectNamespace: string;
  subjectRelation: Generated<string>;
  updatedAt: Generated<DateTime>;
}

export interface DeadairPlayHistory {
  airedAt: Generated<DateTime>;
  artistKey: string;
  artists: string;
  createdAt: Generated<DateTime>;
  externalId: string;
  id: Generated<string>;
  pluginId: string;
  songKey: string;
  source: Generated<string>;
  title: string;
  trackId: string | null;
}

export interface DeadairPlaylists {
  createdAt: Generated<DateTime>;
  id: Generated<string>;
  name: string;
  originPluginId: string | null;
  prompt: Generated<string>;
  updatedAt: Generated<DateTime>;
}

export interface DeadairPlaylistTracks {
  id: Generated<string>;
  originExternalId: string | null;
  originPluginId: string | null;
  originSnapshot: Json | null;
  playlistId: string;
  position: number;
  trackId: string | null;
}

export interface DeadairPluginConfigs {
  config: Generated<Json>;
  createdAt: Generated<DateTime>;
  enabled: Generated<boolean>;
  lastError: string | null;
  logLevel: Generated<"debug" | "info" | "warn" | "error">;
  pluginId: string;
  secrets: Generated<Json>;
  status: string | null;
  updatedAt: Generated<DateTime>;
}

export interface DeadairPluginStorage {
  createdAt: Generated<DateTime>;
  key: string;
  pluginId: string;
  updatedAt: Generated<DateTime>;
  value: Json | null;
}

export interface DeadairSettings {
  createdAt: Generated<DateTime>;
  key: string;
  updatedAt: Generated<DateTime>;
  value: string | null;
}

export interface DeadairStationAir {
  active: Generated<boolean>;
  createdAt: Generated<DateTime>;
  cursor: Generated<number>;
  defaultLineupId: string | null;
  lineupId: string | null;
  resumeCursor: number | null;
  resumeLineupId: string | null;
  slot: Generated<string>;
  updatedAt: Generated<DateTime>;
}

export interface DeadairTrackEnrichment {
  createdAt: Generated<DateTime>;
  data: Json;
  expiresAt: DateTime | null;
  fetchedAt: Generated<DateTime>;
  id: Generated<string>;
  provider: string;
  providerRef: string | null;
  trackId: string;
  updatedAt: Generated<DateTime>;
}

export interface DeadairTracks {
  albumId: string | null;
  artistId: string;
  artists: string;
  createdAt: Generated<DateTime>;
  durationMs: number | null;
  genre: string | null;
  id: Generated<string>;
  mbid: string | null;
  mergedIntoId: string | null;
  rating: Generated<number>;
  title: string;
  titleKey: string;
  updatedAt: Generated<DateTime>;
  year: number | null;
}

export interface DeadairTrackSources {
  bitrate: number | null;
  coverArtId: string | null;
  createdAt: Generated<DateTime>;
  durationMs: number | null;
  externalId: string;
  format: string | null;
  id: Generated<string>;
  isrc: string | null;
  lastSeenAt: DateTime | null;
  missingAt: DateTime | null;
  playable: Generated<boolean>;
  pluginId: string;
  raw: Json | null;
  trackId: string;
  updatedAt: Generated<DateTime>;
  uri: string | null;
}

export interface SchemaMigrations {
  version: string;
}

export interface DB {
  "deadair.actors": DeadairActors;
  "deadair.actorsAuthenticatorFactors": DeadairActorsAuthenticatorFactors;
  "deadair.actorsEmailFactors": DeadairActorsEmailFactors;
  "deadair.actorSessionEvents": DeadairActorSessionEvents;
  "deadair.actorsFidoFactors": DeadairActorsFidoFactors;
  "deadair.actorsOidcFactors": DeadairActorsOidcFactors;
  "deadair.actorsPasswordFactors": DeadairActorsPasswordFactors;
  "deadair.actorsPasswordFactorsArchive": DeadairActorsPasswordFactorsArchive;
  "deadair.albumEnrichment": DeadairAlbumEnrichment;
  "deadair.albums": DeadairAlbums;
  "deadair.albumSources": DeadairAlbumSources;
  "deadair.artAssets": DeadairArtAssets;
  "deadair.artistEnrichment": DeadairArtistEnrichment;
  "deadair.artists": DeadairArtists;
  "deadair.artistSources": DeadairArtistSources;
  "deadair.lineups": DeadairLineups;
  "deadair.loginEvents": DeadairLoginEvents;
  "deadair.loginFailureCounters": DeadairLoginFailureCounters;
  "deadair.permissionsRelationTuples": DeadairPermissionsRelationTuples;
  "deadair.playHistory": DeadairPlayHistory;
  "deadair.playlists": DeadairPlaylists;
  "deadair.playlistTracks": DeadairPlaylistTracks;
  "deadair.pluginConfigs": DeadairPluginConfigs;
  "deadair.pluginStorage": DeadairPluginStorage;
  "deadair.settings": DeadairSettings;
  "deadair.stationAir": DeadairStationAir;
  "deadair.trackEnrichment": DeadairTrackEnrichment;
  "deadair.tracks": DeadairTracks;
  "deadair.trackSources": DeadairTrackSources;
  schemaMigrations: SchemaMigrations;
}
