// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `art.breaks.ck`.
public final class ArtBreaksClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// List break artwork
    /// Every kind the station holds a picture for
    public func listBreakArtwork() async throws -> BreakArtworkList {
        let request = SdkRequest(method: "GET", path: ["art", "breaks"])
        let response = try await http.execute(request)
        return try http.decodeJSON(BreakArtworkList.self, from: response)
    }

    /// Replace break artwork
    /// Puts an operator's own picture behind a kind of break. The id does not change, so a URL already on the wire keeps working and the ETag is what says the picture moved
    /// - Throws: `SdkError` on 400, 413, 415
    public func replaceBreakArtwork(kind: String, body: [MultipartPart]) async throws -> BreakArtworkList {
        var request = try SdkRequest(method: "POST", path: ["art", "breaks", http.segment(kind)])
        http.setMultipartBody(&request, body)
        let response = try await http.execute(request)
        return try http.decodeJSON(BreakArtworkList.self, from: response)
    }

    /// Revert break artwork
    /// Puts the picture this repository ships back. The shipped file is read at this moment rather than copied at install, so an upgrade that improved it is what comes back
    /// - Throws: `SdkError` on 404
    public func revertBreakArtwork(kind: String) async throws -> BreakArtworkList {
        let request = try SdkRequest(method: "DELETE", path: ["art", "breaks", http.segment(kind)])
        let response = try await http.execute(request)
        return try http.decodeJSON(BreakArtworkList.self, from: response)
    }
}
