// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `messaging.ck`.
public final class MessagingClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// List messaging links
    /// The chat accounts linked to the signed-in account
    public func listMessagingLinks() async throws -> MessagingLinkList {
        let request = SdkRequest(method: "GET", path: ["messaging", "links"])
        let response = try await http.execute(request)
        return try http.decodeJSON(MessagingLinkList.self, from: response)
    }

    /// Create messaging link code
    /// A new one-time code for linking a chat account. It replaces any earlier code and stops working after ten minutes
    public func createMessagingLinkCode() async throws -> MessagingLinkCode {
        let request = SdkRequest(method: "POST", path: ["messaging", "links", "code"])
        let response = try await http.execute(request)
        return try http.decodeJSON(MessagingLinkCode.self, from: response)
    }

    /// Remove messaging link
    /// Unlink a chat account. Its operator commands are refused from the next one on
    public func removeMessagingLink(pluginId: String, platformUserId: String) async throws {
        let request = try SdkRequest(method: "DELETE", path: ["messaging", "links", http.segment(pluginId), http.segment(platformUserId)])
        _ = try await http.execute(request)
    }
}
