// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `nowplaying.ck`.
public final class NowplayingClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// Get now playing
    /// What is on air right now. Answers 200 with `onAir: false` when the station is quiet, so a device polling this treats silence as an answer rather than an error
    public func getNowPlaying() async throws -> NowPlaying {
        let request = SdkRequest(method: "GET", path: ["nowplaying"])
        let response = try await http.execute(request)
        return try http.decodeJSON(NowPlaying.self, from: response)
    }

    /// Get now playing lyrics
    /// The words of the record on air, with what a player needs to follow along line by line
    public func getNowPlayingLyrics() async throws -> NowPlayingLyrics {
        let request = SdkRequest(method: "GET", path: ["nowplaying", "lyrics"])
        let response = try await http.execute(request)
        return try http.decodeJSON(NowPlayingLyrics.self, from: response)
    }
}
