// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `playlists.ck`.
public final class PlaylistsClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// List importable playlists
    /// Fans out across every installed plugin that declares AND implements the `catalog` capability
    public func listImportablePlaylists() async throws -> CatalogPlaylistPage {
        let request = SdkRequest(method: "GET", path: ["playlists"])
        let response = try await http.execute(request)
        return try http.decodeJSON(CatalogPlaylistPage.self, from: response)
    }

    /// Get playlist tracks
    /// One playlist's tracks from one plugin
    public func getPlaylistTracks(pluginId: String, playlistId: String) async throws -> CatalogPlaylistTracks {
        let request = try SdkRequest(method: "GET", path: ["playlists", http.segment(pluginId), http.segment(playlistId), "tracks"])
        let response = try await http.execute(request)
        return try http.decodeJSON(CatalogPlaylistTracks.self, from: response)
    }

    /// Hide playlist
    /// Hides one playlist from this station: the listing marks it hidden, the pickers stop offering it and the library sync stops reading it. Hiding one already hidden changes nothing
    public func hidePlaylist(pluginId: String, playlistId: String) async throws {
        let request = try SdkRequest(method: "PUT", path: ["playlists", http.segment(pluginId), http.segment(playlistId), "hidden"])
        _ = try await http.execute(request)
    }

    /// Show playlist
    /// Shows a hidden playlist again. Showing one that is not hidden changes nothing
    public func showPlaylist(pluginId: String, playlistId: String) async throws {
        let request = try SdkRequest(method: "DELETE", path: ["playlists", http.segment(pluginId), http.segment(playlistId), "hidden"])
        _ = try await http.execute(request)
    }

    /// Refresh playlists
    /// Reads every playlist on every music source again, in the background, rather than waiting for the next scheduled read. New records reach the library; records gone from every playlist are retired
    public func refreshPlaylists() async throws {
        let request = SdkRequest(method: "POST", path: ["playlists", "refresh"])
        _ = try await http.execute(request)
    }

    /// Refresh playlist
    /// Reads one playlist again, in the background. New records reach the library; a record taken out of it stays until the next full read judges it
    public func refreshPlaylist(pluginId: String, playlistId: String) async throws {
        let request = try SdkRequest(method: "POST", path: ["playlists", http.segment(pluginId), http.segment(playlistId), "refresh"])
        _ = try await http.execute(request)
    }
}
