// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `settings.ck`.
public final class SettingsClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// Get settings
    /// Every station setting, its descriptor and its current value
    public func getSettings() async throws -> StationSettings {
        let request = SdkRequest(method: "GET", path: ["settings"])
        let response = try await http.execute(request)
        return try http.decodeJSON(StationSettings.self, from: response)
    }

    /// Update settings
    /// Applies a submitted settings form and answers with the settings as they now stand
    public func updateSettings(body: StationSettingsInput) async throws -> StationSettings {
        var request = SdkRequest(method: "PUT", path: ["settings"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(StationSettings.self, from: response)
    }
}
