// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `station.ck`.
public final class StationClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// Read station attention
    /// Everything wrong or waiting, worst first, each with the console page that can act on it
    public func readStationAttention() async throws -> StationAttention {
        let request = SdkRequest(method: "GET", path: ["station", "attention"])
        let response = try await http.execute(request)
        return try http.decodeJSON(StationAttention.self, from: response)
    }

    /// Read station checkup
    /// The loops the station runs and how much of the library it has looked at
    public func readStationCheckup() async throws -> StationCheckup {
        let request = SdkRequest(method: "GET", path: ["station", "checkup"])
        let response = try await http.execute(request)
        return try http.decodeJSON(StationCheckup.self, from: response)
    }
}
