// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `topics.ck`.
public final class TopicsClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// List topics
    /// Every subject this station has named, for one sort of break or for all of them
    public func listTopics(query: TopicQuery? = nil) async throws -> TopicList {
        var request = SdkRequest(method: "GET", path: ["topics"])
        try http.addQuery(&request, query)
        let response = try await http.execute(request)
        return try http.decodeJSON(TopicList.self, from: response)
    }

    /// Create topic
    /// Names a new subject. Nothing uses it until something points at it
    public func createTopic(body: TopicInput) async throws -> TopicList {
        var request = SdkRequest(method: "POST", path: ["topics"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(TopicList.self, from: response)
    }

    /// List topic kinds
    /// Which sorts of break have subjects, and the form each one's settings are edited with
    public func listTopicKinds() async throws -> TopicKindList {
        let request = SdkRequest(method: "GET", path: ["topics", "kinds"])
        let response = try await http.execute(request)
        return try http.decodeJSON(TopicKindList.self, from: response)
    }

    /// Update topic
    /// Rewrites one subject. A break already written keeps the words it was given
    public func updateTopic(id: String, body: TopicInput) async throws -> TopicList {
        var request = try SdkRequest(method: "PUT", path: ["topics", http.segment(id)])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(TopicList.self, from: response)
    }

    /// Delete topic
    /// Removes a subject, and any band on the format clock that asked for it
    public func deleteTopic(id: String) async throws -> TopicList {
        let request = try SdkRequest(method: "DELETE", path: ["topics", http.segment(id)])
        let response = try await http.execute(request)
        return try http.decodeJSON(TopicList.self, from: response)
    }
}
