// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A value that can be read back out of an HTTP header. Header values arrive as text, so every type
/// a contract may declare on a response header knows how to parse itself from one.
public protocol HeaderDecodable {
    init?(headerValue: String)
}

extension String: HeaderDecodable {
    public init?(headerValue: String) {
        self = headerValue
    }
}

extension Int: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Double: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Bool: HeaderDecodable {
    public init?(headerValue: String) {
        switch headerValue.trimmingCharacters(in: .whitespaces).lowercased() {
        case "true", "1":
            self = true
        case "false", "0":
            self = false
        default:
            return nil
        }
    }
}

extension UUID: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(uuidString: headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Date: HeaderDecodable {
    public init?(headerValue: String) {
        guard let date = SdkJSON.parseDate(headerValue.trimmingCharacters(in: .whitespaces)) else { return nil }
        self = date
    }
}

/// An arbitrary-precision integer, kept as its digit string. Encodes as a plain digit string.
/// Decoding accepts a digit string, the `123n` form the TypeScript SDK emits, and a JSON number, so a
/// body written by any ContractKit client reads back here.
public struct BigIntValue: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let text = try? container.decode(String.self) {
            rawValue = text.hasSuffix("n") ? String(text.dropLast()) : text
        } else if let number = try? container.decode(Int64.self) {
            rawValue = String(number)
        } else if let number = try? container.decode(Double.self) {
            rawValue = JSONValue.text(for: number)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected a JSON string or number for BigIntValue")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}

/// An exact decimal number, kept as its source text. Travels as a quoted JSON string, never as a
/// JSON number: by the time a number reaches this type it has already been through a double, so
/// the precision the contract asked for is gone. Hand `rawValue` to whatever big-decimal library
/// you use for arithmetic.
/// 
/// The text must be plain digits, the form the OpenAPI `pattern` publishes and the server accepts:
/// no exponent, no `+`, no whitespace, no non-finite values. Decoding or encoding anything else throws.
public struct DecimalValue: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    private static let wireForm = #"^-?[0-9]+(\.[0-9]+)?$"#

    /// Whether the text is in the form this value travels in.
    public static func isWireForm(_ text: String) -> Bool {
        text.range(of: wireForm, options: .regularExpression) == text.startIndex..<text.endIndex
    }

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        let text = headerValue.trimmingCharacters(in: .whitespaces)
        guard Self.isWireForm(text) else { return nil }
        self.init(text)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let text = try container.decode(String.self)
        guard Self.isWireForm(text) else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "'\(text)' is not a valid DecimalValue.")
        }
        rawValue = text
    }

    public func encode(to encoder: Encoder) throws {
        guard Self.isWireForm(rawValue) else {
            throw EncodingError.invalidValue(rawValue, EncodingError.Context(codingPath: encoder.codingPath, debugDescription: "'\(rawValue)' is not a valid DecimalValue."))
        }
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}


/// A calendar date without a time zone, as ISO 8601 text: `2024-03-01`.
public struct LocalDate: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}


/// A time of day without a time zone, as ISO 8601 text: `13:45:00`.
public struct LocalTime: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}


/// A duration as ISO 8601 text: `PT1H30M`. Kept as text; Swift has no parser for the format.
public struct IsoDuration: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}
