export type JobNames =
    | 'fake'
    | 'catalog.sync'
    | 'catalog.resolve_placeholders'
    | 'catalog.enrich'
    | 'catalog.extract_facts'
    | 'catalog.cache_art'
    | 'catalog.analyze'
    | 'playout.cache_track'
    | 'playout.sweep_track_cache'
    | 'director.extend_lineup'
    | 'director.replan_lineup'
    | 'director.write_break'
    | 'render.segment'
    | 'render.prune_script_history'
    | 'activity.prune_events'
    | 'scrobble.flush';
